-- SQL Script to import Zones and Localities
-- Run this in the Supabase SQL Editor

-- 1. Insert unique zones
INSERT INTO public.zones (name, is_active)
VALUES
  ('Alrededores', true),
  ('CABA', true),
  ('Depósito', true),
  ('La Plata', true),
  ('Matanza', true),
  ('Microcentro (CABA)', true),
  ('Z. Cañuelas', true),
  ('Z. Korn', true),
  ('Z. Las Heras - Marcos Paz', true),
  ('Z. Lujan - Fátima', true),
  ('Z. Norte Escobar', true),
  ('Z. Norte Jose C. Paz', true),
  ('Z. Norte Pacheco', true),
  ('Z. Norte Pilar', true),
  ('Z. Norte San Martín', true),
  ('Z. Norte Zárate - Campana', true),
  ('Z. Sur. Avellaneda-Beraza.', true),
  ('Z. Sur. Eze-Lanus-Burz', true),
  ('Zona Rodriguez', true)
ON CONFLICT (name) DO NOTHING;

-- 2. Insert localities linked to their respective zones
INSERT INTO public.localities (name, zone_id, is_active)
VALUES
  ('Ferrari (Merlo)', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('Mariano Acosta', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('Merlo', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('Parque San Martin (Merlo)', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('Francisco Alvarez', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('La Reja', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('Paso del Rey', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('Ituzaingo', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('Libertad', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('San Antonio de Padua', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('Moreno', (SELECT id FROM public.zones WHERE name = 'Alrededores' LIMIT 1), true),
  ('Agronomía (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Almagro (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Barracas (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Belgrano (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Boedo (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('CABA', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Caballito (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Chacarita (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Coghlan (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Colegiales (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Flores (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Floresta (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('La Paternal (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Liniers (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Mataderos (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Monte Castro (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Nueva Pompeya (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Núñez (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Palermo (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Parque Avellaneda (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Parque Chacabuco (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Parque Chas (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Parque Patricios (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Saavedra (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Vélez Sársfield (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Versalles (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Crespo (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa del Parque (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Devoto (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa General Mitre (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Lugano (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Luro (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Ortúzar (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Pueyrredón (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Real (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Riachuelo (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Santa Rita (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Soldati (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Villa Urquiza (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Once (CABA)', (SELECT id FROM public.zones WHERE name = 'CABA' LIMIT 1), true),
  ('Depósito', (SELECT id FROM public.zones WHERE name = 'Depósito' LIMIT 1), true),
  ('Abasto', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Altos de San Lorenzo', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Arturo Seguí', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Berisso', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('City Bell', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Ensenada', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('El Pato', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Gonnet', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('La Plata', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Lisandro Olmos', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Los Hornos', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Melchor Romero', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Ringuelet', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('San Carlos', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Tolosa', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Transradio', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Villa Elisa', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Ing. Allan', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Villa Elvira', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Arana', (SELECT id FROM public.zones WHERE name = 'La Plata' LIMIT 1), true),
  ('Pontevedra', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Castelar', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Merlo Gomez', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Aldo Bonzi', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Ciudad Evita', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Ciudadela', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('González Catán', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Haedo', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Isidro Casanova', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('La Tablada', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Gregorio de Laferrere', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Lomas del Mirador', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Moron', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Rafael Castillo', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Ramos Mejia', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('San Justo', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Tapiales', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Villa Celina', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Villa Luzuriaga', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Villa Madero', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Villa Sarmiento', (SELECT id FROM public.zones WHERE name = 'Matanza' LIMIT 1), true),
  ('Recoleta (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('Balvanera (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('Constitución (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('La Boca (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('Monserrat (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('Puerto Madero (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('Retiro (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('San Cristóbal (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('San Nicolás (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('San Telmo (CABA)', (SELECT id FROM public.zones WHERE name = 'Microcentro (CABA)' LIMIT 1), true),
  ('Virrey del Pino', (SELECT id FROM public.zones WHERE name = 'Z. Cañuelas' LIMIT 1), true),
  ('20 de Junio (Matanza)', (SELECT id FROM public.zones WHERE name = 'Z. Cañuelas' LIMIT 1), true),
  ('Cañuelas', (SELECT id FROM public.zones WHERE name = 'Z. Cañuelas' LIMIT 1), true),
  ('Vicente Casares', (SELECT id FROM public.zones WHERE name = 'Z. Cañuelas' LIMIT 1), true),
  ('Alejandro Petión', (SELECT id FROM public.zones WHERE name = 'Z. Cañuelas' LIMIT 1), true),
  ('Máximo Paz', (SELECT id FROM public.zones WHERE name = 'Z. Cañuelas' LIMIT 1), true),
  ('La Unión', (SELECT id FROM public.zones WHERE name = 'Z. Cañuelas' LIMIT 1), true),
  ('Spegazzini', (SELECT id FROM public.zones WHERE name = 'Z. Cañuelas' LIMIT 1), true),
  ('Tristan Suarez', (SELECT id FROM public.zones WHERE name = 'Z. Cañuelas' LIMIT 1), true),
  ('Coronel Brandsen', (SELECT id FROM public.zones WHERE name = 'Z. Korn' LIMIT 1), true),
  ('Barrio Parque Las Acacias', (SELECT id FROM public.zones WHERE name = 'Z. Korn' LIMIT 1), true),
  ('Doomselar', (SELECT id FROM public.zones WHERE name = 'Z. Korn' LIMIT 1), true),
  ('Gral. Hornos', (SELECT id FROM public.zones WHERE name = 'Z. Las Heras - Marcos Paz' LIMIT 1), true),
  ('Gral. Las Heras', (SELECT id FROM public.zones WHERE name = 'Z. Las Heras - Marcos Paz' LIMIT 1), true),
  ('Marcos Paz', (SELECT id FROM public.zones WHERE name = 'Z. Las Heras - Marcos Paz' LIMIT 1), true),
  ('Villars', (SELECT id FROM public.zones WHERE name = 'Z. Las Heras - Marcos Paz' LIMIT 1), true),
  ('Alejandro Korn', (SELECT id FROM public.zones WHERE name = 'Z. Korn' LIMIT 1), true),
  ('Glew', (SELECT id FROM public.zones WHERE name = 'Z. Korn' LIMIT 1), true),
  ('Guernica', (SELECT id FROM public.zones WHERE name = 'Z. Korn' LIMIT 1), true),
  ('San Vicente', (SELECT id FROM public.zones WHERE name = 'Z. Korn' LIMIT 1), true),
  ('Luján', (SELECT id FROM public.zones WHERE name = 'Z. Lujan - Fátima' LIMIT 1), true),
  ('Fátima', (SELECT id FROM public.zones WHERE name = 'Z. Lujan - Fátima' LIMIT 1), true),
  ('Manzanares', (SELECT id FROM public.zones WHERE name = 'Z. Lujan - Fátima' LIMIT 1), true),
  ('Open Door', (SELECT id FROM public.zones WHERE name = 'Z. Lujan - Fátima' LIMIT 1), true),
  ('Benavidez', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Dique Luján', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Escobar', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Garin', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Ingeniero Maschwitz', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Manuel Alberti', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Maquinista Savio', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Matheu', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Zelaya', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('La Lonja', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Del Viso', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Villa Rosa', (SELECT id FROM public.zones WHERE name = 'Z. Norte Escobar' LIMIT 1), true),
  ('Adolfo Sourdeaux', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Bella Vista', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Cruce Castelar (Moreno)', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Cuartel V', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Don Torcuato', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Grand Bourg', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('José C. Paz', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Los Polvorines', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Malvinas Argentinas', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Muñiz', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Pablo Nogués', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('San Miguel', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Tortuguitas', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Trujui', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Villa de Mayo', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Derqui', (SELECT id FROM public.zones WHERE name = 'Z. Norte Jose C. Paz' LIMIT 1), true),
  ('Bancalari', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Beccar', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('El Talar', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('General Pacheco', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Los Troncos del Talar', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Ricardo Rojas', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Rincon de Milberg', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Rio Lujan (Tigre)', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('San Fernando', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Talar de Pacheco', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Tigre', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Victoria', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Virreyes', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Acassuso', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Martinez', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Olivos', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('San Isidro', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Florida', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Vicente López', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('La Lucila', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pacheco' LIMIT 1), true),
  ('Pilar', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pilar' LIMIT 1), true),
  ('Villa Astolfi', (SELECT id FROM public.zones WHERE name = 'Z. Norte Pilar' LIMIT 1), true),
  ('Billinghurst', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Boulogne', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Carapachay', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Caseros', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('El Libertador', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('El Palomar', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Florida Oeste', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Hurlingham', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('José Ingenieros', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Jose León Suarez', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Loma Hermosa', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Martin Coronado', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Munro', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Pablo Podesta', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Parque Leloir', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Remedios de Escalada de San Martin', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Saenz Peña', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('San Andres', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('San Martín', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Santos Lugares', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Udaondo', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Villa Adelina', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Villa Ballester', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Villa Bosch', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Villa Libertad', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Villa Lynch', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Villa Maipú', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Villa Martelli', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Villa Tesei', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('William C. Morris', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Churruca', (SELECT id FROM public.zones WHERE name = 'Z. Norte San Martín' LIMIT 1), true),
  ('Campana', (SELECT id FROM public.zones WHERE name = 'Z. Norte Zárate - Campana' LIMIT 1), true),
  ('Zárate', (SELECT id FROM public.zones WHERE name = 'Z. Norte Zárate - Campana' LIMIT 1), true),
  ('Avellaneda', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Bernal', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Bernal Oeste', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Don Bosco', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Gerli', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Quilmes', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Quilmes Oeste', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Sarandi', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Villa Domínico', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Wilde', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Berazategui', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Berazategui Oeste', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Bosques', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Ezpeleta', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Ezpeleta Oeste', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Florencio Varela', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Gdor Costa', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Guillermo Hudson', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Gutierrez', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Platanos', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Ranelagh', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('San Francisco Solano', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Sourigues', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Villa España', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Villa La Florida', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Villa Vatteone', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Zeballos', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Santa Rosa', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('Villa San Luis', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Avellaneda-Beraza.' LIMIT 1), true),
  ('9 de Abril (Nueve de Abril)', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Canning', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('El Jaguel', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Esteban Echeverria (El Jaguel)', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Ezeiza', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Luis Guillon', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Monte Grande', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Malvinas Argentinas (Zona Sur)', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Banfield', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Ingeniero Budge', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Lanús', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Lanús Este', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Lanús Oeste', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Llavallol', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Lomas de Zamora', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Monte Chingolo', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Remedios de Escalada', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('San José (Temperley)', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Temperley', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Valentín Alsina', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Villa Centenario', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Villa Fiorito', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Villa Turdera', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Adrogué', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Burzaco', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Claypole', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('José Marmol', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Don Orione', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Longchamps', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Rafael Calzada', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Ministro Rivadavia', (SELECT id FROM public.zones WHERE name = 'Z. Sur. Eze-Lanus-Burz' LIMIT 1), true),
  ('Gral. Rodríguez', (SELECT id FROM public.zones WHERE name = 'Zona Rodriguez' LIMIT 1), true)
ON CONFLICT (name, zone_id) DO NOTHING;
