const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),ts=require('typescript');
const {rows,grid}=require('./fixtures/mp-statement.cjs');
function load(file){const exports={};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,require:name=>name==='./model'?model:require(name),Intl,Date,Map,Set,BigInt,Number,Error,Array});return exports;}
const model=load('src/lib/bankStatements/model.ts');
const plain=value=>JSON.parse(JSON.stringify(value));
test('23 movements, 16 operations and exact cent totals',()=>{const parsed=model.parseStatementGrid('Sheet0',grid());assert.deepEqual(plain(model.statementTotals(parsed)),{rows:23,valid:23,operations:16,incoming:235230116,outgoing:249317017,net:-14086901,from:'2026-10-08',to:'2026-10-08'});const entries=parsed.map((row,i)=>({id:String(i),external_movement_id:row.movementId,related_operation_id:row.operationId,signed_amount:row.amount}));const groups=model.groupStatementEntries(entries);assert.equal(groups.find(g=>g.id==='5').net,4594509);assert.equal(groups.find(g=>g.id==='11').net,25817235);assert.equal(groups.find(g=>g.id==='1').entries.length,2);assert.equal(groups.find(g=>g.id==='7').net,0);});
test('decimal parsing preserves cents and refuses ambiguous locale formats',()=>{assert.equal(model.statementCents('-4556.55'),-455655);assert.equal(model.statementCents('0'),0);assert.equal(model.decimalAmount(80848),'808.48');for(const value of ['1.234,56','1,23','1e4','NaN','1.001','1000000000000','',null])assert.throws(()=>model.statementCents(value));});
test('text IDs keep leading zeros and large IDs; unsafe numeric IDs require review',()=>{const data=grid();data[1][2].value='00090071992547409931234';data[2][2].value=9007199254740992;const parsed=model.parseStatementGrid('Sheet0',data);assert.equal(parsed[0].movementId,'00090071992547409931234');assert.ok(parsed[1].errors.some(error=>error.includes('precisión')));});
test('headers can reorder; formulas, missing and duplicate headers are rejected',()=>{const reordered=grid().map(row=>[row[4],row[2],row[0],row[3],row[1]]);assert.equal(model.parseStatementGrid('Sheet0',reordered)[0].amount,'808.48');const duplicate=grid();duplicate[0].push({value:'Importe'});assert.throws(()=>model.parseStatementGrid('Sheet0',duplicate),/ambigua/);assert.throws(()=>model.parseStatementGrid('Sheet0',[[{value:'Otro'}]]),/necesita/);const formula=grid();formula[1][4].formula='SUM(A1)';assert.ok(model.parseStatementGrid('Sheet0',formula)[0].errors.some(error=>error.includes('fórmula')));});
test('midnight preserves source calendar date and original timestamp; invalid dates surface',()=>{const data=grid();data[1][0].value='2026-10-08T01:00:00Z';data[2][0].value='2026-02-30T12:00:00Z';const parsed=model.parseStatementGrid('Sheet0',data);assert.equal(parsed[0].date,'2026-10-08');assert.equal(parsed[0].occurredAt,'2026-10-08T01:00:00.000Z');assert.ok(parsed[1].errors.length);});
test('null operation references do not collapse separate movements',()=>{const parsed=model.parseStatementGrid('Sheet0',grid());const entries=parsed.slice(0,2).map((row,i)=>({id:String(i),external_movement_id:row.movementId,related_operation_id:null,signed_amount:row.amount}));assert.equal(model.groupStatementEntries(entries).length,2);});
test('specific suggestions only; generic payments never learn a beneficiary',()=>{const concepts=[{id:'cost',concept:'Costo de Mercado Pago',is_active:true},{id:'adt',concept:'ADT',is_active:true}];assert.equal(model.suggestStatementConcept({description:'Costo de Mercado Pago',signed_amount:'-1.00'},concepts,[],'account'),'cost');assert.equal(model.suggestStatementConcept({description:'Pago',signed_amount:'-1.00'},concepts,[],'account'),null);assert.equal(model.suggestStatementConcept({description:'Costo de Mercado Pago',signed_amount:'1.00'},concepts,[],'account'),null);assert.equal(model.suggestStatementConcept({description:'Costo de Mercado Pago',signed_amount:'-1.00'},[...concepts,{id:'duplicate',concept:'Costo de Mercado Pago',is_active:true}],[],'account'),null);});
test('rule account scope and sign; conflicting rules remain unclassified',()=>{const concepts=[{id:'a',concept:'Uno',is_active:true},{id:'b',concept:'Dos',is_active:true}],rule={description:'costo de mercado pago',direction:'egreso',financial_concept_id:'a',financial_account_id:null};const entry={description:'Costo de Mercado Pago',signed_amount:'-1.00'};assert.equal(model.suggestStatementConcept(entry,concepts,[rule,{...rule,financial_account_id:'mp3',financial_concept_id:'b'}],'mp3'),'b');assert.equal(model.suggestStatementConcept(entry,concepts,[rule,{...rule,financial_concept_id:'b'}],'mp3'),null);});
test('original supplied workbook reconciles to the regression controls when explicitly provided',()=>{const filename=process.env.BANK_STATEMENT_TEST_FILE;if(!filename)return;const workbook=load('src/lib/bankStatements/workbook.ts');const bytes=fs.readFileSync(filename);const parsed=workbook.readStatementWorkbook(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));assert.equal(parsed.length,23);assert.equal(model.statementTotals(parsed).net,-14086901);});

test('MP yields and received funds use the requested active categories, only for incoming amounts',()=>{
 const concepts=[{id:'yield',concept:'MP - Intereses Ganados',category:'Inversiones',is_active:true},{id:'collection',concept:'Cobro',category:'Recaudación',is_active:true},{id:'other',concept:'Cobro',category:'Otra categoría',is_active:true}];
 for(const [description,id] of [['Rendimiento positivo de la inversión','yield'],['Ingreso de dinero','collection'],['Dinero recibido','collection'],['Cobro','collection']]){
  assert.equal(model.suggestStatementConcept({description,signed_amount:'808.48'},concepts,[],'mp3'),id);
  assert.equal(model.suggestStatementConcept({description,signed_amount:'-808.48'},concepts,[],'mp3'),null);
  assert.equal(model.suggestStatementConcept({description,signed_amount:'0.00'},concepts,[],'mp3'),null);
  assert.equal(model.suggestStatementConcept({description,signed_amount:'1.00'},concepts.map(c=>({...c,is_active:false})),[],'mp3'),null);
 }
 assert.equal(model.suggestStatementConcept({description:'Rendimiento positivo de la inversión',signed_amount:'1.00'},concepts.filter(c=>c.id!=='yield'),[],'mp3'),null);
});
test('web gross yield has the same concept as official investment yield and keeps sign guard',()=>{const concepts=[{id:'interest',concept:'MP - Intereses Ganados',category:'Inversiones',is_active:true}];assert.equal(model.suggestStatementConcept({description:'Rendimiento bruto',signed_amount:'142.80'},concepts,[],'mp3'),'interest');assert.equal(model.suggestStatementConcept({description:'Rendimiento bruto',signed_amount:'-142.80'},concepts,[],'mp3'),null);});

test('identified reserve transfers suggest an internal movement on both signed components',()=>{const concepts=[{id:'reserve',concept:'Movimiento de cuentas',category:'Movimiento de cuentas',is_active:true}];for(const amount of ['120000.00','-120000.00'])assert.equal(model.suggestStatementConcept({description:'Movimiento de cuentas',signed_amount:amount},concepts,[],'mp3'),'reserve');assert.equal(model.suggestStatementConcept({description:'Movimiento desconocido',signed_amount:'120000.00'},concepts,[],'mp3'),null);});
