const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),ts=require('typescript');
class OperationError extends Error{constructor(message,status=400){super(message);this.status=status;}}
const validation={OperationError,isUuid:value=>typeof value==='string'&&/^[0-9a-f-]{36}$/i.test(value)};
function load(file,requireFn){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:requireFn,Set,Number,Error,Response});return exports;}
const helper=load('src/lib/bankStatements/initializeInboxes.ts',()=>validation);
const ids=[3,4,5].map(n=>'00000000-0000-4000-8000-00000000000'+n);
function fixture(fail){const calls=[];const mappings=ids.map((id,i)=>({financial_account_id:id,mp_account_id:'mp'+(i+3)}));return {calls,db:{from:()=>({select:()=>({in:async(_field,accounts)=>({data:mappings.filter(m=>accounts.includes(m.financial_account_id))})})}),rpc:async(name,args)=>{calls.push({name,args});return args.p_mp===fail?{error:{message:'Reintentar esta cuenta'}}:{data:{prepared:3}};}}};}
test('bulk setup initializes three separately mapped accounts using the authorized actor, without monetary RPCs',async()=>{const f=fixture();const result=await helper.initializeStatementInboxes(f.db,'admin',ids);assert.equal(result.results.filter(r=>r.ready).length,3);assert.deepEqual(f.calls.map(c=>c.args.p_mp),['mp3','mp4','mp5']);assert.ok(f.calls.every(c=>c.name==='sync_mp_bank_inbox'&&c.args.p_actor==='admin'));});
test('bulk validates every selected account before any initialization and rejects duplicates',async()=>{for(const accounts of [[],[ids[0],ids[0]],['wrong'],[ids[0],'00000000-0000-4000-8000-000000000099']]){const f=fixture();await assert.rejects(()=>helper.initializeStatementInboxes(f.db,'admin',accounts));assert.equal(f.calls.length,0);}});
test('a failed account is reported separately while other accounts can be retried safely',async()=>{const f=fixture('mp4');const result=await helper.initializeStatementInboxes(f.db,'admin',ids);assert.equal(result.results[0].ready,true);assert.equal(result.results[1].ready,false);assert.equal(result.results[1].error,'Reintentar esta cuenta');assert.equal(result.results[2].ready,true);});
test('bulk API requires finance permission before resolving or initializing accounts',async()=>{let effects=0;const route=load('src/app/api/admin/bank-statements/route.ts',name=>name==='next/server'?{NextResponse:{json:(body,init)=>new Response(JSON.stringify(body),init)}}:name.endsWith('/financialOperations/server')?{financialContext:async(_request,write)=>{assert.equal(write,true);throw new OperationError('Sin permiso',403);}}:name.endsWith('/financialOperations/validation')?validation:name.endsWith('/bankStatements/initializeInboxes')?{initializeStatementInboxes:()=>{effects++;}}:{});const r=await route.POST(new Request('http://localhost/api/admin/bank-statements',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'inbox-initialize',accounts:ids})}));assert.equal(r.status,403);assert.equal(effects,0);});
