const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
function load(file,imports=require){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:imports,Date,Intl,Set,Map,URL});return exports;}
const model=load('src/lib/costs/model.ts'),discounts=load('src/lib/erp/discounts.ts'),sales=load('src/lib/sellerCommissionBase.ts');
const daily=load('src/lib/costs/dailyMargin.ts',n=>n==='./model'?model:n.includes('discounts')?discounts:sales);
function database(){
  const orders=[{id:'OK',legacy_code:'1',total_amount:120,totals:{freight:20},status:'entregado',order_items:[{product_id:'P',product_name:'Producto',quantity:1,unit_price:100,subtotal:100,historical_unit_cost:40}],deliveries:{status:'entregado',real_delivery_date:'2026-10-05'}},{id:'MISSING',legacy_code:'2',status:'entregado',deliveries:{status:'entregado',real_delivery_date:null}}];
  const deliveries=[{id:1,order_id:'OK',status:'entregado',real_delivery_date:'2026-10-05'},{id:2,order_id:'OK',status:'entregado',real_delivery_date:null},{id:3,order_id:'MISSING',status:'entregado',real_delivery_date:null}];
  return {from(table){let data=[...(table==='orders'?orders:table==='products'?[]:deliveries)];const q={select(){return q;},ilike(){return q;},eq(k,v){data=data.filter(r=>r[k]===v);return q;},is(k,v){data=data.filter(r=>r[k]===v);return q;},not(k,op,v){assert.equal(op,'is');data=data.filter(r=>r[k]!==v);return q;},in(k,values){data=data.filter(r=>values.includes(r[k]));return q;},gte(k,v){data=data.filter(r=>r[k]!=null&&r[k]>=v);return q;},lte(k,v){data=data.filter(r=>r[k]!=null&&r[k]<=v);return q;},order(){return q;},range(a,b){data=data.slice(a,b+1);return q;},then(resolve){return Promise.resolve({data,error:null}).then(resolve);}};return q;}};
}
test('report loads when the database embeds a delivery as an object and preserves exclusion reasons',async()=>{
  const db=database();const route=load('src/app/api/admin/rentabilidad-diaria/route.ts',n=>n==='next/server'?{NextResponse:{json:(body,options)=>({status:options?.status||200,body})}}:n.includes('financeAdminAccess')?{requireFinanceAdmin:async()=>null}:n.endsWith('/server')?{costDatabase:()=>db,readCosts:async()=>({updatedAt:'2026-10-07',current:[{id:'P',name:'Producto',material:40,operations:10,operationDetail:{gas:10},warnings:[]}]})}:n.endsWith('/model')?model:daily);
  const response=await route.GET({url:'http://localhost/api/admin/rentabilidad-diaria?from=2026-10-01&to=2026-10-07'});
  assert.equal(response.status,200);assert.equal(response.body.orders.length,1);assert.equal(response.body.orders[0].margin,80);assert.equal(response.body.orders[0].operationsReference,10);assert.equal(response.body.exclusions.length,1);assert.equal(response.body.exclusions[0].code,'2');assert.match(response.body.exclusions[0].reason,/sin fecha real/);assert.equal(response.body.missingDate,1);
});
