const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
function load(file,imports=require){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:imports,Date,Intl,Set,Map});return exports;}
const m=load('src/lib/costs/model.ts'),discount=load('src/lib/erp/discounts.ts'),sales=load('src/lib/sellerCommissionBase.ts');
const daily=load('src/lib/costs/dailyMargin.ts',n=>n==='./model'?m:n.includes('discounts')?discount:n.includes('sellerCommissionBase')?sales:require(n));
const current=[{id:'P',code:'P',name:'Producto',material:25,operations:15,operationDetail:{gas:5,labor:10},total:40,coverage:'Completo',warnings:[]}];
function order(){return {id:'O',legacy_code:'123',total_amount:200,totals:{items_subtotal:200,subtotal:180,freight:20},order_items:[{product_id:'P',product_name:'Producto',quantity:2,unit_price:100,subtotal:200,historical_unit_cost:30}]};}
test('only successful actual dates count; duplicate attempts are not duplicate orders',()=>{const dates=daily.deliveryDates([{order_id:'O',status:'entregado',real_delivery_date:null},{order_id:'O',status:'fallido',real_delivery_date:'2026-10-01'},{order_id:'O',status:'entregado',real_delivery_date:'2026-10-02'},{order_id:'O',status:'entregado',real_delivery_date:'2026-10-02'}]);assert.equal(dates.get('O').size,1);assert.equal([...dates.get('O')][0],'2026-10-02');});
test('fabrication expenses stay reference-only; freight increases profit and discounts apply once',()=>{const result=daily.orderMargin(order(),'2026-10-02',current,'historical');assert.equal(result.sales,180);assert.equal(result.cost,50);assert.equal(result.margin,150);assert.equal(result.operationsReference,30);assert.equal(result.lines[0].historicalCostReference,30);assert.equal(result.freightCharged,20);assert.equal(result.status,'Estimación parcial');});
test('replacement does not rewrite the saved cost',()=>{const o=order(),r=daily.orderMargin(o,'2026-10-02',current,'replacement');assert.equal(r.cost,50);assert.equal(o.order_items[0].historical_unit_cost,30);});
test('negative discount items reduce sales and always cost zero',()=>{const o=order();o.totals=null;o.order_items.push({product_id:'D',product_name:'Descuento Combo',quantity:1,unit_price:-20,subtotal:-20,historical_unit_cost:100});const r=daily.orderMargin(o,'2026-10-02',current,'historical');assert.equal(r.sales,180);assert.equal(r.cost,50);});
test('missing cost never becomes zero or a claimed daily profit',()=>{const o=order();o.order_items[0].historical_unit_cost=0;const r=daily.orderMargin(o,'2026-10-02',[],'historical');assert.equal(r.cost,null);assert.equal(r.margin,null);const d=daily.dailyTotals([r])[0];assert.equal(d.missing,1);assert.equal(d.calculableSales,0);assert.equal(d.sales,180);});
test('conflicting successful dates remain distinct for review',()=>{const d=daily.deliveryDates([{order_id:'O',status:'entregado',real_delivery_date:'2026-10-01'},{order_id:'O',status:'entregado',real_delivery_date:'2026-10-02'}]);assert.equal(d.get('O').size,2);});
test('an order without items has unknown cost',()=>{const o=order();o.order_items=[];const r=daily.orderMargin(o,'2026-10-02',current,'replacement');assert.equal(r.cost,null);assert.equal(r.margin,null);});
test('daily profit includes freight without deducting reference expenses',()=>{const r=daily.orderMargin(order(),'2026-10-02',current,'replacement'),d=daily.dailyTotals([r])[0];assert.equal(d.margin,150);assert.equal(d.freightCharged,20);assert.equal(d.operationsReference,30);});
test('recorded surcharges increase order and daily profit once, separate from discounted sales and freight',()=>{const o=order();o.totals.payment_surcharges=35;o.total_amount=235;const r=daily.orderMargin(o,'2026-10-02',current,'replacement');assert.equal(r.sales,180);assert.equal(r.freightCharged,20);assert.equal(r.surchargesCharged,35);assert.equal(r.margin,185);const d=daily.dailyTotals([r])[0];assert.equal(d.surchargesCharged,35);assert.equal(d.margin,185);assert.equal(r.cost,50);});
test('CAMB surcharges remain inherited reference and never become new income',()=>{const o=order();o.legacy_code='CAMB1509';o.totals.payment_surcharges=35;const r=daily.orderMargin(o,'2026-10-02',current,'replacement');assert.equal(r.recordedSurcharges,35);assert.equal(r.surchargesCharged,0);assert.equal(r.margin,null);assert.equal(daily.dailyTotals([r])[0].surchargesCharged,0);});
test('a saved total without a split cannot hide fabrication expenses in deductible cost',()=>{const r=daily.orderMargin(order(),'2026-10-02',[],'historical');assert.equal(r.margin,null);assert.ok(r.reasons[0].includes('falta un costo'));assert.equal(r.lines[0].historicalCostReference,30);});
test('items without an id match only their name, never unrelated unlinked products',()=>{const o=order();o.order_items[0].product_id=null;const r=daily.orderMargin(o,'2026-10-02',[...current,{id:null,name:'Otro',material:900}], 'replacement');assert.equal(r.cost,50);});
test('ENC identifies encomiendas without excluding ordinary seller codes',()=>{for(const code of ['ENC604',' enc607 ','ENC'])assert.equal(daily.isEncomiendaCode(code),true);for(const code of ['JS25939 / JS25940','LK01719','ENCANTO'])assert.equal(daily.isEncomiendaCode(code),false);});
test('installation service is deducted once alongside the physical materials, fabrication stays reference-only',()=>{const o=order();o.order_items.push({product_id:'INSTALL',product_name:'Kit Instalación',quantity:1,unit_price:1000,subtotal:1000,historical_unit_cost:null});o.totals={freight:20};const r=daily.orderMargin(o,'2026-10-02',current,'replacement',[{id:'INSTALL',name:'Kit Instalación',unitCost:900}]);assert.equal(r.cost,950);assert.equal(r.margin,270);assert.equal(r.operationsReference,30);assert.equal(r.lines[1].cost,900);});
test('CAMB never counts inherited payment as new income or assumes the replacement is a full loss',()=>{const o=order();o.legacy_code='CAMB1509';const r=daily.orderMargin(o,'2026-10-02',current,'replacement');assert.equal(r.sales,0);assert.equal(r.freightCharged,0);assert.equal(r.recordedSales,180);assert.equal(r.recordedFreight,20);assert.equal(r.cost,50);assert.equal(r.margin,null);assert.match(r.reasons[0],/pedido anterior/);const d=daily.dailyTotals([r])[0];assert.equal(d.sales,0);assert.equal(d.cost,0);assert.equal(d.margin,0);assert.equal(d.missing,1);assert.equal(o.total_amount,200);});

test('purchase alerts resolve the same material cost as daily deliveries, including equivalent ids',()=>{const products=[{...current[0],equivalentIds:['ERP']}];const product=m.resolveDailyCostProduct(products,'ERP','Otra descripción');const o=order();o.order_items[0].product_id='ERP';assert.equal(product.material,daily.orderMargin(o,'2026-10-09',products,'replacement').lines[0].unitCost);assert.equal(product.material,25);assert.notEqual(product.material,product.total);assert.equal(m.resolveDailyCostProduct([], 'ERP','Producto'),undefined);assert.equal(m.resolveDailyCostProduct([{...current[0],id:'A'},{...current[0],id:'B'}],null,'Producto'),undefined);});
