const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>{if(n in imports)return imports[n];throw new Error('Unknown import '+n);},Date,Map,Set,Number,String,Math,Object,Array,Promise,console,process:{env:{}}});return exports;}
const changes=load('src/lib/importChanges.ts'),orderSync=load('src/lib/orderSync.ts'),lookup=load('src/lib/importOrderLookup.ts',{'./orderSync':orderSync}),wholesale=load('src/lib/wholesaleOrders.ts');
function fixture(){
 const row=Array(38).fill('');Object.assign(row,{0:'Pendiente',1:'AQU123',2:'8/10/2026',3:'1/10/2026',4:'8/10/2026',5:'Cliente',11:'WhatsApp',21:'Tarjeta',25:'10',28:'75',29:'85',30:'Tanque',31:'1',32:'100',34:'Descuento Mayorista',35:'1',36:'-25'});
 const order={id:'O',legacy_code:'AQU123',status:'Pendiente',client_id:'C',channel:'mayorista',order_medium_id:'WP',payment_method_id:'PM',total_amount:'85.00',order_discount_type:'fixed',order_discount_value:'25.00',order_discount_amount:'25.00',totals:{subtotal:100,freight:0,payment_surcharges:10,deposit_amount:0,pending_balance:85,order_discount_type:'fixed',order_discount_value:25,order_discount_amount:25,existing_metadata:'preserved'}};
 const tables={orders:[order],products:[{id:'P',name:'Tanque',sku:'T'}],order_items:[{id:'I',order_id:'O',product_name:'Tanque',quantity:1,unit_price:'100.00',product_id:'P'}],order_mediums:[{id:'WP',name:'WhatsApp'}],payment_methods:[{id:'PM',name:'Tarjeta',surcharge_percentage:10}]};
 const writes=[];let fail=false;
 const db={from(table){let data=[...(tables[table]||[])],patch,operation='read',columns;const q={select(value){columns=value;return q;},limit(){return q;},in(k,values){data=data.filter(r=>values.includes(r[k]));return q;},or(){return q;},eq(k,v){data=data.filter(r=>r[k]===v);return q;},is(){return q;},neq(){return q;},update(value){patch=value;operation='update';return q;},delete(){throw new Error('Unexpected item deletion');},insert(){throw new Error('Unexpected insert');},then(resolve){if(operation==='update'){if(fail)return Promise.resolve({error:{message:'write failed'}}).then(resolve);for(const item of data){writes.push({table,patch:structuredClone(patch)});Object.assign(item,structuredClone(patch));}return Promise.resolve({error:null}).then(resolve);}const projected=data.map(r=>columns?Object.fromEntries(columns.split(',').map(k=>k.trim()).filter(k=>k in r).map(k=>[k,structuredClone(r[k])])):structuredClone(r));return Promise.resolve({data:projected,error:null}).then(resolve);}};return q;}};
 const route=load('src/app/api/admin/import-sheet/route.ts',{'next/server':{NextResponse:{json:(body,opts)=>({body,status:opts?.status||200})}},'@supabase/supabase-js':{createClient:()=>db},'@/lib/orderCategory':{hasBiodigestor:()=>false},'@/lib/googleSheets':{normalizePaymentMethodForSheet:v=>v,createLogisticsCancellationReasonLookup:()=>async()=>null},'@/lib/orderSync':orderSync,'@/lib/importOrderLookup':lookup,'@/lib/importChanges':changes,'@/lib/deliveryAttemptSync':{centralDeliveryOutcome:()=>null},'@/lib/wholesaleOrders':wholesale,'@/lib/importStatus':{isJazminCentralCancellation:()=>false}});
 const run=()=>route.POST({json:async()=>({sheetName:'Central',rows:[row],syncPaymentMethods:true,skipCAMB:true,defaultChannel:'mayorista'})});
 return {order,row,writes,run,failWrites(){fail=true;}};
}
test('repeated import with surcharge and wholesale discount writes nothing when values match',async()=>{const f=fixture();for(let i=0;i<2;i++){const r=await f.run();assert.equal(r.status,200,JSON.stringify(r.body));assert.equal(r.body.totalUpdated,0);assert.equal(r.body.updatedOrders.length,0);}assert.equal(f.writes.length,0);});
test('real payment, discount and contact changes count one order, then next import writes nothing',async()=>{const f=fixture();f.order.total_amount='80.00';f.order.order_discount_amount='20.00';f.order.order_medium_id='OLD';const first=await f.run();assert.equal(first.status,200,JSON.stringify(first.body));assert.equal(first.body.totalUpdated,1);assert.equal(first.body.updatedOrders[0].code,'AQU123');assert.match(first.body.updatedOrders[0].changes.join(';'),/importe total: \$80 → \$85/);assert.match(first.body.updatedOrders[0].changes.join(';'),/medio de contacto/);assert.equal(f.order.totals.existing_metadata,'preserved');const writes=f.writes.length;assert.ok(writes>1);const second=await f.run();assert.equal(second.body.totalUpdated,0);assert.equal(f.writes.length,writes);});
test('failed payment write is not counted as an updated order',async()=>{const f=fixture();f.order.total_amount='80.00';f.failWrites();const r=await f.run();assert.equal(r.body.totalUpdated,0);assert.match(r.body.warnings.join(';'),/write failed/);});
test('numeric storage and object key order do not cause false differences',()=>{assert.equal(changes.importValuesEqual({subtotal:'100.00',freight:0},{freight:0,subtotal:100}),true);assert.equal(Object.keys(changes.changedImportFields({total_amount:'85.00'},{total_amount:85})).length,0);assert.equal(changes.importValuesEqual(null,0),false);assert.equal(changes.importValuesEqual(85,85.01),false);});
