const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>{if(n in imports)return imports[n];throw new Error(n);},structuredClone,Date,Map,Set,Math,Number,String,Array,Object,Promise,console:{log(){},error(){}},process:{env:{}}});return exports;}
const cache=load('src/lib/runReadCache.ts'),sync=load('src/lib/orderSync.ts'),review=load('src/lib/logisticsReview.ts');
test('one run shares source reads but planning cannot mutate the cached snapshot',async()=>{const c=cache.createRunReadCache();let calls=0;const loader=async()=>{calls++;return {rows:['original']};};const a=await c.read('run-a',loader);a.value.rows[0]='modified';const b=await c.read('run-a',loader);assert.equal(b.value.rows[0],'original');assert.equal(b.reused,true);assert.equal(calls,1);await c.read('run-b',loader);assert.equal(calls,2);c.release('run-a');await c.read('run-a',loader);assert.equal(calls,3);});
test('failed reads retry and cache misses safely load fresh sources',async()=>{const c=cache.createRunReadCache();let calls=0;const loader=async()=>{if(++calls===1)throw new Error('offline');return 1;};await assert.rejects(c.read('run',loader),/offline/);assert.equal((await c.read('run',loader)).value,1);assert.equal(calls,2);const replacement=cache.createRunReadCache();assert.equal((await replacement.read('run',loader)).reused,false);});
test('logistics reuses full reads while comparing each batch against current database values',async()=>{
 const orders=[{id:'A',legacy_code:'AQ-FP00030',status:'Entregado',total_amount:0},{id:'B',legacy_code:'AQ-FP00031',status:'Entregado',total_amount:0}];
 const counts={sheet:0,cancelled:0,fullOrders:0,batchOrders:0};const writes=[];
 const db={from(table){let rows=table==='orders'?orders:table==='deliveries'?orders.map(o=>({order_id:o.id,real_delivery_date:'2026-10-08'})):[],patch;const q={maybeSingle(){return q;},upsert(value){writes.push({table,patch:value});return q;},select(){return q;},not(){return q;},range(a,b){if(table==='orders')counts.fullOrders++;rows=rows.slice(a,b+1);return q;},in(k,ids){if(table==='orders')counts.batchOrders++;rows=rows.filter(r=>ids.includes(r[k]));return q;},eq(k,v){if(k!=='status')rows=rows.filter(r=>r[k]===v);return q;},is(){return q;},update(value){patch=value;return q;},then(resolve){if(patch){writes.push({table,patch});for(const row of rows)Object.assign(row,patch);}return Promise.resolve({data:structuredClone(rows),error:null}).then(resolve);}};return q;}};
 const csv=['header',...orders.map(o=>{const r=Array(30).fill('');r[0]=o.legacy_code;r[1]='8/10/2026';r[15]='🟢 Entregado';r[27]='0';return r.map(JSON.stringify).join(',');})].join('\n');
 const route=load('src/app/api/admin/audit-deliveries/route.ts',{'next/server':{NextResponse:{json:body=>body}},'@supabase/supabase-js':{createClient:()=>db},'@/lib/googleSheets':{fetchSpreadsheetCsv:async()=>{counts.sheet++;return csv;},fetchSpreadsheetValues:async()=>{counts.cancelled++;return [];}},'@/lib/cancelledOrderSheet':{logisticsCancellationReasons:()=>new Map(),logisticsCancellationReason:()=>''},'@/lib/orderSync':sync,'@/lib/logisticsBatchItems':{loadLogisticsBatchItems:async()=>[]},'@/lib/runReadCache':cache,'@/lib/logisticsReview':review});
 const run=(cursor,dryRun=false)=>route.POST({json:async()=>({cursor,batchSize:1,syncRunId:'run-a',dryRun})});
 const first=await run(0);assert.equal(first.success,true,JSON.stringify(first));assert.equal(first.syncedOrdersCount,0);orders[1].total_amount=10;
 const second=await run(1);assert.equal(second.success,true,JSON.stringify(second));assert.equal(second.metrics.reusedSources,true);assert.equal(second.syncedOrdersCount,1);assert.equal(orders[1].total_amount,0);assert.deepEqual(counts,{sheet:1,cancelled:1,fullOrders:1,batchOrders:2});assert.equal(writes.filter(w=>w.table!=='site_settings').length,1);orders[0].total_amount=10;const dry=await run(0,true);assert.equal(dry.dryRun,true);assert.equal(dry.plannedUpdatesCount,1);assert.equal(writes.filter(w=>w.table!=='site_settings').length,1);assert.equal(orders[0].total_amount,10);assert.equal(counts.sheet,2);
});
