const {test}=require('node:test'),assert=require('assert/strict'),fs=require('fs'),vm=require('vm');
function fixture(count=450){const sent=[],toasts=[];let page=0;const row=i=>({operationId:String(183000000000+i),occurredAt:'2026-10-10T10:00:00-03:00',amount:'1.00',description:'Pago',occurrence:1});const rows=Array.from({length:count},(_,i)=>row(i));
 const dateEl={innerText:'10/10/2026',closest:()=>null,getClientRects:()=>[1]};const button={innerText:'Siguiente',closest:()=>null,getClientRects:()=>[1],getAttribute:()=>null,click(){page++;dateEl.innerText=page===1?'01/10/2026':'30/09/2026';}};
 const ctx={config:{webhookUrl:'https://zono-erp.pages.dev/api/mp-webhook',accountName:'diegozono.mp',secretToken:'test'},isMonitorTab:true,location:{pathname:'/banking/movements',href:'https://www.mercadopago.com.ar/banking/movements',reload(){}},ZonoMpBanking:{scan:()=>count===2?(page===0?[row(1)]:page===1?[{...row(2),occurredAt:'2026-10-01T10:00:00-03:00'}]:[]):rows,scanActivities:()=>rows},chrome:{runtime:{lastError:null,sendMessage(message,callback){sent.push(message);callback({ok:true,data:{success:true,captured:message.payload.rows?.length}});}}},getBankingInterval:()=>1800,updateReadingStatus(){},getRowDate:()=>({dateStr:'2026-10-10'}),detectMercadoPagoError:()=>({hasError:false}),document:{querySelectorAll:selector=>selector.startsWith('tr,')?[dateEl]:selector.startsWith('button')?[button]:[],documentElement:{scrollHeight:100}},window:{scrollTo(){}},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},lastActivityCaptureError:'',lastBankCaptureError:'',lastReadingCount:0,reportBankingRows(){},reportActivityBankRows(){},showToast:m=>toasts.push(m),Date,Map,Set,JSON,URL,console,setTimeout:(fn,ms)=>setTimeout(fn,ms===4000?100000:ms>=1000?1:ms),clearTimeout,setInterval(){}};
 // Suppress the module's startup timer; direct calls are exercised below.
 ctx.setTimeout=(fn,ms)=>ms===4000?0:setTimeout(fn,ms>=1000?1:ms);vm.createContext(ctx);vm.runInContext(fs.readFileSync('chrome-extension-mp/capture-refresh.js','utf8'),ctx);return {ctx,sent,toasts};}
test('all loaded rows are sent in bounded capture batches without collections notifications',async()=>{const f=fixture(),result=await f.ctx.ZonoCaptureRefresh.captureLoaded('banking',true);assert.equal(result.captured,450);assert.deepEqual(f.sent.map(x=>x.payload.rows.length),[100,100,100,100,50]);assert.ok(f.sent.every(x=>new URL(x.url).pathname==='/api/mp-bank-web'));});
test('unselected monitor cannot run reference capture',async()=>{const f=fixture();f.ctx.isMonitorTab=false;assert.equal((await f.ctx.ZonoCaptureRefresh.captureLoaded('banking',true)).failed,true);assert.equal(f.sent.length,0);});
test('history loads consecutive pages and only confirms coverage after reaching a prior date',async()=>{const f=fixture(2),result=await f.ctx.ZonoCaptureRefresh.readHistory('banking',{date_from:'2026-10-01',date_to:'2026-10-31'});assert.equal(result.count,2);assert.ok(result.message.includes('Se alcanzó el inicio'));assert.ok(f.sent.every(x=>x.payload.type==='BANK_WEB_CAPTURE'));});

test('an empty loading list does not postpone the next capture for two hours',async()=>{const f=fixture(0);assert.equal((await f.ctx.ZonoCaptureRefresh.captureLoaded('banking')).captured,0);f.ctx.ZonoMpBanking.scan=()=>[{operationId:'183123456789',occurredAt:'2026-10-10T10:00:00-03:00',amount:'1.00',description:'Pago',occurrence:1}];assert.equal((await f.ctx.ZonoCaptureRefresh.captureLoaded('banking')).captured,1);assert.equal(f.sent.length,1);});

test('manual banking capture displays progress and confirmation including repeats',async()=>{const f=fixture(3);await f.ctx.reportBankingRows(true);await f.ctx.reportBankingRows(true);assert.equal(f.sent.length,2);assert.equal(f.toasts.filter(m=>m.includes('3 movimientos bancarios confirmados')).length,2);assert.ok(f.toasts[0].includes('Leyendo'));});
test('manual zero-row and failed banking captures explain what happened',async()=>{const empty=fixture(0);await empty.ctx.reportBankingRows(true);assert.ok(empty.toasts.at(-1).includes('No se detectaron filas'));const fail=fixture(3);fail.ctx.chrome.runtime.sendMessage=(m,cb)=>cb({ok:false,data:{error:'Sin conexión al ERP'}});const result=await fail.ctx.reportBankingRows(true);assert.equal(result.failed,true);assert.equal(fail.toasts.at(-1),'Sin conexión al ERP');});
test('manual activity references report independently from collection counts; automatic scans stay quiet',async()=>{const f=fixture(3);f.ctx.location.pathname='/activities';await f.ctx.reportActivityBankRows(true);assert.ok(f.toasts.at(-1).includes('3 referencias de Actividad confirmados'));const quiet=fixture(3);await quiet.ctx.reportBankingRows(false);assert.equal(quiet.toasts.length,0);});

test('banking pagination retains the capture channel and sends page URL',async()=>{const f=fixture(3);f.ctx.location.pathname='/banking/movements/2';f.ctx.location.href='https://www.mercadopago.com.ar/banking/movements/2?beginDate=2026-09-30';const result=await f.ctx.reportBankingRows(true);assert.equal(result.captured,3);assert.equal(f.sent[0].payload.url,f.ctx.location.href);f.ctx.location.pathname='/banking/movements/detail';assert.equal((await f.ctx.reportBankingRows(true)).failed,true);});
