const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>imports[n]||require(n),Date,Intl,Map,console,AbortSignal,...globals});return exports;}
const dates=load('src/lib/mpPaymentDate.ts'),income=load('src/lib/mpAccountIncome.ts',{'./mpPaymentDate':dates});
const account=(id,amount)=>({id,name:id,monthAmount:amount,dailyAverage:amount/8,periodAmount:0,date40:'2026-10-20',date50:'2026-10-25',monthEnd:'2026-10-31',asOf:'2026-10-08'});
test('Telegram warns strongly at 40M and repeats neither account nor milestone',async()=>{
 let accounts=[account('A',30000000),account('B',10000000)],reject=false;const records=new Map(),messages=[];
 const db={from(){let identity,values,isInsert=false,claiming=false;const q={insert(value){identity=value;isInsert=true;return q},update(value){values=value;return q},match(value){identity=value;return q},eq(){return q},lt(){claiming=true;return q},select(){return q},then(resolve){const key=[identity.month,identity.account_id,identity.threshold].join(':');if(isInsert){if(records.has(key))return resolve({error:{code:'23505'}});records.set(key,{...identity});return resolve({error:null});}const row=records.get(key);if(values?.status==='sent'){Object.assign(row,values);return resolve({error:null});}if(claiming&&(row.status==='sent'||Date.parse(row.lease_until)>=Date.now()))return resolve({data:[],error:null});Object.assign(row,values);return resolve({data:[row],error:null});}};return q;}};
 const alerts=load('src/lib/mpMonthlyIncomeAlerts.ts',{'@supabase/supabase-js':{createClient:()=>db},'./mpAccountIncome':income,'./mpAccountIncomeServer':{loadMonthlyAccountIncome:async()=>accounts}},{process:{env:{LOGISTICS_TELEGRAM_BOT_TOKEN:'test',META_BALANCE_TELEGRAM_CHAT_ID:'test',NEXT_PUBLIC_SUPABASE_URL:'test',SUPABASE_SERVICE_ROLE_KEY:'test'}},fetch:async(url,options)=>{messages.push(JSON.parse(options.body));return {ok:!reject,status:reject?500:200,json:async()=>({ok:!reject,description:'delivery rejected'})};}});
 assert.equal((await alerts.checkMonthlyIncomeAlerts()).sent,4);assert.equal((await alerts.checkMonthlyIncomeAlerts()).sent,0);accounts=[account('A',40000000),account('B',10000000)];assert.equal((await alerts.checkMonthlyIncomeAlerts()).sent,1);assert.match(messages.at(-1).text,/🚨 ATENCIÓN/);assert.equal(messages.at(-1).chat_id,'test');
 accounts=[account('C',10000000)];reject=true;await assert.rejects(alerts.checkMonthlyIncomeAlerts(),/Telegram rechazó/);assert.equal([...records.values()].filter(r=>r.account_id==='C'&&r.status==='sent').length,0);reject=false;await new Promise(resolve=>setTimeout(resolve,2));assert.equal((await alerts.checkMonthlyIncomeAlerts()).sent,1);
});
