const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>imports[n]||require(n),Date,Intl,Map,console});return exports;}
const dates=load('src/lib/mpPaymentDate.ts'),income=load('src/lib/mpAccountIncome.ts',{'./mpPaymentDate':dates});
const account={id:'A',name:'Cuenta A'},row=(amount,id='A')=>({account_id:id,amount,received_at:'2026-10-08T12:00:00Z'});
test('per-account average includes zero-income calendar days and month reset',()=>{const totals=income.summarizeAccountIncome([row(500)],[row(16000000),row(8000000,'B')],[account,{id:'B',name:'B'}],'2026-10-08');assert.equal(totals[0].periodAmount,500);assert.equal(totals[0].dailyAverage,2000000);assert.equal(totals[0].date40,'2026-10-20');assert.equal(totals[0].date50,'2026-10-25');assert.equal(totals[1].monthAmount,8000000);const next=income.summarizeAccountIncome([],[],[account],'2026-11-01')[0];assert.equal(next.monthAmount,0);assert.equal(next.date40,null);});
test('monthly window uses Argentina, crosses years and leap February',()=>{assert.equal(income.monthWindow('2026-12-31').endExclusiveIso,'2027-01-01T03:00:00.000Z');assert.equal(income.monthWindow('2028-02-10').monthEnd,'2028-02-29');assert.throws(()=>income.monthWindow('2026-02-30'));});
test('thresholds are per account, include skipped milestones and stop at 40M',()=>{assert.equal(income.crossedIncomeThresholds(9999999).length,0);assert.equal(income.crossedIncomeThresholds(30000000).join(','),'10000000,20000000,30000000');assert.equal(income.crossedIncomeThresholds(70000000).length,4);});
test('aliases consolidate into the registered account without changing cents',()=>{const totals=income.summarizeAccountIncome([],[{...row('12.34',null),account_name:'ALIAS'}],[{...account,alias:'Alias'}],'2026-10-01');assert.equal(totals.length,1);assert.equal(totals[0].monthAmount,12.34);});
const types=load('src/lib/financialOperations/types.ts'),validation=load('src/lib/financialOperations/validation.ts',{'./types':types});const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
test('client credit accepts no order and rejects missing or malformed client',()=>{const p={operation_type:'customer_collection',effective_date:'2026-10-08',account_id:id(1),payment_method_id:id(2),client_id:id(3),amount:'44',direction:'ingreso',concept:'Saldo a favor',category:'Cobranza',detail:{}};validation.validateOperation(p);assert.throws(()=>validation.validateOperation({...p,client_id:undefined}));assert.throws(()=>validation.validateOperation({...p,client_id:'bad'}));assert.throws(()=>validation.validateOperation({...p,client_payment_id:id(4)}));});
const variants=load('src/lib/catalogVariantPrices.ts');
test('catalog keeps each venda price while retaining blind tank and missing-price inheritance',()=>{const rows=variants.inheritVariantPrices([{id:'parent',price:3800},{id:'25m',parent_id:'parent',price:8990},{id:'50m',parent_id:'parent',price:17500},{id:'blind',parent_id:'parent',variant_type:'ciego',price:1},{id:'empty',parent_id:'parent',price:0}]);assert.equal(rows[1].price,8990);assert.equal(rows[2].price,17500);assert.equal(rows[3].price,3800);assert.equal(rows[4].price,3800);});
