const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
function compile(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Date,require:n=>imports[n]||require(n)});return exports;}
const types=compile('src/lib/financialOperations/types.ts'),validation=compile('src/lib/financialOperations/validation.ts',{'./types':types});
const {buildSpecialPlan}=compile('src/lib/financialOperations/specialized.ts',{'./validation':validation});
const ids=[1,2,3,4].map(n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`);
const resources=()=>({accounts:ids.slice(0,3).map((id,i)=>({id,name:String(i),currency:i===2?'USD':'ARS',is_active:true})),funds:[],loans:[],counts:[]});
const base={effective_date:'2026-10-01',account_id:ids[0],payment_method_id:ids[3],amount:'100',concept:'Operación de prueba',counterparty:'Contraparte',reference:'DOC-1'};
const cents=l=>Math.round(Number(l.amount)*100)*(l.direction==='ingreso'?1:-1);
test('twelve business families plus a separate general exception are exposed',()=>{assert.equal(Object.keys(types.operationLabels).length,13);});
test('custody money cannot be spent by an unrelated business operation',()=>{const r=resources();r.funds=[{id:ids[3],account_id:ids[0],status:'open'}];assert.throws(()=>buildSpecialPlan({...base,operation_type:'partner_equity',action:'withdrawal'},r),/bajo custodia/);});
test('exchange preserves independent currency amounts and separate commission',()=>{const plan=buildSpecialPlan({...base,operation_type:'currency_exchange',action:'exchange',destination_account_id:ids[2],destination_amount:'1',fee:'2.50',fee_account_id:ids[0]},resources());assert.deepEqual(Array.from(plan.lines,l=>[l.direction,l.amount,l.account_id]),[['egreso','100.00',ids[0]],['ingreso','1.00',ids[2]],['egreso','2.50',ids[0]]]);assert.throws(()=>buildSpecialPlan({...base,operation_type:'currency_exchange',action:'exchange',destination_account_id:ids[1],destination_amount:'1'},resources()),/dos monedas/);});
test('fund 30000 delivered, 24000 spent, 6000 returned leaves no custody money and 24000 actual outflow',()=>{const r=resources();const give=buildSpecialPlan({...base,operation_type:'custody_fund',action:'deliver',amount:'30000',destination_account_id:ids[1],purpose:'Gastos'},r);r.funds=[{id:ids[3],custodian:'Persona',purpose:'Gastos',account_id:ids[1],currency:'ARS',balance:'30000',pending:'0',version:1,status:'open'}];const spend=buildSpecialPlan({...base,operation_type:'custody_fund',action:'expense',amount:'24000',resource_id:ids[3],voucher_ids:[ids[3]]},r);r.funds[0].balance='6000';r.funds[0].version++;const ret=buildSpecialPlan({...base,operation_type:'custody_fund',action:'return',amount:'6000',resource_id:ids[3]},r);const lines=[...give.lines,...spend.lines,...ret.lines];assert.equal(lines.filter(l=>l.account_id===ids[0]).reduce((s,l)=>s+cents(l),0),-2400000);assert.equal(lines.filter(l=>l.account_id===ids[1]).reduce((s,l)=>s+cents(l),0),0);r.funds[0].balance='0';assert.equal(buildSpecialPlan({...base,operation_type:'custody_fund',action:'close',resource_id:ids[3]},r).lines.length,0);});
test('overspending is a reimbursement obligation, never a fictitious return',()=>{const r=resources();r.funds=[{id:ids[3],account_id:ids[1],currency:'ARS',balance:'100',pending:'0',version:1,status:'open'}];const input={...base,operation_type:'custody_fund',action:'expense',amount:'120',resource_id:ids[3],voucher_ids:[ids[3]]};assert.throws(()=>buildSpecialPlan(input,r),/pagado por la persona/);const p=buildSpecialPlan({...input,personal_paid:true},r);assert.equal(p.fund.pending_delta,'20.00');assert.equal(p.lines.length,1);assert.equal(p.lines[0].direction,'egreso');assert.equal(p.lines[0].amount,'100.00');r.funds[0].balance='0';r.funds[0].pending='20';assert.throws(()=>buildSpecialPlan({...base,operation_type:'custody_fund',action:'close',resource_id:ids[3]},r),/cero/);const reimburse=buildSpecialPlan({...base,operation_type:'custody_fund',action:'reimburse',resource_id:ids[3],amount:'20'},r);assert.equal(reimburse.fund.pending_delta,'-20.00');assert.equal(reimburse.lines[0].account_id,ids[0]);});
test('financing separates capital and interest and rejects repayments beyond principal',()=>{const r=resources();r.loans=[{id:ids[3],counterparty:'Banco',reference:'X',currency:'ARS',side:'borrower',capital:'600',version:2}];const p=buildSpecialPlan({...base,operation_type:'financing',action:'repay',resource_id:ids[3],amount:'400',fee:'25'},r);assert.equal(p.loan.capital_delta,'-400.00');assert.deepEqual(Array.from(p.lines,l=>l.amount),['400.00','25.00']);assert.throws(()=>buildSpecialPlan({...base,operation_type:'financing',action:'repay',resource_id:ids[3],amount:'601'},r),/supera/);});
test('partner contribution and withdrawal have opposite directions; existing purchase is not repaid as asset',()=>{assert.equal(buildSpecialPlan({...base,operation_type:'partner_equity',action:'contribution'},resources()).lines[0].direction,'ingreso');assert.equal(buildSpecialPlan({...base,operation_type:'partner_equity',action:'withdrawal'},resources()).lines[0].direction,'egreso');assert.throws(()=>buildSpecialPlan({...base,operation_type:'asset_trade',action:'purchase',asset_name:'Camioneta'},resources()),/Pago a proveedor/);});
test('count records no money, adjustment requires unchanged cut and explicit reason, opening rejects history',()=>{const r=resources(),cut={balance:'100',fingerprint:'version1',has_history:true},cutoff=new Date(Date.now()-60000).toISOString();const p=buildSpecialPlan({...base,operation_type:'cash_count',action:'record',cutoff,counted:'90'},r,cut);assert.equal(p.lines.length,0);r.counts=[{id:ids[3],account_id:ids[0],cutoff,expected:'100',counted:'90',fingerprint:'version1',version:1,status:'recorded'}];const input={...base,operation_type:'cash_count',action:'adjust',resource_id:ids[3],confirm:true,notes:'Faltante verificado'};assert.throws(()=>buildSpecialPlan(input,r,{...cut,fingerprint:'version2'}),/cambiaron/);const adjust=buildSpecialPlan(input,r,cut);assert.equal(adjust.lines[0].direction,'egreso');assert.equal(adjust.lines[0].amount,'10.00');assert.throws(()=>buildSpecialPlan({...base,operation_type:'cash_count',action:'opening',cutoff,counted:'100',confirm:true},r,cut),/nueva apertura/);});
