const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),ts=require('typescript');
const ctx={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/supplierReceiptGroups.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);
const items=[{poItemId:'a',productId:'P',sku:'SKU',ocCode:'OC1',quantityOrdered:11,quantityReceivedPrior:0,quantityReceivedNew:11,unitCost:10},{poItemId:'b',productId:'P',sku:'SKU',ocCode:'OC2',quantityOrdered:12,quantityReceivedPrior:2,quantityReceivedNew:10,unitCost:12}];
const group=ctx.exports.receiptGroups(items)[0];assert.equal(group.ordered,23);assert.equal(group.prior,2);assert.equal(group.quantity,21);assert.equal(group.subtotal,230);assert.equal(group.cost,null,'Different OC costs must remain distinct');
const result=ctx.exports.distributeReceiptQuantity(items,[0,1],15);assert.equal(result[0].quantityReceivedNew,11);assert.equal(result[1].quantityReceivedNew,4);assert.equal(result[1].poItemId,'b');assert.equal(items[1].quantityReceivedNew,10,'Original state must remain untouched');
const capped=ctx.exports.distributeReceiptQuantity(items,[0,1],100);assert.equal(capped[1].quantityReceivedNew,10);
const source=fs.readFileSync('src/app/admin/compras/page.tsx','utf8'),start=source.indexOf('  const toggleReceiptPO ='),end=source.indexOf('  const handleFulfillPOWithoutStock',start);
let alerts=[];const batch={exports:{},selectedReceiptPOIds:[],purchaseOrders:[{id:'A',supplier_id:'S',status:'Pendiente',oc_code:'OC1'},{id:'B',supplier_id:'S',status:'Parcial',oc_code:'OC2'},{id:'C',supplier_id:'OTHER',status:'Pendiente'}],receptionOrderLoading:{current:false},alert:v=>alerts.push(v),supabase:{from:()=>({select:()=>({in:async()=>({data:items.map((item,i)=>({id:item.poItemId,purchase_order_id:i?'B':'A',product_id:'P',quantity_ordered:12,quantity_received:2,unit_cost:item.unitCost,product:{sku:'SKU'}}))})})})}};
for(const name of ['setSelectedReceiptPOIds','setReceptionPOIds','setReceptionItems','setShowNewReceptionModal'])batch[name]=v=>batch[name.slice(3)]=typeof v==='function'?v(batch.selectedReceiptPOIds):v;
for(const name of ['setReceptionOrdersLoading','setReceptionSupplierId','setModalSupplierSearchText','setReceptionSlipNumber','setReceptionNotes','setModalOCSearchText','setReceptionAlignPO'])batch[name]=()=>{};
vm.runInNewContext(ts.transpileModule(source.slice(start,end)+';exports.toggle=toggleReceiptPO;exports.open=handleOpenReceptionForOrders;',{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,batch);
(async()=>{batch.exports.toggle(batch.purchaseOrders[0]);batch.selectedReceiptPOIds=batch.SelectedReceiptPOIds;batch.exports.toggle(batch.purchaseOrders[2]);assert.equal(alerts.length,1);await batch.exports.open(batch.purchaseOrders.slice(0,2));assert.equal(batch.ReceptionItems.length,2);assert.equal(batch.ReceptionPOIds.length,2);assert.equal(batch.ShowNewReceptionModal,true);console.log('Grouped receipt totals, mixed costs, bounded allocation and joint OC opening: OK');})().catch(e=>{console.error(e);process.exitCode=1;});


