const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const discountExports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/erp/discounts.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:discountExports});
const exportsObject={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/erp/prices.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:exportsObject,require:n=>n==='./discounts'?discountExports:require(n),Map,Set});
const {calculateProductPrice,calculateBulkPrices}=exportsObject;
function db(product){return{from(table){const q={select(){return q},eq(){return q},in(){return q},single:async()=>({data:product}),maybeSingle:async()=>({data:null}),then(resolve){return Promise.resolve({data:table==='products'?[product]:[]}).then(resolve)}};return q}};}
test('a fixed selling price preserves the current unified cost of new sales',async()=>{const p={id:'P',price:1000,fixed_price:true,sku:'P',cost_price:100,unified_cost:350};const result=await calculateProductPrice(db(p),'P');assert.equal(result.price,1000);assert.equal(result.cost,350);assert.equal(result.fixed,true);});
test('bulk fixed prices retain the last known material cost when integrated costs are pending',async()=>{const p={id:'P',price:1000,fixed_price:true,sku:'P',cost_price:100,unified_cost:null};const result=await calculateBulkPrices(db(p),[p]);assert.equal(result.P.cost,100);assert.equal(result.P.price,1000);});
test('bulk projections hydrate authoritative costs instead of freezing zero',async()=>{const full={id:'P',cost_price:100,unified_cost:350};const result=await calculateBulkPrices(db(full),[{id:'P',price:1000,fixed_price:true}]);assert.equal(result.P.cost,350);assert.equal(result.P.price,1000);});
test('a product without a supplier still retains a known catalog cost',async()=>{const p={id:'P',price:1000,fixed_price:false,sku:'P',cost_price:100,unified_cost:350};const result=await calculateProductPrice(db(p),'P');assert.equal(result.cost,350);assert.equal(result.price,1000);});
test('promo, combo and quantity discounts always cost zero while preserving their selling adjustment',async()=>{for(const name of ['Descuento Combo Biodigestor','Descuento - MEP x12','Descuento Compra Mayorista']){const p={id:'D',name,sku:name,price:-500,fixed_price:false,cost_price:123,unified_cost:999};const single=await calculateProductPrice(db(p),'D');const bulk=await calculateBulkPrices(db(p),[p]);assert.equal(single.cost,0);assert.equal(single.price,-500);assert.equal(bulk.D.cost,0);assert.equal(bulk.D.price,-500);}});
