const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function compile(file,imports=require){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:imports,Date,Intl,Set,Map});return exports;}
const m=compile('src/lib/costs/model.ts'),e=compile('src/lib/costs/engine.ts',name=>name==='./model'?m:require(name));
test('BioFort catalog descriptions match their recipes without merging brands or pipe diameters',()=>{for(const size of [300,500,600,750,1000])assert.equal(m.catalogIdentity(`Cámara Desengrasadora ${size===750?'para Cocina ':''}${size} Litros - BioFort`),m.catalogIdentity(`BioFort - Desengrasadora ${size}L`));for(const diameter of [50,110])assert.equal(m.catalogIdentity(`Cámara Desengrasadora 70 Litros (Caños ${diameter}mm) - BioFort`),m.catalogIdentity(`BioFort - Desengrasadora 70L (C${diameter})`));assert.notEqual(m.catalogIdentity('BioFort - Desengrasadora 70L (C50)'),m.catalogIdentity('BioFort - Desengrasadora 70L (C110)'));assert.notEqual(m.catalogIdentity('WP - Camara Desengrasadora C/canasto'),m.catalogIdentity('BioFort - Desengrasadora 300L'));assert.equal(m.catalogIdentity('Cisterna de agua 300 Litros - Aquafort'),m.catalogIdentity('AquaFort - CISTERNA 300L'));});
function fixture(){const def={captured:'2026-10-07',articles:[{code:'PIPE',name:'PVC Caño 4m',unit:'caño de 4 m',factor:1,fallback:null},{code:'CAP',name:'Tapa Click con aro',unit:'unidad',factor:1,fallback:null},{code:'BODY',name:'Tacho Cámara/Bio 1000L',unit:'unidad',factor:1,fallback:null}],recipes:[{code:'CUT',name:'Pieza 35cm',components:[{code:'PIPE',name:'PVC Caño 4m',quantity:.0875,unit:'caño de 4 m'}]}],products:[]};const product={code:'P',id:null,name:'BioFort Séptica',family:'BioFort',capacity:1000,origin:'Ensamblado',purchaseName:'P',termination:'',price:200,reference:null,recipe:{code:'P',name:'P',components:[{code:'CUT',name:'Pieza 35cm',quantity:2,unit:'unidad'}]}};def.products=[product];const purchases=[{key:'A',code:'PIPE',name:'PVC Caño 4m',source:'Compra',row:1,receipt:'1',vendor:'Proveedor',unit:'caño de 4 m',date:'2026-01-03',quantity:2,cost:400}];return {def,product,purchases};}
test('Spanish numbers and dates preserve decimals and reject invalid dates',()=>{assert.equal(m.number('1.234,56'),1234.56);assert.equal(m.number(1234.56),1234.56);assert.equal(m.date('31/02/2026'),null);assert.equal(m.date(46300),'2026-10-05');});
test('cuts use a 4m pipe and nested material recipes receive waste only once',()=>{const f=fixture();const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[]);assert.equal(r.material,73.5);assert.equal(r.lines[0].quantity,.175);assert.equal(r.coverage,'Parcial');assert.equal(r.suggested,null);});
test('missing price remains unknown rather than zero or a partial sum',()=>{const f=fixture();const r=e.calculate(f.def,[],f.product,'2026-10-07',[]);assert.equal(r.material,null);assert.equal(r.total,null);assert.equal(r.coverage,'Falta precio');});
test('as-of histories never use later purchases and weight monthly prices by quantity',()=>{const f=fixture();f.purchases.push({...f.purchases[0],key:'B',date:'2026-02-05',cost:800,quantity:1});assert.equal(e.calculate(f.def,f.purchases,f.product,'2026-01-31',[]).material,73.5);const feb=e.calculate(f.def,f.purchases,f.product,'2026-02-28',[]);assert.equal(feb.material,147);assert.equal(feb.recipeEstimated,true);});
test('manual origin settings only affect their effective period; purchases have no waste',()=>{const f=fixture();f.purchases.push({...f.purchases[0],code:'P',key:'BUY',cost:100});const s=[{code:'P',effective:'2026-09-01',origin:'Compra'}];assert.equal(e.calculate(f.def,f.purchases,f.product,'2026-08-31',s).origin,'Ensamblado');assert.equal(e.calculate(f.def,f.purchases,f.product,'2026-10-07',s).material,100);});
test('complete operating costs produce target margin using division, not markup',()=>{const f=fixture();const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[{code:'P',effective:'2026-10-01',labor:10,gas:0,electricity:0,overhead:0,margin:30,basis:'Medido'}]);assert.equal(r.total,83.5);assert.equal(r.coverage,'Completo');assert.ok(Math.abs(r.suggested-83.5/.7)<1e-8);});
test('purchased 1000L body includes its cap and does not expand a manufacture recipe',()=>{const f=fixture();f.product.recipe.components=[{code:'BODY',name:'Tacho Cámara/Bio 1000L',quantity:1,unit:'unidad'},{code:'CAP',name:'Tapa Click con aro',quantity:1,unit:'unidad'}];f.def.recipes.push({code:'BODY',name:'Tacho Cámara/Bio 1000L',components:[{code:'PIPE',name:'PVC Caño 4m',quantity:5,unit:'unidad'}]});f.def.products.push({...f.product,code:'BODY',name:'Tacho Cámara/Bio 1000L',origin:'Compra'});f.purchases.push({...f.purchases[0],code:'BODY',key:'BODYBUY',cost:1000});const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[]);assert.equal(r.material,1050);assert.equal(r.lines.length,1);});
test('cycles fail closed instead of overflowing or producing an understated total',()=>{const f=fixture();f.def.recipes[0].components=[{code:'CUT',name:'Pieza 35cm',quantity:1,unit:'unidad'}];const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[]);assert.equal(r.material,null);assert.ok(r.warnings.some(w=>w.includes('Ciclo')));});
test('alerts require both relative and absolute impact, including decreases',()=>{assert.equal(e.changed(100,120,10,30),false);assert.equal(e.changed(1000,800,10,100),true);assert.equal(e.changed(null,800,10,100),false);});
test('manual settings reject invalid origins, negative costs and impossible margins',()=>{assert.throws(()=>m.validateSetting({code:'P',effective:'2026-10-07',margin:100}));assert.throws(()=>m.validateSetting({code:'P',effective:'2026-10-07',gas:-1}));assert.throws(()=>m.validateSetting({code:'P',effective:'2026-10-07',origin:'Inventado'}));});
test('kit replaces cap, ring, brida and air vent, without duplicating vent cost',()=>{const f=fixture();f.def.articles.push({code:'KIT',name:'Tapa, Brida y Descompresor',unit:'unidad',factor:1,fallback:null});f.product.termination='Kit comprado';f.product.recipe.components=[{code:'CAP',name:'Tapa Click con aro',quantity:1,unit:'unidad'},{code:'VENT',name:'Descompresor de Aire',quantity:1,unit:'unidad'}];f.purchases.push({...f.purchases[0],code:'KIT',key:'K',cost:100});const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[]);assert.equal(r.material,105);assert.equal(r.lines.length,1);});
test('purchased branded lids add their own label even when a reference recipe has no brand label',()=>{const f=fixture();f.product.origin='Compra';f.product.brandLabel='Etiqueta Aquafort (Blanca)';f.def.articles.push({code:'LABEL',name:f.product.brandLabel,unit:'unidad',factor:1,fallback:null});f.purchases.push({...f.purchases[0],code:'LABEL',key:'LABEL',cost:600},{...f.purchases[0],code:'P',key:'FINISHED',cost:1000});const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[]);assert.equal(r.material,1600);assert.equal(r.lines.length,2);});
test('a newer supplier list updates the cost without inflating bought quantity or weighted purchase cost',()=>{const f=fixture();f.product.origin='Compra';f.purchases=[{...f.purchases[0],code:'P',key:'BUY',date:'2026-10-01',cost:100,quantity:2},{...f.purchases[0],code:'P',key:'LIST',date:'2026-10-03',cost:140,quantity:0,kind:'Lista'}];const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[]);assert.equal(r.material,140);assert.equal(r.purchasedQuantity,2);assert.equal(r.weightedPurchase,100);const before=e.calculate(f.def,f.purchases,f.product,'2026-10-02',[]);assert.equal(before.material,100);});
test('Eco plastic half-inch float aliases use dated reconciliation purchases instead of the old catalog fallback',()=>{const f=fixture();f.product={...f.product,code:'OLD',name:'Válvula de Flotante Eco 1/2" Varilla Plástica',origin:'Compra',recipe:undefined};f.def.products=[f.product];f.def.articles=[{code:'OLD',name:f.product.name,unit:'unidad',factor:1,fallback:4300},{code:'BUY',name:'Flotante Eco Varilla Plástica 1/2"',unit:'unidad',factor:1,fallback:4300}];f.purchases=[{...f.purchases[0],code:'BUY',name:f.def.articles[1].name,key:'3458',source:'Recibidos ZONO',date:'2026-10-02',quantity:120,cost:1973.47,vendor:'Inyectplast'}];const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[]);assert.equal(r.material,1973.47);assert.equal(r.lines[0].date,'2026-10-02');assert.equal(r.lines[0].vendor,'Inyectplast');assert.equal(r.purchasedQuantity,120);assert.equal(r.warnings.length,0);assert.equal(e.calculate(f.def,f.purchases,f.product,'2026-10-01',[]).material,4300);assert.notEqual(m.catalogIdentity('Flotante Eco Varilla Plástica 1/2"'),m.catalogIdentity('Flotante Completo Varilla Bronce Rao 1/2'));});
test('reviewed purchase names share dated evidence without merging different sizes, models or quantities',()=>{for(const group of m.purchaseNameGroups){const f=fixture();f.product={...f.product,code:'A',name:group[0],purchaseName:group[0],origin:'Compra',recipe:undefined};f.def.products=[f.product];f.def.articles=group.map((name,i)=>({code:i?'B':'A',name,unit:'unidad',factor:1,fallback:100}));f.purchases=[{...f.purchases[0],code:'B',name:group[1],date:'2026-10-02',quantity:3,cost:80}];const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[]);assert.equal(r.material,80,group[0]);assert.equal(r.purchasedQuantity,3);assert.equal(r.lines[0].date,'2026-10-02');}assert.notEqual(m.purchaseIdentity('Base Hierro Reforzada 74 cms'),m.purchaseIdentity('Base Hierro Reforzada 102 cms'));assert.notEqual(m.purchaseIdentity('Konan - Bomba Periferica 1/2 HP (KBP12)'),m.purchaseIdentity('Omaha - Bomba Periférica Elevadora 1/2hp'));});
test('web descriptions use ERP SKU purchase evidence while preserving order identity',()=>{const f=fixture();f.product={...f.product,code:'WEB',name:'Flotante Premium',purchaseName:'Flotante Premium',origin:'Compra',recipe:undefined};f.def.products=[f.product];f.def.articles=[{code:'WEB',name:'Flotante Premium',sku:'FLOTANTE RAO 1/2',aliases:['Flotante Premium','FLOTANTE RAO 1/2'],unit:'unidad',factor:1,fallback:7943},{code:'ERP',name:'Flotante RAO 1/2',sku:'Flotante RAO 1/2',aliases:['Flotante RAO 1/2'],unit:'unidad',factor:1,fallback:null}];f.purchases=[{...f.purchases[0],code:'ERP',name:'Flotante RAO 1/2',cost:8340.05}];const r=e.calculate(f.def,f.purchases,f.product,'2026-10-07',[]);assert.equal(r.material,8340.05);assert.equal(r.name,'Flotante Premium');assert.equal(m.resolvePurchaseArticle(f.def.articles,'Flotante RAO 1/2').code,'ERP');assert.equal(m.identifyingSku('AUTO-COMP-X'),null);assert.equal(m.identifyingSku('SKU_OLD'),null);const ambiguous=[{...f.def.articles[0],sku:'RAO',aliases:['Flotante']},{...f.def.articles[1],sku:'EGEO',aliases:['Flotante']}];assert.equal(m.resolvePurchaseArticle(ambiguous,'Flotante'),undefined);});
