const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const {generateKeyPairSync,webcrypto}=require('node:crypto');
const privateKey=generateKeyPairSync('rsa',{modulusLength:2048}).privateKey.export({type:'pkcs8',format:'pem'});
function fixture(channel,options={}) {
  const requests=[],eventId='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',caseId='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
  const tables={visit_integration_settings:[{id:true,public_url:'https://erp.example.test',telegram_chat_id:'-123',visits_calendar_id:'visits@example.test',installations_calendar_id:'installations@example.test'}],visit_delivery_jobs:[{id:'job',event_id:eventId,case_id:caseId,channel,state:'pending'}],visit_cases:[{id:caseId,number:3,customer_name:'Cliente <A>',locality:'Merlo',phone:'SECRET-PHONE'}],visit_events:[{id:eventId,kind:'create',data:{input:{scheduled_date:'2026-10-10',scheduled_time:'10:00'}}}],visit_appointments:[{id:eventId,case_id:caseId,date:'2026-10-10',start_time:'10:00',end_time:'11:00',status:'proposed'}]};
  if(options.missingConfig)tables.visit_integration_settings[0].telegram_chat_id='';
  const db={from(table){let rows=tables[table]||[],filters=[],patch=null;const query={select(){return query;},eq(k,v){filters.push(r=>r[k]===v);return query;},in(k,v){filters.push(r=>v.includes(r[k]));return query;},order(){return query;},limit(){return query;},update(v){patch=v;return query;},single(){return execute(true);},maybeSingle(){return execute(true);},then(resolve,reject){return execute(false).then(resolve,reject);}};function execute(single){const selected=rows.filter(r=>filters.every(f=>f(r)));if(patch)selected.forEach(r=>Object.assign(r,patch));return Promise.resolve({data:single?selected[0]||null:selected,error:null});}return query;}};
  const fetch=async(url,init={})=>{requests.push({url,method:init.method||'GET',body:init.body?String(init.body):null});if(url.includes('oauth2'))return Response.json({access_token:'mock-token',expires_in:3600});if(url.includes('telegram')){if(options.networkFailure)throw new TypeError('fetch failed');return Response.json({ok:true,result:{message_id:1}});}if(url.includes('?timeMin='))return Response.json({items:options.conflict?[{id:'other',status:'confirmed'}]:[]});if(init.method==='POST' || init.method==='PATCH')return Response.json({id:eventId.replaceAll('-','')});return Response.json({}, {status:options.existing?200:404});};
  const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/visits/integrations.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>n==='./model'?{visitCode:n=>`VIS-${n}`}:{createClient:()=>db},process:{env:{NEXT_PUBLIC_SUPABASE_URL:'https://db.example.test',SUPABASE_SERVICE_ROLE_KEY:'mock',LOGISTICS_TELEGRAM_BOT_TOKEN:'mock',GOOGLE_SERVICE_ACCOUNT_KEY:JSON.stringify({private_key:privateKey,client_email:'service@example.test'})}},fetch,crypto:webcrypto,btoa,atob,TextEncoder,Uint8Array,AbortSignal,URLSearchParams});
  return {run:()=>exports.processVisitJobs(caseId),requests,tables};
}
test('Telegram sends basic data and an authenticated deep link without phone or quote details',async()=>{const f=fixture('telegram');const result=await f.run();assert.equal(result.done,1);const text=JSON.parse(f.requests[0].body).text;assert.match(text,/Cliente &lt;A&gt;/);assert.match(text,/\/visitas\?case=/);assert.doesNotMatch(text,/SECRET-PHONE/);await f.run();assert.equal(f.requests.length,1);});
test('missing destination keeps a job pending and sends nothing',async()=>{const f=fixture('telegram',{missingConfig:true});assert.equal((await f.run()).pending,1);assert.equal(f.requests.length,0);assert.equal(f.tables.visit_delivery_jobs[0].state,'pending');});
test('ambiguous Telegram failure is held for review and never blindly resent',async()=>{const f=fixture('telegram',{networkFailure:true});assert.equal((await f.run()).failed,1);assert.equal(f.tables.visit_delivery_jobs[0].state,'unknown');await f.run();assert.equal(f.requests.length,1);});
test('Google creates a deterministic event with Argentina times and preserves the ERP link',async()=>{const f=fixture('google');assert.equal((await f.run()).done,1);const posted=f.requests.find(r=>r.method==='POST' && r.url.includes('/events?'));const body=JSON.parse(posted.body);assert.equal(body.id,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');assert.equal(body.start.dateTime,'2026-10-10T10:00:00-03:00');assert.equal(body.end.dateTime,'2026-10-10T11:00:00-03:00');assert.match(body.description,/\/visitas\?case=/);});
test('Google updates the same event on retry or rescheduling instead of creating a duplicate',async()=>{const f=fixture('google',{existing:true});assert.equal((await f.run()).done,1);assert.ok(f.requests.some(r=>r.method==='PATCH'));assert.ok(!f.requests.some(r=>r.method==='POST' && r.url.includes('/events?')));});
test('external calendar conflict is reported without losing or moving the local appointment',async()=>{const f=fixture('google',{conflict:true});assert.equal((await f.run()).failed,1);assert.equal(f.tables.visit_delivery_jobs[0].state,'error');assert.equal(f.tables.visit_appointments[0].start_time,'10:00');assert.ok(!f.requests.some(r=>['PATCH','POST'].includes(r.method) && r.url.includes('/events')));});
