'use client';
import type { ShippingQuote, ShippingRequest } from '@/lib/support/shipping';
import { paymentLabels, quoteExpired } from '@/lib/support/shipping';
import { fieldClass, secondaryClass } from './SupportShell';

export const emptyQuote = (): ShippingQuote => ({ carrier: '', cost: NaN, customer_price: NaN, payment: 'origin', delivery: '', valid_until: '', conditions: '' });
const money = (amount: number) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS' }).format(amount);
export function ShippingQuoteEditor({ quotes, onChange }: { quotes: ShippingQuote[]; onChange: (quotes: ShippingQuote[]) => void }) {
    const change = (index: number, patch: Partial<ShippingQuote>) => onChange(quotes.map((q, i) => i === index ? { ...q, ...patch } : q));
    return <div className="space-y-3"><p className="text-xs text-slate-500">Importes en ARS para el envío completo. Diferenciá el costo del transporte del importe que Ventas puede comunicar al cliente.</p>{quotes.map((quote, index) => <fieldset key={index} className="space-y-3 rounded border p-3"><div className="flex items-center justify-between"><h4 className="text-sm font-semibold">Opción {index + 1}</h4>{quotes.length > 1 && <button type="button" onClick={() => onChange(quotes.filter((_, i) => i !== index))} className="text-xs text-rose-600">Quitar opción</button>}</div>
        <label className="block text-sm">Transporte / expreso<input required maxLength={250} value={quote.carrier} onChange={e => change(index, { carrier: e.target.value })} className={`${fieldClass} mt-1`} /></label>
        <div className="grid grid-cols-2 gap-3">{(['cost', 'customer_price'] as const).map(field => <label key={field} className="text-sm">{field === 'cost' ? 'Costo transporte' : 'Importe al cliente'}<input type="number" required min={0} max={100000000} step="0.01" value={Number.isFinite(quote[field]) ? quote[field] : ''} onChange={e => change(index, { [field]: e.target.value === '' ? NaN : Number(e.target.value) })} className={`${fieldClass} mt-1`} /></label>)}</div>
        <label className="block text-sm">Forma de pago<select value={quote.payment} onChange={e => change(index, { payment: e.target.value as ShippingQuote['payment'] })} className={`${fieldClass} mt-1`}>{Object.entries(paymentLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
        <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Plazo estimado<input required maxLength={250} value={quote.delivery} onChange={e => change(index, { delivery: e.target.value })} className={`${fieldClass} mt-1`} /></label><label className="text-sm">Vigente hasta<input type="date" required value={quote.valid_until} onChange={e => change(index, { valid_until: e.target.value })} className={`${fieldClass} mt-1`} /></label></div>
        <label className="block text-sm">Condiciones / qué incluye<textarea rows={2} maxLength={1000} value={quote.conditions} onChange={e => change(index, { conditions: e.target.value })} className={`${fieldClass} mt-1`} /></label>
    </fieldset>)}{quotes.length < 5 && <button type="button" className={secondaryClass} onClick={() => onChange([...quotes, emptyQuote()])}>Agregar alternativa</button>}</div>;
}
export function ShippingQuoteList({ quotes, selected, selection, onSelect, historical = false }: { quotes: ShippingQuote[]; selected?: number | null; selection?: number; onSelect?: (index: number) => void; historical?: boolean }) {
    return <div className="space-y-2">{historical && <p className="text-xs text-amber-700">Cotizaciones anteriores como referencia. Logística debe recotizar antes de elegir una opción.</p>}{quotes.map((q, i) => { const expired = quoteExpired(q); return <article key={i} className={`rounded border p-3 ${selected === i ? 'border-emerald-300 bg-emerald-50' : 'bg-white'}`}>
        <div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-sm font-semibold">Opción {i + 1} · {q.carrier}</h4>{selected === i && <span className="text-xs text-emerald-700">Elegida</span>}{expired && <span className="text-xs text-rose-700">Vencida</span>}</div>
        <dl className="mt-2 grid grid-cols-2 gap-2 text-sm">{[['Costo transporte', money(q.cost)], ['Importe al cliente', money(q.customer_price)], ['Pago', paymentLabels[q.payment]], ['Plazo estimado', q.delivery], ['Vigente hasta', q.valid_until.split('-').reverse().join('/')]].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl>{q.conditions && <p className="mt-2 whitespace-pre-wrap text-sm">{q.conditions}</p>}
        {onSelect && <label className="mt-3 flex items-center gap-2 text-sm"><input type="radio" name="shipping-option" value={i} required checked={selection === i} disabled={expired || historical} onChange={() => onSelect(i)} />Elegir esta opción</label>}
    </article>; })}</div>;
}
export function ShippingRequestSummary({ request }: { request: ShippingRequest }) {
    return <dl className="space-y-2 text-sm">{[['Destino', `${request.locality}, ${request.province} · CP ${request.postal_code}`], ['Dirección', request.address], ['Cliente', request.customer], ['Presupuesto / pedido', request.reference], ['Productos y cantidades', request.products], ['Condiciones de entrega', request.conditions]].filter(([, value]) => value).map(([label, value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="whitespace-pre-wrap break-words">{value}</dd></div>)}</dl>;
}
