'use client';
import { useState } from 'react';
import { commandBody, errorMessage, supportRequest } from '@/lib/support/client';
import { priorities, ticketTypes, type SupportMe, type Ticket } from '@/lib/support/types';
import { Alert, fieldClass, secondaryClass } from './SupportShell';
export function TicketDataEditor({ticket,me,onDone}:{ticket:Ticket;me:SupportMe;onDone:()=>Promise<void>}) {
    const [assignee,setAssignee]=useState(ticket.assignee_id || '');const [priority,setPriority]=useState(ticket.priority);const [kind,setKind]=useState(ticket.type);const [sector,setSector]=useState(ticket.sector_id);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
    const save=async(action:string,data:Record<string,unknown>)=>{setBusy(true);setError('');try{await supportRequest(`tickets/${ticket.id}/actions`,{method:'POST',body:commandBody(data,ticket.version,action)});await onDone();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
    return <div className="space-y-3 border-b bg-slate-50 p-3">{error && <Alert>{error}</Alert>}<fieldset disabled={busy || me.impersonating} className="grid gap-3 sm:grid-cols-2">
      <form onSubmit={e=>{e.preventDefault();void save('assign',{assignee_id:assignee});}} className="flex items-end gap-2"><label className="min-w-0 flex-1 text-xs">Responsable<select value={assignee} onChange={e=>setAssignee(e.target.value)} className={`${fieldClass} mt-1`}><option value="">Sin asignar</option>{me.people.filter(p=>p.active && me.assignee_ids?.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className={secondaryClass} disabled={!assignee || assignee===ticket.assignee_id}>Asignar</button></form>
      <form onSubmit={e=>{e.preventDefault();void save('classify',{priority,type:kind});}} className="flex items-end gap-2"><label className="flex-1 text-xs">Prioridad<select value={priority} onChange={e=>setPriority(e.target.value as Ticket['priority'])} className={`${fieldClass} mt-1`}>{Object.entries(priorities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="flex-1 text-xs">Tipo<select value={kind} onChange={e=>setKind(e.target.value as Ticket['type'])} className={`${fieldClass} mt-1`}>{Object.entries(ticketTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className={secondaryClass} disabled={priority===ticket.priority && kind===ticket.type}>Guardar</button></form>
      {me.is_admin && <form onSubmit={e=>{e.preventDefault();void save('transfer',{sector_id:sector,body:reason});}} className="flex flex-wrap items-end gap-2 sm:col-span-2"><label className="min-w-40 flex-1 text-xs">Transferir al sector<select value={sector} onChange={e=>setSector(e.target.value)} className={`${fieldClass} mt-1`}>{me.sectors.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="min-w-40 flex-1 text-xs">Motivo<input required value={reason} maxLength={10000} onChange={e=>setReason(e.target.value)} className={`${fieldClass} mt-1`}/></label><button className={secondaryClass} disabled={sector===ticket.sector_id || !reason.trim()}>Transferir</button></form>}
    </fieldset></div>;
}
