'use client';
import { Fragment, Suspense, useEffect, useState } from 'react';
import Link from 'next/link';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { ChevronDown, MoreHorizontal, Search } from 'lucide-react';
import { supportRequest, errorMessage } from '@/lib/support/client';
import { availableActions, actionLabels, nextActor, type TicketAction } from '@/lib/support/actions';
import { code, dateLabel, priorities, statuses, type Ticket } from '@/lib/support/types';
import { Alert, fieldClass, Loading, secondaryClass, useSupport } from './SupportShell';
import { useRefreshSignal } from './useRefreshSignal';
import { TicketActionDialog } from './TicketActionDialog';
export function StatusBadge({status}:{status:Ticket['status']}) {
    const colors={new:'bg-slate-100 text-slate-700',in_progress:'bg-blue-50 text-blue-700',waiting_requester:'bg-amber-50 text-amber-800',waiting_validation:'bg-violet-50 text-violet-700',closed:'bg-emerald-50 text-emerald-700',cancelled:'bg-rose-50 text-rose-700'};
    return <span className={`inline-flex whitespace-nowrap rounded px-1.5 py-0.5 text-xs font-medium ${colors[status]}`}>{statuses[status]}</span>;
}
export function TicketList({management=false}:{management?:boolean}) {return <Suspense fallback={<Loading/>}><TicketTable management={management}/></Suspense>;}
function TicketTable({management}:{management:boolean}) {
    const {me}=useSupport();const router=useRouter();const path=usePathname();const params=useSearchParams();
    const view=params.get('view') || 'all';const search=params.get('q') || '';const sector=params.get('sector') || '';const status=params.get('status') || '';const priority=params.get('priority') || '';const page=params.get('cursor') || '';
    const [q,setQ]=useState(search);const [items,setItems]=useState<Ticket[]>([]);const [people,setPeople]=useState<{id:string;name:string}[]>([]);const [next,setNext]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const [expanded,setExpanded]=useState<string|null>(null);const [selected,setSelected]=useState<{ticket:Ticket;action:TicketAction}|null>(null);
    const automatic=useRefreshSignal(!selected);
    const [lastSearch,setLastSearch]=useState(search);
    if(lastSearch!==search){setLastSearch(search);setQ(search);}
    const change=(values:Record<string,string>)=>{const url=new URLSearchParams(params.toString());url.delete('cursor');Object.entries(values).forEach(([k,v])=>v?url.set(k,v):url.delete(k));setLoading(true);router.replace(`${path}${url.size?`?${url}`:''}`,{scroll:false});};
    useEffect(()=>{if(management && !me.is_manager)return;let alive=true;const query=new URLSearchParams({mode:management?'manage':'mine',view,q:search,limit:'25'});if(sector)query.set('sector_id',sector);if(status)query.set('status',status);if(priority)query.set('priority',priority);if(page)query.set('cursor',page);
        void supportRequest<{items:Ticket[];people:{id:string;name:string}[];next:string|null}>(`tickets?${query}`).then(data=>{if(alive){setItems(data.items);setPeople(data.people || []);setNext(data.next);setError('');}}).catch(e=>{if(alive)setError(errorMessage(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};
    },[management,me.is_manager,view,search,sector,status,priority,page,revision,automatic]);
    if(management && !me.is_manager)return <Alert>No tenés acceso a la bandeja de gestión.</Alert>;
    const name=(id:string)=>people.find(p=>p.id===id)?.name || me.people.find(p=>p.id===id)?.name || 'Usuario';
    const tabs=management?[['all','Todas'],['assigned','A mi cargo'],['unassigned','Sin asignar'],['action','Esperando solicitante'],['closed','Cerradas']]:[['all','Todas'],['action','Requieren mi acción'],['closed','Cerradas']];
    const returnTo=`${path}${params.size?`?${params}`:''}`;const filtered=Boolean(search || sector || status || priority || view!=='all');
    return <section className="space-y-3"><h2 className="sr-only">{management?'Bandeja de gestión':'Mis solicitudes'}</h2>
      <div className="flex flex-wrap items-center gap-1">{tabs.map(([value,label])=><button key={value} onClick={()=>change({view:value==='all'?'':value})} className={`rounded px-3 py-1.5 text-sm max-sm:min-h-11 ${view===value?'bg-indigo-50 font-medium text-indigo-700':'text-slate-500 hover:bg-slate-100'}`}>{label}</button>)}</div>
      <form onSubmit={e=>{e.preventDefault();change({q:q.trim()});}} className="flex flex-wrap items-center gap-2"><div className="relative min-w-40 flex-1"><Search className="absolute left-2.5 top-2 size-4 text-slate-400"/><input aria-label="Buscar por título o código" value={q} onChange={e=>setQ(e.target.value)} className={`${fieldClass} pl-8`} placeholder="Buscar ticket…"/></div><select aria-label="Estado" value={status} onChange={e=>change({status:e.target.value})} className={`${fieldClass} !w-auto max-sm:max-w-[48%]`}><option value="">Todos los estados</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="Sector" value={sector} onChange={e=>change({sector:e.target.value})} className={`${fieldClass} !w-auto max-sm:max-w-[48%]`}><option value="">Todos los sectores</option>{me.sectors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><details className="relative"><summary className={`${secondaryClass} cursor-pointer`}>Más filtros{priority?' · 1':''}</summary><div className="absolute right-0 z-30 mt-1 w-44 rounded border bg-white p-2 shadow-sm"><label className="text-xs">Prioridad<select aria-label="Prioridad" value={priority} onChange={e=>change({priority:e.target.value})} className={`${fieldClass} mt-1`}><option value="">Todas</option>{Object.entries(priorities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div></details><button className={secondaryClass}>Buscar</button>{filtered && <button type="button" className={secondaryClass} onClick={()=>{setQ('');change({q:'',view:'',sector:'',status:'',priority:''});}}>Limpiar</button>}</form>
      {error && <div><Alert>{error}</Alert><button className={secondaryClass} onClick={()=>setRevision(n=>n+1)}>Reintentar</button></div>}
      {loading?<Loading/>:!items.length?<div className="rounded-md border bg-white p-6 text-center"><h3 className="text-sm font-medium">No hay incidencias en esta vista</h3><p className="mt-1 text-xs text-slate-500">Revisá los filtros o creá un ticket.</p></div>:<div className="rounded-md border bg-white"><table className="w-full table-fixed text-left text-sm"><thead className="border-b bg-slate-50 text-xs text-slate-500"><tr><th className="w-[48%] px-3 py-2 font-medium sm:w-[35%] xl:w-[30%]">Ticket</th><th className="w-[35%] px-2 py-2 font-medium sm:w-[22%] xl:w-[16%]">Estado</th><th className="hidden px-2 py-2 font-medium sm:table-cell">Solicitante</th><th className="hidden px-2 py-2 font-medium xl:table-cell">Responsable</th><th className="hidden px-2 py-2 font-medium xl:table-cell">Sector</th><th className="hidden w-16 px-2 py-2 font-medium xl:table-cell">Prioridad</th><th className="hidden w-24 px-2 py-2 font-medium xl:table-cell">Actualización</th><th className="w-16 px-1 py-2 font-medium"><span className="sr-only">Acciones</span></th></tr></thead><tbody>{items.map(t=>{
        const actions=availableActions(me,t).filter(a=>['request_validation','close_admin'].includes(a));const href=`/incidencias/${t.id}?returnTo=${encodeURIComponent(returnTo)}`;
        return <Fragment key={t.id}><tr className="h-14 border-b border-slate-100 last:border-0 hover:bg-slate-50"><td className="px-3 py-1.5"><Link href={href} className="block"><span className="text-[11px] font-medium text-indigo-600">{code(t.number)}</span><span title={t.title} className="line-clamp-1 font-medium">{t.title}</span></Link></td><td className="px-2 py-1.5"><StatusBadge status={t.status}/>{['waiting_requester','waiting_validation'].includes(t.status) && <span className="mt-0.5 block truncate text-[11px] text-slate-500" title={nextActor(t,name)}>{nextActor(t,name)}</span>}</td><td className="hidden truncate px-2 sm:table-cell" title={name(t.created_by)}>{name(t.created_by)}</td><td className="hidden truncate px-2 xl:table-cell" title={t.assignee_id?name(t.assignee_id):''}>{t.assignee_id?name(t.assignee_id):'Sin asignar'}</td><td className="hidden truncate px-2 text-xs xl:table-cell" title={me.sectors.find(s=>s.id===t.sector_id)?.name}>{me.sectors.find(s=>s.id===t.sector_id)?.name}</td><td className="hidden px-2 text-xs xl:table-cell">{priorities[t.priority]}</td><td className="hidden px-2 text-xs xl:table-cell"><time title={dateLabel(t.updated_at)} dateTime={t.updated_at}>{new Date(t.updated_at).toLocaleDateString('es-AR',{timeZone:'America/Argentina/Buenos_Aires'})}</time></td><td className="px-1"><div className="flex items-center"><button aria-label={`Ver datos de ${code(t.number)}`} aria-expanded={expanded===t.id} onClick={()=>setExpanded(expanded===t.id?null:t.id)} className="p-1 max-sm:p-2 xl:hidden"><ChevronDown className="size-4"/></button><details className="relative"><summary aria-label={`Acciones de ${code(t.number)}`} className="flex cursor-pointer list-none justify-center rounded p-2 hover:bg-slate-100 max-sm:min-h-11"><MoreHorizontal className="size-4"/></summary><div className="absolute right-0 z-30 mt-1 w-44 rounded border bg-white p-1 shadow-sm"><Link href={href} className="block px-3 py-2">Abrir ticket</Link>{actions.map(a=><button key={a} disabled={me.impersonating} onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');setSelected({ticket:t,action:a});}} className="block w-full px-3 py-2 text-left text-sm hover:bg-slate-50 disabled:opacity-50">{actionLabels[a]}</button>)}</div></details></div></td></tr>{expanded===t.id && <tr className="border-b bg-slate-50 xl:hidden"><td colSpan={8} className="px-3 py-2"><dl className="grid grid-cols-2 gap-2 text-xs">{[['Solicitante',name(t.created_by)],['Responsable',t.assignee_id?name(t.assignee_id):'Sin asignar'],['Sector',me.sectors.find(s=>s.id===t.sector_id)?.name],['Prioridad',priorities[t.priority]],['Actualización',dateLabel(t.updated_at)]].map(([k,v])=><div key={k}><dt className="text-slate-500">{k}</dt><dd>{v}</dd></div>)}</dl></td></tr>}</Fragment>;
      })}</tbody></table></div>}
      <div className="flex justify-end gap-2">{page && <button className={secondaryClass} onClick={()=>change({})}>Volver al inicio</button>}{next && <button className={secondaryClass} onClick={()=>change({cursor:next})}>Siguiente página</button>}</div>
      {selected && <TicketActionDialog ticket={selected.ticket} action={selected.action} onClose={()=>setSelected(null)} onDone={async()=>{setRevision(n=>n+1);}}/>}
    </section>;
}
