'use client';
import { useState } from 'react';
import { commandBody, errorMessage, supportRequest } from '@/lib/support/client';
import { priorities, ticketTypes, type SupportMe, type Ticket } from '@/lib/support/types';
import { isShipping } from '@/lib/support/shipping';
import { Alert, fieldClass, secondaryClass } from './SupportShell';
import { ResponsibilityPicker } from './ResponsibilityPicker';
export function TicketDataEditor({ticket,me,onDone}:{ticket:Ticket;me:SupportMe;onDone:()=>Promise<void>}) {
    const [assignee,setAssignee]=useState(ticket.assignee_id || 'area');const [priority,setPriority]=useState(ticket.priority);const [kind,setKind]=useState(ticket.type);const [sector,setSector]=useState(ticket.sector_id);const [transferAssignee,setTransferAssignee]=useState('');const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
    const save=async(action:string,data:Record<string,unknown>)=>{setBusy(true);setError('');try{await supportRequest(`tickets/${ticket.id}/actions`,{method:'POST',body:commandBody(data,ticket.version,action)});await onDone();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
    return <div className="space-y-3 border-b bg-slate-50 p-3">{error && <Alert>{error}</Alert>}<fieldset disabled={busy || me.impersonating} className="grid gap-3 sm:grid-cols-2">
      <form onSubmit={e=>{e.preventDefault();void save('assign',{responsibility_kind:assignee==='area'?'area':'person',assignee_id:assignee==='area'?null:assignee});}} className="space-y-2"><ResponsibilityPicker fixedSector sector={ticket.sector_id} assignee={assignee} onChange={(_area,person)=>setAssignee(person)}/><button className={secondaryClass} disabled={!assignee || assignee===(ticket.assignee_id || 'area')}>Asignar</button></form>
      <form onSubmit={e=>{e.preventDefault();void save('classify',{priority,type:kind});}} className="flex items-end gap-2"><label className="flex-1 text-xs">Prioridad<select value={priority} onChange={e=>setPriority(e.target.value as Ticket['priority'])} className={`${fieldClass} mt-1`}>{Object.entries(priorities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{!isShipping(ticket) && <label className="flex-1 text-xs">Tipo<select value={kind} onChange={e=>setKind(e.target.value as Ticket['type'])} className={`${fieldClass} mt-1`}>{Object.entries(ticketTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}<button className={secondaryClass} disabled={priority===ticket.priority && kind===ticket.type}>Guardar</button></form>
      {me.is_admin && !isShipping(ticket) && <form onSubmit={e=>{e.preventDefault();void save('transfer',{sector_id:sector,assignee_id:transferAssignee==='area'?null:transferAssignee,body:reason});}} className="space-y-2 border-t pt-3 sm:col-span-2"><h3 className="text-sm font-semibold">Transferir a otra área responsable</h3><ResponsibilityPicker sector={sector} assignee={transferAssignee} onChange={(area,person)=>{setSector(area);setTransferAssignee(person);}}/><label className="block text-xs">Motivo<input required value={reason} maxLength={10000} onChange={e=>setReason(e.target.value)} className={`${fieldClass} mt-1`}/></label><button className={secondaryClass} disabled={sector===ticket.sector_id || !transferAssignee || !reason.trim()}>Transferir</button></form>}
    </fieldset></div>;
}
