'use client';
import SearchableSelect from '@/components/ui/SearchableSelect';
import VisitDateInput from './VisitDateInput';
import VisitNumberInput from './VisitNumberInput';
import { useEffect, useRef, useState } from 'react';
import { Loader2, Plus, Trash2, X } from 'lucide-react';
import { sortVisitKits, contactResults, lossReasons, money, outcomes, pendingReasons, quoteTotal, type Appointment, type Kit, type QuoteLine, type VisitCase, type VisitQuote, type VisitExtra, type VisitsMe } from '@/lib/visits/model';
import { validateCommand } from '@/lib/visits/validation';
export const inputStyle = 'w-full min-h-11 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500';
export const buttonStyle = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold hover:bg-slate-50 disabled:opacity-50';
export const primaryStyle = `${buttonStyle} !border-indigo-600 !bg-indigo-600 !text-white hover:!bg-indigo-700`;
const titles: Record<string, string> = { create: 'Nueva solicitud de visita', edit: 'Editar datos de la obra', assign: 'Responsables del caso', contact: 'Registrar contacto', kit: 'Definir kit final', appointment: 'Coordinar / reprogramar visita', visit_result: 'Registrar resultado de visita', quote: 'Nuevo presupuesto', quote_status: 'Estado del presupuesto', outcome: 'Resultado comercial', payment: 'Informar cobro de visita / seña', extras: 'Productos extras / adicionales', agreement: 'Valores acordados', note: 'Agregar observación', order_unlink: 'Desvincular pedido' };
function nowInput(days = 0) { const date = new Date(Date.now() + days * 86400000); return new Intl.DateTimeFormat('sv-SE', { timeZone: 'America/Argentina/Buenos_Aires', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(date).replace(' ', 'T'); }
function instant(value: unknown) { return `${String(value)}:00-03:00`; }
export function KitSelect({ kits, value, onChange, label = 'Kit', required = true, allowOther = false }: { kits: Kit[]; value: string; onChange: (id: string) => void; label?: string; required?: boolean; allowOther?: boolean }) {
  return <label className="block space-y-1 text-sm font-medium">{label}<select className={inputStyle} value={value} onChange={e => onChange(e.target.value)} required={required}><option value="">Seleccionar kit…</option>{sortVisitKits(kits).map(k => <option key={k.id} value={k.id}>{k.name}</option>)}{allowOther && <option value="other">Otro…</option>}</select></label>;
}
interface Props { action: string; me: VisitsMe; visit?: VisitCase; appointment?: Appointment; quote?: VisitQuote; orderId?: string; save: (data: Record<string, unknown>) => Promise<void>; close: () => void; refresh?: () => Promise<void>; whaticketLink?:string; }
export default function VisitForm({ action, me, visit: v, appointment: ap, quote: q, orderId, save, close, refresh, whaticketLink }: Props) {
  const [values, setValues] = useState<Record<string, unknown>>(() => ({
    whaticket_link: whaticketLink || '', locality_id: v?.locality_id || me.localities?.find(l=>l.name.toLowerCase()===v?.locality.toLowerCase())?.id || (v?.locality ? 'other' : ''), customer_name: v?.customer_name || '', phone: v?.phone || '', locality: v?.locality || '', address: v?.address || '', maps_url: v?.maps_url || '', request_reason: v?.request_reason || 'Relevamiento para instalación', notes: v?.notes || '',
    seller_id: v?.seller_id || (me.commercial ? me.id : ''), installer_id: v?.installer_id || me.default_installer_id || '', custom_kit: q?.kit.custom ? q.kit.name : v?.final_kit?.custom ? v.final_kit.name : '', kit_id: q?.kit.custom || v?.final_kit?.custom ? 'other' : q?.kit.id || v?.final_kit?.id || (action === 'create' ? '' : v?.interest_kit.id) || '',
    result: 'contacted', payment_kind:'visit', channel: 'WhatsApp', interlocutor: v?.customer_name || '', at: nowInput(), body: '',
    appointment_id: ap?.id || '', mode: ap?.mode || 'onsite', date: ap?.date || nowInput().slice(0, 10), start_time: ap?.start_time.slice(0, 5) || '09:00', end_time: ap?.end_time.slice(0, 5) || '10:00',
    status: action === 'appointment' ? 'proposed' : action === 'visit_result' ? 'completed' : action === 'quote_status' ? 'sent' : 'sent', client_confirmed: false, installer_confirmed: false,
    performed_at: nowInput(), technical: '', conditions: q?.conditions || 'Valor comunicado al cliente durante la visita', exclusions: q?.exclusions || '', valid_until: nowInput(7).slice(0, 10), valid_until_display: nowInput(7).slice(0,10).split('-').reverse().join('/'), communicated_at: nowInput().slice(0,10), quote_id: q?.id || '',
    outcome: 'pending', installation_date:v?.installation_date || '', reason: 'response', next_action: v?.next_action || 'Contactar al cliente', next_at: nowInput(1), next_owner_id: v?.seller_id || me.id,
    initial_installation_amount: v?.initial_installation_amount ?? '', visit_fee: v?.visit_fee ?? me.default_visit_fee ?? 50000, discount_visit_fee: v?.discount_visit_fee ?? true, extras_products: v?.extras_products || [], extras: v?.extras || '', scheduled_date: '', scheduled_time: '', amount: '', method: 'Efectivo', receiver: me.name, order_id: orderId || '',
  }));
  const [lines, setLines] = useState<QuoteLine[]>(()=>{const base=q?.lines || [{ description: v?.final_kit?.name || v?.interest_kit.name || '', quantity: 1, unit_price: Number(v?.initial_installation_amount ?? v?.final_kit?.price ?? v?.interest_kit.price ?? 0) }];return [...base,...(v?.extras_products || []).filter(e=>!base.some(l=>l.description===e.name)).map(e=>({description:e.name,quantity:e.quantity,unit_price:Number(e.unit_price || 0)}))];});
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [dirty, setDirty] = useState(false);
  const [specifyDay,setSpecifyDay]=useState(false),[specifyTime,setSpecifyTime]=useState(false);
  const [installationDefined,setInstallationDefined]=useState(Boolean(v?.installation_date));
  const dialog = useRef<HTMLDivElement>(null);
  const change = (key: string, value: unknown) => { setDirty(true); setValues(prev => ({ ...prev, [key]: value, ...(key === 'outcome' ? { reason: '' } : {}) })); };
  const cancel = () => { if (!busy && (!dirty || window.confirm('Tenés cambios sin guardar. ¿Querés descartarlos?'))) close(); };
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    dialog.current?.querySelector<HTMLElement>('input, select, textarea, button')?.focus();
    return () => previous?.focus();
  }, []);
  useEffect(() => {
    const unload = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } };
    window.addEventListener('beforeunload', unload); return () => window.removeEventListener('beforeunload', unload);
  }, [dirty]);
  const field = (label: string, key: string, type = 'text', required = false) => type === 'datetime-local' ? <div className="space-y-2"><VisitDateInput label={label} required={required} value={String(values[key] ?? '').slice(0,10)} onChange={date=>change(key,`${date}T${String(values[key] || '').slice(11,16) || '09:00'}`)}/><label className="block text-xs text-slate-500">Hora · {label}<input className={inputStyle} type="time" required={required} value={String(values[key] || '').slice(11,16)} onChange={e=>change(key,`${String(values[key] || '').slice(0,10)}T${e.target.value}`)}/></label></div> : type === 'date' ? <VisitDateInput label={label} value={String(values[key] ?? '')} required={required} onChange={value=>change(key,value)}/> : <label className="block space-y-1 text-sm font-medium">{label}{type === 'textarea' ? <textarea className={inputStyle} rows={3} maxLength={key === 'technical' ? 6000 : 3000} required={required} value={String(values[key] ?? '')} onChange={e => change(key, e.target.value)} /> : <input className={inputStyle} lang="es-AR" type={type} required={required} maxLength={['customer_name', 'phone', 'locality', 'request_reason'].includes(key) ? 500 : 3000} value={String(values[key] ?? '')} onChange={e => change(key, e.target.value)} {...(type === 'number' ? { min: 0, max: 100000000, step: '0.01' } : {})} />}</label>;
  const select = (label: string, key: string, options: Record<string, string>, required = true) => <label className="block space-y-1 text-sm font-medium">{label}<select className={inputStyle} required={required} value={String(values[key] ?? '')} onChange={e => change(key, e.target.value)}>{Object.entries(options).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>;
  const people = (roles: string[], empty = false) => Object.fromEntries([...(empty ? [['', 'Sin asignar']] : []), ...me.people.filter(p => p.roles.some(r => roles.includes(r))).map(p => [p.id, p.name])]);
  const followup = <><div className="sm:col-span-2">{field('Próxima acción', 'next_action', 'text', true)}</div>{field('Fecha de seguimiento', 'next_at', 'datetime-local', true)}{select('Quién debe actuar', 'next_owner_id', Object.fromEntries(me.people.filter(p => !v || [v.seller_id, v.installer_id].includes(p.id)).map(p => [p.id, p.name])))}</>;
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError('');
    const data = { ...values };
    for (const key of ['at', 'performed_at', 'next_at']) data[key] = instant(values[key]);
    data.communicated_at = instant(String(values.communicated_at).slice(0,10) + 'T12:00');
    if (!data.appointment_id) delete data.appointment_id;
    if(data.locality_id==='other')data.locality_id=null;
    if (action === 'quote') { data.lines = lines; data.valid_until = String(values.valid_until_display).split('/').reverse().join('-'); }
    if (action === 'payment') data.amount = Number(values.amount);
    try { validateCommand(action, data); setBusy(true); await save(data); setDirty(false); }
    catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar.'); }
    finally { setBusy(false); }
  }
  const kits = [...me.kits];
  for (const historical of [v?.interest_kit, v?.final_kit, q?.kit]) if (historical && !kits.some(k => k.id === historical.id)) kits.push(historical);
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/40 p-3" onMouseDown={e => { if (e.target === e.currentTarget) cancel(); }}>
    <div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="visit-form-title" className="max-h-[94dvh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white shadow-xl" onKeyDown={e => {
      if (e.key === 'Escape') { e.preventDefault(); cancel(); }
      if (e.key === 'Tab') { const items = dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]'); if (!items?.length) return; const first = items[0], last = items[items.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } }
    }}>
      <header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-3"><h2 id="visit-form-title" className="font-bold">{titles[action]}</h2><button type="button" aria-label="Cerrar formulario" onClick={cancel} disabled={busy} className={buttonStyle}><X size={18} /></button></header>
      <form data-shortcut-submit onSubmit={submit} className="space-y-4 p-5">
        {v && <p className="text-sm text-slate-600">{v.customer_name} · {v.locality}</p>}
        {values.kit_id === 'other' && <div>{field('Describir otro kit *', 'custom_kit', 'text', true)}</div>}
        <div className="grid gap-4 sm:grid-cols-2">
          {['create', 'edit'].includes(action) && <>
            {field('Cliente *', 'customer_name', 'text', true)}{field('Teléfono *', 'phone', 'tel', true)}<div><SearchableSelect label="Localidad" required value={String(values.locality_id)} options={[...(me.localities || []).map(l=>({value:l.id,label:l.name})),{value:'other',label:'Otro (escribir localidad)'}]} onChange={id=>{change('locality_id',id);if(id==='other')change('locality','');else change('locality',me.localities?.find(l=>l.id===id)?.name || '');}}/>{values.locality_id==='other' && field('Escribir localidad *','locality','text',true)}</div>{field('Dirección de la obra', 'address')}{field('Enlace a Maps', 'maps_url', 'url')}{field('Motivo de la visita *', 'request_reason', 'text', true)}{me.commercial && field('Enlace de Whaticket (interno)','whaticket_link','url')}
            {action === 'create' && <><div className="sm:col-span-2"><KitSelect kits={me.kits} label="Kit de interés *" value={String(values.kit_id)} onChange={id => { change('kit_id', id); change('initial_installation_amount', me.kits.find(k => k.id === id)?.price ?? ''); }} /></div><p className="self-center text-sm text-slate-600">Vendedor/a: <strong>{me.name}</strong></p>{select('Instalador', 'installer_id', people(['instalador'], true), false)}</>}
            {action === 'create' && <><div className="space-y-2"><label className="block space-y-1 text-sm font-medium">Día aproximado<select className={inputStyle} value={specifyDay?'specify':'installer'} onChange={e=>{const specify=e.target.value==='specify';setSpecifyDay(specify);if(!specify)change('scheduled_date','');}}><option value="installer">A coordinar por el instalador</option><option value="specify">Indicar día aproximado</option></select></label>{specifyDay && field('Día aproximado (opcional)', 'scheduled_date', 'date',true)}</div><div className="space-y-2"><label className="block space-y-1 text-sm font-medium">Hora aproximada<select className={inputStyle} value={specifyTime?'specify':'installer'} onChange={e=>{const specify=e.target.value==='specify';setSpecifyTime(specify);if(!specify)change('scheduled_time','');}}><option value="installer">A coordinar por el instalador</option><option value="specify">Indicar hora aproximada</option></select></label>{specifyTime && field('Indicar hora aproximada', 'scheduled_time', 'time',true)}</div>{field('Instalación inicial con kit ($)', 'initial_installation_amount', 'number')}{field('Valor acordado de visita ($)', 'visit_fee', 'number')}<label className="sm:col-span-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(values.discount_visit_fee)} onChange={e => change('discount_visit_fee', e.target.checked)} />Descontar el valor de la visita si acepta la instalación</label></>}
            <div className="sm:col-span-2">{field('Datos de acceso, disponibilidad y observaciones', 'notes', 'textarea')}</div>
          </>}
          {action === 'assign' && <>{select('Vendedor/a responsable', 'seller_id', people(['seller', 'admin']))}{select('Instalador', 'installer_id', people(['instalador'], true), false)}</>}
          {action === 'contact' && <>{select('Resultado', 'result', contactResults)}{select('Canal', 'channel', { WhatsApp: 'WhatsApp', Teléfono: 'Teléfono', Videollamada: 'Videollamada', Presencial: 'Presencial', Otro: 'Otro' })}{field('Con quién se habló / intentó hablar', 'interlocutor', 'text', true)}{field('Fecha y hora', 'at', 'datetime-local', true)}<div className="sm:col-span-2">{field('Qué se habló o qué ocurrió', 'body', 'textarea', true)}</div></>}
          {action === 'kit' && <><div className="sm:col-span-2"><p className="mb-3 text-sm text-slate-600">Interés inicial: <strong>{v?.interest_kit.name}</strong></p><KitSelect kits={me.kits} allowOther label="Kit finalmente seleccionado" value={String(values.kit_id)} onChange={id => change('kit_id', id)} /></div><div className="sm:col-span-2">{field('Motivo del cambio / observación', 'body', 'textarea', Boolean(v && String(values.kit_id) !== (v.final_kit?.id || v.interest_kit.id)))}</div><p className="sm:col-span-2 text-xs text-slate-500">Definir el kit no confirma la venta ni cambia presupuestos anteriores.</p></>}
          {action === 'appointment' && <>
            {select('Modalidad', 'mode', { onsite: 'Visita presencial', video: 'Videollamada' })}{field('Fecha', 'date', 'date', true)}{field('Desde', 'start_time', 'time', true)}{field('Hasta', 'end_time', 'time', true)}{select('Estado', 'status', { proposed: 'Propuesta / a confirmar', confirmed: 'Confirmada', ...(ap ? { cancelled: 'Cancelada' } : {}) })}
            <div className="space-y-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(values.client_confirmed)} onChange={e => change('client_confirmed', e.target.checked)} />El cliente confirmó la franja</label><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(values.installer_confirmed)} onChange={e => change('installer_confirmed', e.target.checked)} />El instalador confirmó disponibilidad</label></div><div className="sm:col-span-2">{field(ap ? 'Motivo del cambio y qué se informó al cliente *' : 'Coordinación / indicaciones', 'body', 'textarea', Boolean(ap))}</div>
          </>}
          {action === 'visit_result' && <>
            {select('Resultado de la visita', 'status', { completed: 'Realizada', missed: 'No realizada' })}{values.status === 'completed' && field('Fecha y hora de realización', 'performed_at', 'datetime-local', true)}<div className="sm:col-span-2">{field(values.status === 'completed' ? 'Qué se habló y cuál fue el resultado *' : 'Motivo por el que no se realizó *', 'body', 'textarea', true)}</div>
            {values.status === 'completed' && <><div className="sm:col-span-2">{field('Relevamiento: terreno, agua/luz, equipo, materiales y adicionales', 'technical', 'textarea')}</div>{v?.outcome === 'pending' && followup}</>}
          </>}
          {action === 'quote' && <>
            <div className="sm:col-span-2"><KitSelect kits={me.kits} allowOther label="Kit cotizado" value={String(values.kit_id)} onChange={id => change('kit_id', id)} /></div>
            <div className="sm:col-span-2 space-y-2"><p className="text-sm font-semibold">Agregar adicionales</p><div className="flex flex-wrap gap-2">{(me.extra_products || []).map(extra=><button key={extra.code} type="button" className={buttonStyle} disabled={lines.length>=30 || lines.some(l=>l.description===extra.name)} onClick={()=>{setDirty(true);setLines(prev=>[...prev,{description:extra.name,quantity:1,unit_price:Number(extra.unit_price || 0)}]);}}><Plus size={15}/>{extra.name}</button>)}</div><p className="text-xs text-slate-500">Adicionales: 1 unidad por metro. Terminación: por unidad. Completá cantidad y precio abajo.</p></div>
            <div className="space-y-3 sm:col-span-2"><p className="text-sm font-semibold">Conceptos del presupuesto · cantidad y precio unitario</p>{lines.map((line, index) => <div key={index} className="grid grid-cols-2 gap-2 sm:grid-cols-[minmax(0,1fr)_75px_110px_44px]">
              <input aria-label={`Concepto ${index + 1}`} className={`${inputStyle} min-w-0 col-span-2 sm:col-span-1`} required placeholder="Kit, mano de obra, adicional…" value={line.description} onChange={e => { setDirty(true); setLines(prev => prev.map((l, i) => i === index ? { ...l, description: e.target.value } : l)); }} />
              <VisitNumberInput aria-label={`Cantidad ${index + 1}`} className={inputStyle} required min={line.description==='Terminación Instalación Biofort'?'1':'0.01'} max="10000" step={line.description==='Terminación Instalación Biofort'?'1':'0.01'} value={line.quantity} onChange={quantity => { setDirty(true); setLines(prev => prev.map((l, i) => i === index ? { ...l, quantity } : l)); }} />
              <VisitNumberInput aria-label={`Precio unitario ${index + 1}`} className={inputStyle} required min="0" step="0.01" blankZero={line.description==='Terminación Instalación Biofort'} value={line.unit_price} onChange={unit_price => { setDirty(true); setLines(prev => prev.map((l, i) => i === index ? { ...l, unit_price } : l)); }} />
              <button type="button" className={buttonStyle} aria-label={`Quitar concepto ${index + 1}`} disabled={lines.length === 1} onClick={() => { setDirty(true); setLines(lines.filter((_, i) => i !== index)); }}><Trash2 size={15} /></button>
            </div>)}<button type="button" className={buttonStyle} disabled={lines.length >= 30} onClick={() => { setDirty(true); setLines([...lines, { description: '', quantity: 1, unit_price: 0 }]); }}><Plus size={16} />Concepto</button><p className="font-bold">Total: {money(quoteTotal(lines))}</p></div>
            <label className="block space-y-1 text-sm font-medium">Vigente hasta (dd/mm/aaaa)<input className={inputStyle} required inputMode="numeric" placeholder="dd/mm/aaaa" value={String(values.valid_until_display)} onChange={e => change('valid_until_display', e.target.value)} /></label>{select('Estado', 'status', { draft: 'Borrador', sent: 'Ya comunicado al cliente' })}{values.status === 'sent' && field('Cuándo se comunicó', 'communicated_at', 'date', true)}<div className="sm:col-span-2">{field('Alcance y condiciones de pago *', 'conditions', 'textarea', true)}</div><details className="sm:col-span-2"><summary className="cursor-pointer text-sm text-slate-500">Exclusiones (opcional)</summary>{field('Exclusiones', 'exclusions', 'textarea')}</details><p className="text-xs text-slate-500 sm:col-span-2">Se guardará una nueva versión. Las anteriores se conservan.</p>
          </>}
          {action === 'quote_status' && <>{select('Nuevo estado', 'status', me.commercial ? { sent: 'Enviado', accepted: 'Aceptado', rejected: 'Rechazado' } : { sent: 'Enviado' })}<div className="sm:col-span-2">{field('Qué informó el cliente / canal de comunicación', 'body', 'textarea', true)}</div><p className="sm:col-span-2 text-xs text-slate-500">La venta se confirma por separado en Resultado comercial.</p></>}
          {action === 'outcome' && <>
            {select('Resultado comercial', 'outcome', outcomes)}
            {values.outcome !== 'won' && select(values.outcome === 'lost' ? 'Motivo de no concreción *' : 'Por qué sigue pendiente *', 'reason', { '': 'Seleccionar motivo…', ...(values.outcome === 'lost' ? lossReasons : pendingReasons) })}
            <div className="sm:col-span-2">{field(values.outcome === 'won' ? 'Qué confirmó el cliente y por qué medio *' : 'Explicación del caso *', 'body', 'textarea', true)}</div>
            {values.outcome === 'pending' && followup}
            {values.outcome === 'won' && <><KitSelect kits={kits} allowOther label="Kit aceptado por el cliente" value={String(values.kit_id)} onChange={id => change('kit_id', id)} />{field('Fecha de confirmación', 'at', 'datetime-local', true)}<label className="block space-y-1 text-sm font-medium">Fecha de instalación<select className={inputStyle} value={installationDefined?'defined':'pending'} onChange={e=>{const defined=e.target.value==='defined';setInstallationDefined(defined);if(!defined)change('installation_date','');}}><option value="pending">Aún por definir</option><option value="defined">Fecha ya definida</option></select></label>{installationDefined && field('Día de instalación','installation_date','date',true)}</>}
          </>}
          {action === 'payment' && <>{select('Concepto del cobro','payment_kind',{visit:'Visita',deposit:'Seña de instalación'})}{field('Importe cobrado en esta ocasión', 'amount', 'number', true)}{field('Medio de pago', 'method', 'text', true)}{field('Quién recibió el dinero', 'receiver', 'text', true)}{field('Fecha del cobro', 'at', 'datetime-local', true)}<div className="sm:col-span-2">{field('Detalle / referencia del comprobante', 'body', 'textarea', true)}</div><p className="sm:col-span-2 text-xs text-slate-500">Cobro informado por vendedor/a o instalador. No genera movimientos contables ni pagos de pedidos.</p></>}
          {action === 'extras' && <div className="space-y-4 sm:col-span-2">{(me.extra_products || []).map(option=>{const selected=(values.extras_products as VisitExtra[]).find(e=>e.code===option.code);return <div key={option.code} className="space-y-2 rounded-lg border p-3"><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={Boolean(selected)} onChange={e=>change('extras_products',e.target.checked?[...(values.extras_products as VisitExtra[]),{...option,quantity:1}]:(values.extras_products as VisitExtra[]).filter(x=>x.code!==option.code))}/>{option.name}</label>{selected && <label className="block text-sm">{option.unit==='metro'?'Metros adicionales (1 unidad por metro)':'Cantidad de terminaciones'}<input className={inputStyle} type="number" required min={option.unit==='metro'?'0.01':'1'} max="10000" step={option.unit==='metro'?'0.01':'1'} value={selected.quantity} onChange={e=>change('extras_products',(values.extras_products as VisitExtra[]).map(x=>x.code===option.code?{...x,quantity:Number(e.target.value)}:x))}/></label>}</div>;})}{field('Observaciones sobre adicionales', 'extras', 'textarea')}</div>}
          {action === 'agreement' && <>{field('Instalación inicial con kit ($)', 'initial_installation_amount', 'number')}{field('Valor acordado de visita ($)', 'visit_fee', 'number')}<label className="sm:col-span-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(values.discount_visit_fee)} onChange={e => change('discount_visit_fee', e.target.checked)} />Descontar la visita si acepta la instalación</label></>}
          {['note', 'order_unlink'].includes(action) && <div className="sm:col-span-2">{field(action === 'note' ? 'Observación' : 'Motivo de desvinculación', 'body', 'textarea', true)}</div>}
        </div>
        {error && <div role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800"><p>{error}</p>{refresh && error.includes('ficha cambió') && <button type="button" className={`${buttonStyle} mt-2`} disabled={busy} onClick={() => { setBusy(true); void refresh().finally(() => setBusy(false)); }}>Actualizar ficha conservando formulario</button>}</div>}
        <div className="flex justify-end gap-2 border-t pt-4"><button type="button" className={buttonStyle} disabled={busy} onClick={cancel}>Cancelar</button><button className={primaryStyle} disabled={busy}>{busy && <Loader2 size={16} className="animate-spin" />}{busy ? 'Guardando…' : 'Guardar'}</button></div>
      </form>
    </div>
  </div>;
}
