'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { ArrowLeft, Loader2, MapPin, Phone, RefreshCw, Upload } from 'lucide-react';
import VisitOrderDraft from './VisitOrderDraft';
import VisitForm, { buttonStyle, inputStyle, primaryStyle } from './VisitForm';
import { visitsRequest } from '@/lib/visits/client';
import { supabase } from '@/lib/supabase';
import { contactResults, dateTimeLabel, eventLabels, money, outcomes, reasonLabel, quoteStatuses, safeExternalUrl, visitCode, visitStatuses, type Appointment, type VisitDetail as Detail, type VisitQuote, type VisitsMe } from '@/lib/visits/model';
type Action = { name: string; appointment?: Appointment; quote?: VisitQuote; orderId?: string };
export default function VisitDetail({ id, me, back, changed }: { id: string; me: VisitsMe; back: () => void; changed: () => void }) {
  const [detail, setDetail] = useState<Detail | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [action, setAction] = useState<Action | null>(null);
  const [orderSearch, setOrderSearch] = useState(''), [orderResults, setOrderResults] = useState<{ id: string; customer_name: string; total_amount: number; created_at: string }[]>([]), [orderBusy, setOrderBusy] = useState(false);
  const [uploading, setUploading] = useState(false), [message, setMessage] = useState('');
  const [orderChoice,setOrderChoice]=useState(false),[prepareOrder,setPrepareOrder]=useState(false);
  const ordersSection=useRef<HTMLElement>(null),choiceDialog=useRef<HTMLDivElement>(null);
  const pendingOrderAction=useRef<boolean|null>(null);
  useEffect(()=>{if(!orderChoice)return;const previous=document.activeElement as HTMLElement|null;choiceDialog.current?.querySelector<HTMLButtonElement>('button')?.focus();return()=>previous?.focus();},[orderChoice]);
  useEffect(()=>{if(orderChoice || pendingOrderAction.current===null)return;const create=pendingOrderAction.current;pendingOrderAction.current=null;ordersSection.current?.scrollIntoView({behavior:'smooth',block:'start'});if(!create)ordersSection.current?.querySelector<HTMLInputElement>('input[type=search]')?.focus();},[orderChoice]);
  const operation = useRef<{ signature: string; key: string } | null>(null);
  const uploadOperation = useRef<{ file: File; version: number; key: string } | null>(null);
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const load = useCallback(async () => {
    setLoading(true); setError('');
    try { const value = await visitsRequest(`/api/visits/case/${id}`); if (mounted.current) setDetail(value); }
    catch (e) { if (mounted.current) setError(e instanceof Error ? e.message : 'No se pudo abrir la visita.'); }
    finally { if (mounted.current) setLoading(false); }
  }, [id]);
  useEffect(() => { void load(); }, [load]);
  const hasDetail = Boolean(detail);
  useEffect(() => { if (hasDetail) void visitsRequest(`/api/visits/read/${id}`, { method: 'POST' }).then(changed).catch(() => {}); }, [id, hasDetail, changed]); // Mark notifications, without polling the whole case.
  const person = (id: string | null) => me.people.find(p => p.id === id)?.name || (id ? 'Usuario anterior' : 'Sin asignar');
  async function command(name: string, data: Record<string, unknown>) {
    if (!detail) return;
    const payload = { command: name, id, version: detail.visit.version, data };
    const signature = JSON.stringify(payload);
    if (operation.current?.signature !== signature) operation.current = { signature, key: crypto.randomUUID() };
    await visitsRequest('/api/visits/command', { method: 'POST', body: JSON.stringify({ ...payload, key: operation.current.key }) });
    operation.current = null; setAction(null); setMessage('Cambio guardado.'); changed(); await load();
    if(name==='outcome' && data.outcome==='won' && me.commercial && !detail.orders.length)setOrderChoice(true);
  }
  async function upload(file: File) {
    if (!detail) return;
    setUploading(true); setError('');
    try {
      if (!uploadOperation.current || uploadOperation.current.file !== file || uploadOperation.current.version !== detail.visit.version) uploadOperation.current = { file, version: detail.visit.version, key: crypto.randomUUID() };
      const form = new FormData(); form.set('file', file); form.set('version', String(detail.visit.version)); form.set('key', uploadOperation.current.key);
      const { data: { session } } = await supabase.auth.getSession(); if (!session) throw new Error('La sesión venció.');
      const response = await fetch(`/api/visits/upload/${id}`, { method: 'POST', headers: { Authorization: `Bearer ${session.access_token}` }, body: form });
      const result = await response.json(); if (!response.ok) throw new Error(result.error || 'No se pudo subir el archivo.');
      uploadOperation.current = null; setMessage('Archivo guardado.'); changed(); await load();
    } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo subir el archivo.'); }
    finally { setUploading(false); }
  }
  async function searchOrders() { setOrderBusy(true); setError(''); try { setOrderResults(await visitsRequest(`/api/visits/orders?search=${encodeURIComponent(orderSearch)}`)); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudieron buscar los pedidos.'); } finally { setOrderBusy(false); } }
  const v = detail?.visit;
  const open = (name: string, extra: Omit<Action, 'name'> = {}) => { setAction({ name, ...extra }); setMessage(''); };
  const actionButton = (label: string, name: string) => <button type="button" className={buttonStyle} onClick={() => open(name)}>{label}</button>;
  const chooseOrder=(create:boolean)=>{pendingOrderAction.current=create;setOrderChoice(false);if(create)setPrepareOrder(true);};
  return <div className="space-y-5 pb-8">
    <header className="flex flex-wrap items-center gap-3"><button type="button" onClick={back} className={buttonStyle}><ArrowLeft size={16} />Volver</button><button type="button" className={buttonStyle} onClick={() => { void navigator.clipboard.writeText(`${location.origin}/visitas?case=${id}`).then(() => setMessage('Enlace copiado.')).catch(() => setMessage('Copiá el enlace de la barra del navegador.')); }}>Copiar enlace</button><div className="flex-1"><p className="text-xs text-slate-500">{v ? visitCode(v.number) : 'Seguimiento de visitas'}</p><h1 className="text-xl font-bold">{v?.customer_name || 'Ficha de visita'}</h1></div><button type="button" onClick={() => void load()} disabled={loading} className={buttonStyle}><RefreshCw size={16} />Actualizar ficha</button></header>
    {error && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    {message && <p role="status" className="text-sm text-emerald-700">{message}</p>}
    {loading && !detail && <p role="status" className="flex items-center gap-2 py-8"><Loader2 className="animate-spin" size={18} />Abriendo visita…</p>}
    {detail && v && <>
      {v.outcome==='won' && <p className="rounded-lg border bg-white p-3 text-sm"><strong>Fecha de instalación:</strong> {v.installation_date?v.installation_date.split('-').reverse().join('/'):'Aún por definir'}</p>}
      {!detail.appointments.length && <p className="rounded-lg bg-indigo-50 p-3 text-sm text-indigo-900"><strong>Coordinación de visita:</strong> Día: {v.requested_date ? v.requested_date.split('-').reverse().join('/') : 'a coordinar por el instalador'} · Hora: {v.requested_time ? v.requested_time.slice(0,5) : 'a coordinar por el instalador'}</p>}
      <section className="rounded-xl border border-slate-200 bg-white p-4">
        <div className="flex flex-wrap items-center justify-between gap-3"><div><span className={`rounded-full px-3 py-1 text-sm font-semibold ${v.outcome === 'won' ? 'bg-emerald-50 text-emerald-800' : v.outcome === 'lost' ? 'bg-rose-50 text-rose-800' : 'bg-amber-50 text-amber-900'}`}>{outcomes[v.outcome]}</span><p className="mt-3 text-sm">{v.outcome === 'won' ? `Confirmada el ${dateTimeLabel(v.outcome_at)}` : reasonLabel(v.outcome, v.outcome_reason)}</p>{v.outcome_note && <p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{v.outcome_note}</p>}</div>{me.commercial && <button className={primaryStyle} onClick={() => open('outcome')}>{v.outcome === 'pending' ? 'Registrar resultado comercial' : 'Actualizar / reabrir seguimiento'}</button>}</div>
        {v.outcome === 'pending' && <div className={`mt-4 rounded-lg p-3 text-sm ${v.next_at && new Date(v.next_at) < new Date() ? 'bg-amber-50 text-amber-900' : 'bg-indigo-50 text-indigo-900'}`}><strong>Próxima acción:</strong> {v.next_action} · {person(v.next_owner_id)} · {dateTimeLabel(v.next_at)}</div>}
      </section>
      <section ref={ordersSection} className="scroll-mt-4 space-y-3 rounded-xl border bg-white p-4"><h2 className="font-bold">Pedidos vinculados <span className="text-xs font-normal text-slate-500">· opcionales</span></h2>{detail.orders.map(o => <div key={o.order_id} className="flex items-center justify-between gap-2 text-sm"><span>{o.reference}</span>{me.commercial && <button className={buttonStyle} onClick={() => open('order_unlink', { orderId: o.order_id })}>Desvincular</button>}</div>)}{!detail.orders.length && <p className="text-sm text-slate-500">Este caso se gestiona sin pedido vinculado.</p>}{me.commercial && <><VisitOrderDraft id={id} hasOrder={detail.orders.length>0} autoOpen={prepareOrder}/><div className="flex gap-2"><input className={inputStyle} type="search" aria-label="Buscar pedido por cliente" placeholder="Buscar un pedido por nombre de cliente…" value={orderSearch} onChange={e => setOrderSearch(e.target.value)} /><button className={buttonStyle} disabled={orderBusy || orderSearch.trim().length < 3} onClick={() => void searchOrders()}>Buscar</button></div>{orderResults.map(o => <div key={o.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-2 text-sm"><span>{o.customer_name} · {money(o.total_amount)} · {dateTimeLabel(o.created_at)}</span><button className={buttonStyle} disabled={detail.orders.some(link => link.order_id === o.id)} onClick={() => { void command('order_link', { order_id: o.id }).catch(e => setError(e.message)); }}>Vincular</button></div>)}</>}</section>
      <div className="grid gap-4 lg:grid-cols-2">
        <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><h2 className="font-bold">Cliente y obra</h2><p className="text-sm"><strong>{v.locality}</strong> · {v.address || 'Dirección pendiente'}</p><div className="flex flex-wrap gap-2"><a className={buttonStyle} href={`tel:${v.phone.replace(/[^+\d]/g, '')}`}><Phone size={15} />{v.phone}</a><a className={buttonStyle} target="_blank" rel="noopener noreferrer" href={`https://wa.me/${v.phone.replace(/\D/g, '')}`}>WhatsApp</a>{safeExternalUrl(v.maps_url) && <a className={buttonStyle} target="_blank" rel="noopener noreferrer" href={safeExternalUrl(v.maps_url)}><MapPin size={15} />Maps</a>}</div>{me.commercial && safeExternalUrl(detail.commercial?.whaticket_link || '') && <a className={buttonStyle} target="_blank" rel="noopener noreferrer" href={safeExternalUrl(detail.commercial?.whaticket_link || '')}>Abrir Whaticket (interno)</a>}<p className="text-sm">{v.request_reason}</p>{v.notes && <p className="whitespace-pre-wrap text-sm text-slate-600">{v.notes}</p>}<p className="text-sm text-slate-600">Vendedor/a: {person(v.seller_id)}<br />Instalador: {person(v.installer_id)}</p>{me.commercial && <div className="flex flex-wrap gap-2">{actionButton('Editar datos', 'edit')}{actionButton('Asignar responsables', 'assign')}</div>}</section>
        <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><h2 className="font-bold">Kit y presupuesto</h2><p className="text-sm"><span className="text-slate-500">Interés inicial</span><br /><strong>{v.interest_kit.name}</strong></p><p className="text-sm"><span className="text-slate-500">Kit finalmente seleccionado</span><br /><strong>{v.final_kit?.name || 'Sin definir'}</strong></p><p className="text-lg font-bold">{money(v.quote_amount)}<span className="ml-2 text-xs font-normal text-slate-500">{quoteStatuses[v.quote_status as keyof typeof quoteStatuses] || ''}</span></p>{v.outcome === 'pending' && <div className="flex flex-wrap gap-2">{actionButton('Definir kit final', 'kit')}{actionButton('Cargar presupuesto', 'quote')}</div>}</section>
      </div>
      <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">Contactos y visitas <span className="text-sm font-normal text-slate-500">· {v.visit_count} realizadas</span></h2><div className="flex gap-2">{actionButton('Registrar contacto', 'contact')}{v.outcome === 'pending' && actionButton('Coordinar visita', 'appointment')}</div></div><p className="text-sm text-slate-500">Contacto: {v.contact_status === 'none' ? 'Sin intentos registrados' : contactResults[v.contact_status]}</p>
        {!detail.appointments.length && <p className="text-sm text-slate-500">Todavía no hay visitas coordinadas.</p>}
        {detail.appointments.map(ap => <div key={ap.id} className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm"><strong>{ap.date.split('-').reverse().join('/')} · {ap.start_time.slice(0, 5)}–{ap.end_time.slice(0, 5)}</strong> · {ap.mode === 'onsite' ? 'Presencial' : 'Videollamada'} · {visitStatuses[ap.status]}</p>{['proposed', 'confirmed'].includes(ap.status) && <div className="flex flex-wrap gap-2">{v.outcome === 'pending' && <button className={buttonStyle} onClick={() => open('appointment', { appointment: ap })}>Reprogramar / confirmar</button>}<button className={buttonStyle} onClick={() => open('visit_result', { appointment: ap })}>Registrar resultado</button></div>}</div>{ap.note && <p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{ap.note}</p>}{ap.result && <p className="mt-2 whitespace-pre-wrap text-sm">{ap.result}</p>}{(ap as Appointment & { technical?: string }).technical && <details className="mt-2 text-sm"><summary className="cursor-pointer font-medium">Relevamiento técnico</summary><p className="mt-2 whitespace-pre-wrap">{(ap as Appointment & { technical?: string }).technical}</p></details>}</div>)}
      </section>
      {!!detail.quotes.length && <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><h2 className="font-bold">Versiones de presupuesto</h2>{detail.quotes.map(q => <details key={q.id} className="rounded-lg border p-3" open={q.id === v.quote_id}><summary className="cursor-pointer text-sm font-semibold">Versión {q.number} · {money(q.total)} · {quoteStatuses[q.status]} · {q.kit.name}</summary><div className="mt-3 space-y-3 text-sm"><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="text-xs text-slate-500"><th>Concepto</th><th>Cantidad</th><th>Precio unitario</th></tr></thead><tbody>{q.lines.map((l, i) => <tr key={i} className="border-t"><td className="py-2 pr-3">{l.description}</td><td>{l.quantity}</td><td>{money(l.unit_price)}</td></tr>)}</tbody></table></div><p className="whitespace-pre-wrap">{q.conditions}</p>{q.exclusions && <p className="whitespace-pre-wrap text-slate-500">Exclusiones: {q.exclusions}</p>}<p>Vigente hasta {q.valid_until.split('-').reverse().join('/')}{q.communicated_at ? ` · Comunicado: ${dateTimeLabel(q.communicated_at)}` : ''}</p>{q.id === v.quote_id && ['draft', 'sent'].includes(q.status) && <button className={buttonStyle} onClick={() => open('quote_status', { quote: q })}>Registrar envío / respuesta</button>}</div></details>)}</section>}
      <div className="grid gap-4 lg:grid-cols-2"><section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-bold">Cobros de visita y seña informados</h2><p className="text-lg font-semibold">Visita: {money(v.payment_amount)}<br />Seña: {money(v.deposit_amount || 0)}</p><p className="text-xs text-slate-500">Registro operativo. La validación contable y los descuentos se gestionan por separado.</p>{actionButton('Informar cobro de visita / seña', 'payment')}</section><section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-bold">Archivos y fotos</h2><label className={`${buttonStyle} cursor-pointer`}><Upload size={16} />{uploading ? 'Subiendo…' : 'Adjuntar foto / PDF'}<input type="file" className="sr-only" accept="image/png,image/jpeg,image/webp,application/pdf" disabled={uploading} onChange={e => { const file = e.target.files?.[0]; if (file) void upload(file); }} /></label>{uploadOperation.current && !uploading && error && <button className={buttonStyle} onClick={() => void upload(uploadOperation.current!.file)}>Reintentar archivo</button>}<div className="flex flex-wrap gap-3">{detail.attachments.map(a => <a key={a.id} href={a.url} target="_blank" rel="noopener noreferrer" className="max-w-40 break-words text-sm text-indigo-700 underline">{a.mime.startsWith('image/') && <Image src={a.url} alt={a.name} width={128} height={96} unoptimized className="mb-1 h-24 w-32 rounded object-cover" />}{a.name}</a>)}</div></section></div>
      <section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-bold">Valores acordados y extras</h2><p className="text-sm">Instalación inicial con kit: <strong>{money(v.initial_installation_amount ?? null)}</strong><br />Visita: <strong>{money(v.visit_fee || 0)}</strong> · {v.discount_visit_fee !== false ? 'Se descuenta si acepta la instalación' : 'No se descuenta'}</p>{me.commercial && actionButton('Editar valores', 'agreement')}<p className="whitespace-pre-wrap text-sm">{(v.extras_products || []).map(e=>`${e.name}: ${e.quantity} ${e.unit==='metro'?'m (1 unidad por metro)':'unidad(es)'}`).join('\n') || (!v.extras?'Sin productos extras informados':'')}{v.extras ? '\n' + v.extras : ''}</p>{actionButton('Informar productos extras', 'extras')}</section>
      <section className="space-y-3 rounded-xl border bg-white p-4"><div className="flex items-center justify-between"><h2 className="font-bold">Historial</h2>{actionButton('Agregar observación', 'note')}</div><p className="text-xs text-slate-500">Últimas 100 acciones. Cada cambio conserva su autor y datos anteriores.</p>{detail.events.map(event => {
        const data = (event.data.input || {}) as Record<string, unknown>;
        const after = event.data.after as { final_kit?: { name: string } } | undefined;
        const previous = data.previous as Appointment | undefined;
        return <article key={event.id} className="border-t py-3 text-sm"><p><strong>{eventLabels[event.kind] || 'Actualización'}</strong> · {person(event.actor_id)}<span className="block text-xs text-slate-500 sm:ml-2 sm:inline">{dateTimeLabel(event.created_at)}</span></p>{event.body && <p className="mt-1 whitespace-pre-wrap">{event.body}</p>}{event.kind === 'contact' && <p className="mt-1 text-xs text-slate-500">{String(data.channel)} · {String(data.interlocutor)} · {dateTimeLabel(String(data.at))} · {contactResults[data.result as keyof typeof contactResults]}</p>}{event.kind === 'kit' && <p className="mt-1 text-xs text-slate-500">Seleccionado: {after?.final_kit?.name}</p>}{event.kind === 'outcome' && <p className="mt-1 text-xs text-slate-500">{outcomes[data.outcome as keyof typeof outcomes]}{data.reason ? ` · ${reasonLabel(String(data.outcome), String(data.reason))}` : ''}</p>}{event.kind === 'appointment' && <p className="mt-1 text-xs text-slate-500">{previous?.date ? `Anterior: ${previous.date} ${previous.start_time.slice(0, 5)}–${previous.end_time.slice(0, 5)}. ` : ''}Nueva: {String(data.date)} {String(data.start_time)}–{String(data.end_time)}{data.status === 'cancelled' ? ' · Cancelada' : ''}</p>}{event.kind === 'payment' && <p className="mt-1 text-xs text-slate-500">{data.payment_kind==='deposit'?'Seña':'Visita'} · {money(Number(data.amount))} · {String(data.method)} · Recibió: {String(data.receiver)}</p>}</article>;
      })}</section>
    </>}
    {action && detail && <VisitForm key={action.name + (action.appointment?.id || '') + (action.quote?.id || '')} action={action.name} me={me} visit={detail.visit} appointment={action.appointment} quote={action.quote} orderId={action.orderId} refresh={load} close={() => setAction(null)} save={data => command(action.name, data)} />}
    {orderChoice && <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/40 p-4"><div ref={choiceDialog} role="dialog" aria-modal="true" aria-labelledby="visit-order-choice-title" className="w-full max-w-lg space-y-4 rounded-xl bg-white p-5 shadow-xl" onKeyDown={e=>{if(e.key==='Escape')setOrderChoice(false);if(e.key==='Tab'){const buttons=choiceDialog.current?.querySelectorAll<HTMLButtonElement>('button');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey && document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey && document.activeElement===last){e.preventDefault();first.focus();}}}}><h2 id="visit-order-choice-title" className="text-lg font-bold">¿Deseás registrar el pedido o vincularlo a un pedido actual?</h2><p className="text-sm text-slate-600">La venta ya quedó concretada. Elegí cómo continuar.</p><div className="flex flex-wrap gap-2"><button className={primaryStyle} onClick={()=>chooseOrder(true)}>Registrar pedido</button><button className={buttonStyle} onClick={()=>chooseOrder(false)}>Vincular a un pedido actual</button></div><button className="text-sm text-slate-500 underline" onClick={()=>setOrderChoice(false)}>Más tarde</button></div></div>}
  </div>;
}
