'use client';
import { useState } from 'react';
import { visitsRequest } from '@/lib/visits/client';
import { buttonStyle, inputStyle, primaryStyle } from './VisitForm';
interface Settings { public_url:string;telegram_chat_id:string;visits_calendar_id:string;installations_calendar_id:string;default_visit_fee:string;service_email?:string;delivery_status?: {state:string;message:string}[]; }
export default function VisitsIntegrations({ onFeeSaved }: { onFeeSaved: (fee: number) => void }) {
  const [values,setValues] = useState<Settings | null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function load() { try { const data=await visitsRequest('/api/visits/settings'); setValues({...data,default_visit_fee:String(data.default_visit_fee ?? 50000)}); } catch(e) { setMessage(e instanceof Error ? e.message : 'No se pudo abrir.'); } }
  return <details className="rounded-xl border bg-white p-4" onToggle={e => { if (e.currentTarget.open && !values) void load(); }}><summary className="cursor-pointer text-sm font-semibold">Configuración de visitas</summary>{values && <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e => { e.preventDefault();setBusy(true);setMessage('');try { await visitsRequest('/api/visits/settings',{method:'POST',body:JSON.stringify(values)});onFeeSaved(Number(values.default_visit_fee));setMessage('Configuración guardada.'); }catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);} }}>
    <label className="text-sm sm:col-span-2">Valor de visita por defecto ($)<input className={inputStyle} required type="number" min="0" max="100000000" step="0.01" value={values.default_visit_fee} onChange={e=>setValues({...values,default_visit_fee:e.target.value})}/><span className="text-xs text-slate-500">Se aplica a visitas nuevas. En cada visita puede acordarse otro valor.</span></label>
    {Object.entries({public_url:'URL pública del ERP (para los enlaces)',telegram_chat_id:'ID del grupo de Telegram',visits_calendar_id:'ID del calendario de visitas',installations_calendar_id:'ID del calendario de instalaciones'}).map(([key,label])=><label key={key} className="text-sm">{label}<input className={inputStyle} type={key==='public_url'?'url':'text'} value={String(values[key as keyof Settings]||'')} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}
    <p className="text-xs text-slate-500 sm:col-span-2">Compartí los calendarios con permiso para modificar eventos con: {values.service_email || 'cuenta de servicio de Google aún no configurada'}. Agregá el bot de comunicaciones al grupo elegido. Los enlaces requieren ingresar al ERP.</p><div className="flex gap-2 sm:col-span-2"><button className={primaryStyle} disabled={busy}>Guardar configuración</button><button type="button" className={buttonStyle} disabled={busy} onClick={async()=>{setBusy(true);try{const result=await visitsRequest('/api/visits/deliver',{method:'POST',body:'{}'});setMessage(result.message);}catch(e){setMessage(e instanceof Error?e.message:'No se pudo sincronizar.');}finally{setBusy(false);}}}>Procesar avisos pendientes</button></div>
    {!!values.delivery_status?.length && <p className="text-xs text-amber-800 sm:col-span-2">{values.delivery_status.length} entregas pendientes o por revisar. {Array.from(new Set(values.delivery_status.map(j=>j.message).filter(Boolean))).join(' ')}</p>}
  </form>}{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</details>;
}
