'use client';
import VisitDateInput from './VisitDateInput';
import { useRef, useState } from 'react';
import { buttonStyle, inputStyle, primaryStyle } from './VisitForm';
import { visitStatuses, type Appointment, type VisitCase, type VisitsMe } from '@/lib/visits/model';
import { visitsRequest } from '@/lib/visits/client';
export interface Slot { id: string; installer_id: string; case_id: string | null; kind: 'installation' | 'available' | 'blocked'; date: string; start_time: string; end_time: string; title: string; cancelled: boolean; }
export default function VisitsCalendar({ month, appointments, visits, unplanned = [], slots = [], me, open, refresh }: { month: string; appointments: Appointment[]; visits: VisitCase[]; unplanned?: VisitCase[]; slots?: Slot[]; me: VisitsMe; open: (id: string) => void; refresh: () => void }) {
  const operation=useRef<{signature:string;key:string}|null>(null);
  const [choices,setChoices]=useState<VisitCase[]>([]);
  const [form, setForm] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [kind, setKind] = useState('available'), [day, setDay] = useState(`${month}-01`), [title, setTitle] = useState(''), [installer, setInstaller] = useState(me.commercial ? me.default_installer_id || '' : me.id);
  const [start, setStart] = useState('09:00'), [end, setEnd] = useState('18:00'), [caseId, setCaseId] = useState('');
  const [year, num] = month.split('-').map(Number), first = new Date(Date.UTC(year, num - 1, 1)), count = new Date(Date.UTC(year, num, 0)).getUTCDate(), offset = (first.getUTCDay() + 6) % 7;
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const data={ installer_id: installer, case_id: caseId, kind, date: day, start_time: start, end_time: end, title: title || (kind === 'available' ? 'Disponible para instalar' : kind === 'blocked' ? 'No disponible' : 'Instalación') };const signature=JSON.stringify(data);if(operation.current?.signature!==signature)operation.current={signature,key:crypto.randomUUID()};await visitsRequest('/api/visits/slot',{method:'POST',body:JSON.stringify({key:operation.current.key,data})});operation.current=null; setForm(false); refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar.'); } finally { setBusy(false); } }
  return <section className="space-y-3">
    <div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-slate-500">Azul: visita · ámbar: instalación · verde: disponible · gris: no disponible. Las visitas propuestas tienen horario aproximado.</p><button className={buttonStyle} onClick={() => { setForm(!form); if(!form) void visitsRequest('/api/visits/list').then(r=>setChoices(r.visits)).catch(()=>{}); }}>Instalación / disponibilidad</button></div>
    {form && <form onSubmit={save} className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-3">
      <label className="text-sm">Tipo<select className={inputStyle} value={kind} onChange={e => setKind(e.target.value)}><option value="available">Disponible para instalar</option><option value="installation">Instalación</option><option value="blocked">No disponible</option></select></label>
      <VisitDateInput label="Día" required value={day} onChange={setDay} />
      <label className="text-sm">Instalador<select className={inputStyle} required value={installer} onChange={e => setInstaller(e.target.value)}>{me.people.filter(p => p.roles.includes('instalador') && (me.commercial || p.id === me.id)).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      <label className="text-sm">Desde<input className={inputStyle} type="time" required value={start} onChange={e => setStart(e.target.value)} /></label><label className="text-sm">Hasta<input className={inputStyle} type="time" required value={end} onChange={e => setEnd(e.target.value)} /></label>
      <label className="text-sm">Detalle<input className={inputStyle} maxLength={300} value={title} onChange={e => setTitle(e.target.value)} placeholder={kind === 'installation' ? 'Cliente / localidad' : 'Opcional'} /></label>
      {kind === 'installation' && <label className="text-sm">Vincular a visita (opcional)<select className={inputStyle} value={caseId} onChange={e => setCaseId(e.target.value)}><option value="">Sin vínculo</option>{[...visits, ...unplanned,...choices].filter((v, i, all) => all.findIndex(x => x.id === v.id) === i).map(v => <option key={v.id} value={v.id}>{v.customer_name} · {v.locality}</option>)}</select></label>}
      {error && <p role="alert" className="text-sm text-rose-700 sm:col-span-3">{error}</p>}<div className="flex gap-2 sm:col-span-3"><button className={primaryStyle} disabled={busy}>Guardar</button><button type="button" className={buttonStyle} onClick={() => setForm(false)}>Cancelar</button></div>
    </form>}
    {!!unplanned.length && <div className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Por coordinar · {unplanned.length}</h2><p className="mt-1 text-xs text-slate-500">Están asignadas y aún no tienen una cita pendiente.</p><div className="mt-3 flex flex-wrap gap-2">{unplanned.map(v => <button key={v.id} className={buttonStyle} onClick={() => open(v.id)}>{v.customer_name} · {v.locality}</button>)}</div></div>}
    <div className="overflow-x-auto rounded-xl border bg-white"><div className="min-w-[650px]"><div className="grid grid-cols-7 border-b bg-slate-50 text-center text-xs font-semibold">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d => <div key={d} className="p-3">{d}</div>)}</div><div className="grid grid-cols-7">{Array.from({ length: Math.ceil((count + offset) / 7) * 7 }, (_, index) => {
      const n = index - offset + 1, date = `${month}-${String(n).padStart(2,'0')}`;
      return <div key={index} className={`min-h-28 border-b border-r p-1.5 ${n < 1 || n > count ? 'bg-slate-50' : ''}`}>{n >= 1 && n <= count && <><p className="mb-1 text-xs font-semibold">{n}</p>{appointments.filter(a => a.date === date && a.status !== 'cancelled').map(a => { const v = visits.find(v => v.id === a.case_id); return v && <button key={a.id} onClick={() => open(v.id)} className="mb-1 block w-full rounded bg-indigo-50 p-1.5 text-left text-xs text-indigo-800"><strong>{a.start_time.slice(0,5)} · {v.customer_name}</strong><span className="block">{v.locality} · {visitStatuses[a.status]}</span></button>; })}{visits.filter(v=>v.requested_date===date && !appointments.some(a=>a.case_id===v.id)).map(v=><button key={'requested-'+v.id} onClick={()=>open(v.id)} className="mb-1 block w-full rounded bg-indigo-50 p-1.5 text-left text-xs text-indigo-800"><strong>{v.customer_name}</strong><span className="block">{v.locality} · Hora a coordinar por el instalador</span></button>)}{slots.filter(s => s.date === date && !s.cancelled).map(s => <div key={s.id} className={`mb-1 rounded p-1.5 text-xs ${s.kind === 'available' ? 'bg-emerald-50 text-emerald-800' : s.kind === 'installation' ? 'bg-amber-50 text-amber-900' : 'bg-slate-100 text-slate-600'}`}><button className="text-left" onClick={() => s.case_id && open(s.case_id)}>{s.start_time.slice(0,5)} · {s.title}</button><button aria-label={`Cancelar ${s.title}`} className="float-right px-1" onClick={async () => { if (!confirm('¿Cancelar este espacio del calendario?')) return; try { await visitsRequest('/api/visits/slot-cancel', { method:'POST', body:JSON.stringify({ id:s.id }) }); refresh(); } catch(e) { alert(e instanceof Error ? e.message : 'No se pudo cancelar.'); } }}>×</button></div>)}</>}</div>;
    })}</div></div></div>

  </section>;
}
