'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import { createAuthenticatedRequester } from '@/lib/authenticatedRequest';
import type { Origin, Purchase, Result, Setting } from '@/lib/costs/model';

interface Alert {id:string;created_at:string;data:{type:string;name:string;reason:string;before?:number;after?:number;percent?:number;components?:string[];affected?:string[]}}
interface Report {current:Result[];history:Record<string,Result[]>;settings:Setting[];alerts:Alert[];updatedAt:string|null;lastError:string|null;syncing:boolean;diagnostics:string[];purchaseCount:number;recipeBaseline:string}
const money=(n:number|null|undefined)=>n==null?'Pendiente':new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(n);
const origins:Origin[]=['Compra','Fabricación','Ensamblado','Por confirmar','No usar'];
const request=createAuthenticatedRequester(supabase);
const field='rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900';
function Chart({values}:{values:Result[]}){
  const valid=values.filter(r=>r.total!=null);if(!valid.length)return <p className="text-slate-500">Sin costos disponibles para graficar.</p>;
  const max=Math.max(...valid.map(r=>r.total!),1),min=Math.min(...valid.map(r=>r.total!)),span=max-min||max*.1;
  const x=(i:number)=>45+i*650/Math.max(values.length-1,1),y=(n:number)=>170-(n-min)*130/span;
  return <svg viewBox="0 0 740 210" role="img" aria-label="Evolución mensual del costo de reposición" className="w-full max-h-64"><text x="5" y="22" fontSize="11">{money(max)}</text><text x="5" y="184" fontSize="11">{money(min)}</text>{values.map((r,i)=><g key={r.date}>{r.total!=null&&<><circle cx={x(i)} cy={y(r.total)} r="5" fill={r.recipeEstimated?'#d97706':'#2563eb'}><title>{r.date}: {money(r.total)} · {r.coverage}{r.recipeEstimated?' · Receta estimada':''}</title></circle>{i>0&&values[i-1].total!=null&&<line x1={x(i-1)} y1={y(values[i-1].total!)} x2={x(i)} y2={y(r.total)} stroke="#2563eb" strokeWidth="2"/>}</>}<text x={x(i)} y="205" fontSize="10" textAnchor="middle">{r.date.slice(5,7)}/{r.date.slice(2,4)}</text></g>)}</svg>;
}
export default function CostsPage(){
  const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[family,setFamily]=useState('Todas'),[origin,setOrigin]=useState('Todos'),[selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState<'productos'|'alertas'|'configuracion'>('productos');
  const [setting,setSetting]=useState<Setting|null>(null),[purchases,setPurchases]=useState<Purchase[]>([]),[showUnused,setShowUnused]=useState(false),[target,setTarget]=useState(30),[selling,setSelling]=useState<number|undefined>();
  const load=useCallback(async()=>{try{setReport(await request('/api/admin/costos'));setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar costos.');}},[]);
  useEffect(()=>{void load();},[load]);
  const mutate=async(body:unknown)=>{setBusy(true);setError('');try{const result=await request('/api/admin/costos',{method:'POST',body:JSON.stringify(body)});if(result.busy)setError('Hay una actualización en curso. Volvé a consultar en unos minutos.');await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}};
  const product=report?.current?.find(p=>p.code===selected);
  useEffect(()=>{if(!product||!report)return;const existing=report.settings.filter(s=>s.code===product.code&&s.effective<=product.date).sort((a,b)=>b.effective.localeCompare(a.effective))[0];setSetting({...existing,code:product.code,effective:product.date,origin:existing?.origin||product.origin});setSelling(product.price);setTarget(existing?.margin??30);setPurchases([]);void request('/api/admin/costos?purchases='+encodeURIComponent(product.lines[0]?.code||product.code)).then(data=>setPurchases(data.purchases)).catch(e=>setError(e.message));},[selected,report]); // eslint-disable-line react-hooks/exhaustive-deps
  const filtered=useMemo(()=>(report?.current||[]).filter(p=>(showUnused||p.origin!=='No usar')&&(family==='Todas'||family===p.family)&&(origin==='Todos'||origin===p.origin)&&p.name.toLowerCase().includes(query.toLowerCase())),[report,showUnused,family,origin,query]);
  const exportCsv=()=>{const cells=[['Producto','Familia','Capacidad L','Origen','Materiales','Operación','Total','Estado','Venta','Margen %'],...filtered.map(p=>[p.name,p.family,p.capacity,p.origin,p.material,p.operations,p.total,p.coverage,p.price,p.margin])];const csv='\uFEFF'+cells.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='costos-productos.csv';a.click();URL.revokeObjectURL(url);};
  const history=selected?report?.history?.[selected]||[]:[];
  return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/admin" className="text-sm text-blue-700">← Administración</Link><h1 className="mt-2 text-3xl font-bold">Costos y rentabilidad</h1><p className="mt-1 text-slate-600">Compras, fabricación y ensamblado, con trazabilidad por fecha.</p><Link className="text-sm text-blue-700 underline" href="/admin/rentabilidad-diaria">Ver resultado diario de entregas</Link></div><button disabled={busy||report?.syncing} onClick={()=>mutate({action:'sync'})} className="rounded-lg bg-blue-700 px-4 py-3 text-white disabled:opacity-50">{busy?'Actualizando fuentes…':'Actualizar costos'}</button></div>
    {error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>}
    {report?.lastError&&<p className="rounded-lg bg-amber-50 p-3 text-amber-900">Última actualización fallida: {report.lastError}. Se conserva la última versión correcta.</p>}
    <div className="rounded-xl border bg-white p-4 text-sm text-slate-600">Última actualización: {report?.updatedAt?new Date(report.updatedAt).toLocaleString('es-AR'):'Todavía no realizada'} · {report?.current?.length||0} productos · {report?.purchaseCount||0} compras vinculadas.<br/>El total puede ser parcial si faltan gastos. El margen usa el precio de venta actual y no incluye comisiones, impuestos de venta ni financiación.</div>
    <nav className="flex gap-2" aria-label="Secciones de costos">{(['productos','alertas','configuracion'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={'rounded-lg px-4 py-2 '+(tab===t?'bg-slate-900 text-white':'bg-white border')}>{t==='productos'?'Productos':t==='alertas'?`Alertas (${report?.alerts?.length||0})`:'Reglas y fuentes'}</button>)}</nav>
    {tab==='productos'&&<><div className="flex flex-wrap gap-2"><input aria-label="Buscar producto" placeholder="Buscar producto…" className={field} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Familia" className={field} value={family} onChange={e=>setFamily(e.target.value)}><option>Todas</option>{[...new Set(report?.current?.map(p=>p.family)||[])].map(f=><option key={f}>{f}</option>)}</select><select aria-label="Origen" className={field} value={origin} onChange={e=>setOrigin(e.target.value)}><option>Todos</option>{origins.map(o=><option key={o}>{o}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={showUnused} onChange={e=>setShowUnused(e.target.checked)}/>Ver no utilizados</label><button className={field} onClick={exportCsv}>Exportar</button></div>
    <div className="max-h-[580px] overflow-auto rounded-xl border bg-white"><table className="w-full whitespace-nowrap text-sm"><thead className="sticky top-0 bg-slate-100 text-left"><tr>{['Producto','Origen','Materiales','Operación','Total','Estado','Margen actual'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{filtered.map(p=><tr key={p.code} className={'cursor-pointer border-t hover:bg-blue-50 '+(selected===p.code?'bg-blue-50':'')} onClick={()=>setSelected(p.code)}><td className="p-3"><button className="text-left font-medium text-blue-800">{p.name}</button><div className="text-xs text-slate-500">{p.family}{p.capacity?` · ${p.capacity} L`:''}</div></td><td className="p-3">{p.origin}</td><td className="p-3">{money(p.material)}</td><td className="p-3">{money(p.operations)}</td><td className="p-3 font-semibold">{money(p.total)}</td><td className="p-3"><span className={'rounded px-2 py-1 '+(p.coverage==='Completo'?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-900')}>{p.coverage}</span></td><td className="p-3">{p.margin==null?'—':p.margin.toFixed(1)+'%'}{p.coverage==='Parcial'?' *':''}</td></tr>)}</tbody></table>{!filtered.length&&<p className="p-6 text-slate-600">{report?.updatedAt?'No hay productos con estos filtros.':'Usá Actualizar costos para iniciar la primera carga.'}</p>}</div>
    {product&&setting&&<section className="space-y-5 rounded-xl border bg-white p-5"><div className="flex justify-between"><h2 className="text-xl font-semibold">{product.name}</h2><button onClick={()=>setSelected(null)}>Cerrar</button></div>
      <div className="grid gap-4 md:grid-cols-3"><div className="rounded-lg bg-blue-50 p-4"><p>Compra + etiquetas propias</p><strong>{money(product.purchase)}</strong></div><div className="rounded-lg bg-blue-50 p-4"><p>Fabricación/ensamblado + 5%</p><strong>{money(product.manufacture)}</strong></div><div className="rounded-lg bg-blue-50 p-4"><p>Total seleccionado · {product.operationBasis}</p><strong>{money(product.total)}</strong><p className="text-sm">{product.coverage}</p></div></div>
      <h3 className="font-semibold">Evolución mensual del costo de reposición</h3><p className="text-sm text-slate-600">Las compras se toman hasta cada cierre. Puntos amarillos: receta actual aplicada al pasado. Los valores sin compra utilizan una referencia sin fecha, cuando existe. La venta usada para el margen es la actual.</p><Chart values={history}/>
      <div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left">{['Cierre','Materiales','Total','Promedio compras del mes','Cantidad comprada','Estado'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{history.map(h=><tr key={h.date} className="border-t"><td className="p-2">{h.date}{h.recipeEstimated?' *':''}</td><td>{money(h.material)}</td><td>{money(h.total)}</td><td>{money(h.weightedPurchase)}</td><td>{h.purchasedQuantity}</td><td>{h.coverage}</td></tr>)}</tbody></table></div>
      <h3 className="font-semibold">Componentes y fuente del precio</h3><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left">{['Componente','Cantidad','Unidad','Costo unitario','Subtotal sin merma','Fecha del precio','Proveedor'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{product.lines.map((l,i)=><tr key={i} className="border-t"><td className="p-2">{l.name}</td><td>{l.quantity}</td><td>{l.unit}</td><td>{money(l.cost)}</td><td>{money(l.subtotal)}</td><td><button className="text-blue-700" onClick={()=>request('/api/admin/costos?purchases='+encodeURIComponent(l.code)).then(d=>setPurchases(d.purchases)).catch(e=>setError(e.message))}>{l.date||l.source}</button></td><td>{l.vendor||'—'}</td></tr>)}</tbody></table></div>
      {product.warnings.length>0&&<details><summary className="cursor-pointer text-amber-900">Observaciones ({product.warnings.length})</summary><ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{product.warnings.map(w=><li key={w}>{w}</li>)}</ul></details>}
      <details><summary className="cursor-pointer font-semibold">Historial de compras y listas del producto o componente seleccionado ({purchases.length})</summary><div className="max-h-64 overflow-auto"><table className="w-full text-sm"><thead><tr><th>Fecha</th><th>Producto</th><th>Proveedor</th><th>Cantidad</th><th>Costo unitario</th><th>Referencia</th></tr></thead><tbody>{purchases.map(p=><tr key={p.key} className="border-t"><td className="p-2">{p.date}</td><td>{p.name}</td><td>{p.vendor}</td><td>{p.kind==='Lista'?'Lista (sin compra)':p.quantity+' '+p.unit}</td><td>{money(p.cost)}</td><td>{p.source} · {p.receipt} · fila {p.row}</td></tr>)}</tbody></table></div></details>
      <h3 className="font-semibold">Origen y gastos por unidad</h3><p className="text-sm text-slate-600">Solo completá los gastos que corresponden a este producto. Cero indica que se verificó que no aplica; vacío indica que falta definirlo. En ensamblados incluí los gastos del tacho cuando se fabrica. La merma se aplica a los materiales.</p>
      <div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Origen<select className={field+' block w-full'} value={setting.origin} onChange={e=>setSetting({...setting,origin:e.target.value as Origin})}>{origins.map(o=><option key={o}>{o}</option>)}</select></label><label className="text-sm">Vigente desde<input className={field+' block w-full'} type="date" value={setting.effective} onChange={e=>setSetting({...setting,effective:e.target.value})}/></label><label className="text-sm">Tipo de dato<select className={field+' block w-full'} value={setting.basis||'Estimado'} onChange={e=>setSetting({...setting,basis:e.target.value as Setting['basis']})}>{['Medido','Asignado','Estimado'].map(b=><option key={b}>{b}</option>)}</select></label>{(['labor','gas','electricity','overhead','freight','packaging'] as const).map((key,i)=><label className="text-sm" key={key}>{['Mano de obra','Gas','Electricidad','Estructura','Flete','Embalaje'][i]}<input className={field+' block w-full'} type="number" min="0" step="0.01" placeholder="Pendiente" value={setting[key]??''} onChange={e=>setSetting({...setting,[key]:e.target.value===''?undefined:Number(e.target.value)})}/></label>)}</div><button disabled={busy} className="rounded-lg bg-blue-700 px-4 py-2 text-white disabled:opacity-50" onClick={()=>mutate({action:'setting',setting:{...setting,basis:setting.basis||'Estimado'}})}>Guardar y recalcular</button>
      <h3 className="font-semibold">Simular precio y margen</h3><div className="flex flex-wrap gap-4"><label className="text-sm">Venta<input className={field+' block'} type="number" min="0" value={selling??''} onChange={e=>setSelling(Number(e.target.value))}/></label><label className="text-sm">Margen objetivo %<input className={field+' block'} type="number" min="0" max="95" value={target} onChange={e=>setTarget(Math.min(95,Math.max(0,Number(e.target.value))))}/></label><div>Margen: <strong>{product.total!=null&&selling&&selling>0?((selling-product.total)/selling*100).toFixed(1)+'%':'Pendiente'}</strong><br/>Precio orientativo: <strong>{product.total!=null?money(product.total/(1-target/100)):'Pendiente'}</strong>{product.coverage!=='Completo'&&<p className="text-sm text-amber-800">Estimación con costos incompletos.</p>}</div></div><p className="text-sm text-slate-600">Esta simulación no modifica los precios de venta. Compará importes con el mismo tratamiento de IVA.</p>
    </section>}</>}
    {tab==='alertas'&&<div className="space-y-3">{report?.alerts?.map(a=><article key={a.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between gap-4"><div><p className="text-xs uppercase text-amber-800">{a.data.type}</p><h2 className="font-semibold">{a.data.name}</h2><p className="text-sm">{a.data.reason}</p>{a.data.before!=null&&<p>{money(a.data.before)} → {money(a.data.after)} ({a.data.percent?.toFixed(1)}%)</p>}{a.data.components?.length&&<p className="text-sm">Cambios: {a.data.components.join(', ')}</p>}{a.data.affected?.length&&<p className="text-sm">Afecta: {a.data.affected.join(', ')}</p>}</div><button disabled={busy} className={field+' h-fit'} onClick={()=>mutate({action:'acknowledge',id:a.id})}>Revisada</button></div></article>)}{!report?.alerts?.length&&<p>Sin alertas pendientes.</p>}</div>}
    {tab==='configuracion'&&<section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Reglas del cálculo</h2><ul className="list-disc space-y-2 pl-5 text-sm"><li>Precio válido más reciente entre compras y listas vigentes de BDCosto; se excluyen notas de crédito, cantidades/precios inválidos y fechas futuras.</li><li>Polietileno de Centuma, Victech y Mundileno: precio por kg. Recuperado negro y negro económico tienen el mismo uso.</li><li>5% sobre los materiales de fabricación o ensamblado, una sola vez. Compra de producto terminado: sin merma.</li><li>Caños de 4 m: costo de cada corte = longitud / 400 cm.</li><li>Recetas versionadas desde {report?.recipeBaseline||'la primera actualización'}. Antes de esa fecha, el histórico de recetas es estimado.</li><li>El promedio de compras usa cantidad × costo y no representa costo de existencias.</li><li>Los costos guardados en ventas anteriores no se modifican.</li></ul><h3 className="font-semibold">Alertas configurables</h3><AlertSettings settings={report?.settings||[]} busy={busy} save={s=>mutate({action:'setting',setting:s})}/><h3 className="font-semibold">Fuentes</h3><a className="text-sm text-blue-700 underline" href="https://docs.google.com/spreadsheets/d/1q5m7T0pqlYBj9imWyTkJf5fus2eVyPtTLc74cp0Nul0/edit#gid=39870918" target="_blank" rel="noreferrer">BDCosto: listas vigentes de proveedores</a><p className="text-sm"><a className="text-blue-700" href="https://docs.google.com/spreadsheets/d/1BeNJYToBmeC1yOMNrYxH1I0Th7lTQTMdRhl1HmMhTds/edit" target="_blank" rel="noreferrer">Recetas desglosadas</a> · <a className="text-blue-700" href="https://docs.google.com/spreadsheets/d/1SeQuds8IXRDteHuO_w2FPzbqvpFVf55G6cMo8J7o3nc/edit" target="_blank" rel="noreferrer">Orígenes y componentes</a> · <a className="text-blue-700" href="https://docs.google.com/spreadsheets/d/1orAhg5O_8AHeFihgeXvT512TvokQmf3qDQWQAVVjpNk/edit" target="_blank" rel="noreferrer">Conciliación de compras</a> · <Link className="text-blue-700" href="/admin/gas-consumo">Gastos de fábrica</Link> · <Link className="text-blue-700" href="/admin/rentabilidad-diaria">Resultado diario de entregas</Link></p>{report?.diagnostics?.map(d=><p key={d} className="text-sm text-amber-800">{d}</p>)}</section>}
  </div></main>;
}
function AlertSettings({settings,busy,save}:{settings:Setting[];busy:boolean;save:(s:Setting)=>void}) {
  const [s,setS]=useState<Setting>(()=>settings.filter(s=>s.code==='GLOBAL').sort((a,b)=>b.effective.localeCompare(a.effective))[0]||{code:'GLOBAL',effective:new Date().toLocaleDateString('en-CA'),inputThreshold:10,productThreshold:5,minimumImpact:1000,staleDays:90});
  return <div><div className="grid gap-3 sm:grid-cols-4">{(['inputThreshold','productThreshold','minimumImpact','staleDays'] as const).map((key,i)=><label className="text-sm" key={key}>{['Cambio insumo %','Cambio producto %','Impacto mínimo $','Compra antigua: días'][i]}<input className={field+' block w-full'} type="number" min="0" value={s[key]??''} onChange={e=>setS({...s,[key]:Number(e.target.value)})}/></label>)}</div><button disabled={busy} className={field+' mt-3'} onClick={()=>save({...s,effective:new Date().toLocaleDateString('en-CA')})}>Guardar umbrales</button></div>;
}
