'use client';
import { useState } from 'react';
import Link from 'next/link';
import ReportDateRangePicker, { displayReportDate } from '@/components/ui/ReportDateRangePicker';
import { supabase } from '@/lib/supabase';
import { createAuthenticatedRequester } from '@/lib/authenticatedRequest';
import { today } from '@/lib/costs/model';
import type { dailyTotals, orderMargin } from '@/lib/costs/dailyMargin';
const request=createAuthenticatedRequester(supabase);
type Report={updatedAt:string;notice:string;missingDate:number;conflicts:{code:string;dates:string[]}[];exclusions:{id:string;code:string;reason:string;scope:string}[];orders:ReturnType<typeof orderMargin>[];days:ReturnType<typeof dailyTotals>};
const money=(value:number|null)=>value==null?'Pendiente':new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(value);
const field='rounded border border-slate-300 bg-white p-2 text-slate-900';
export default function DailyMarginPage(){
  const [from,setFrom]=useState(today().slice(0,7)+'-01'),[to,setTo]=useState(today()),[mode,setMode]=useState('historical'),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[exclusionSearch,setExclusionSearch]=useState(''),[exclusionLimit,setExclusionLimit]=useState(100);
  const load=async()=>{setBusy(true);setError('');try{setReport(await request(`/api/admin/rentabilidad-diaria?from=${from}&to=${to}&mode=${mode}`));}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar.');}finally{setBusy(false);}};
  const exportCsv=()=>{if(!report)return;const rows=[['Fecha real','Pedido','Ventas productos','Flete cobrado incluido','Recargos incluidos (financiación sin descontar)','Costo materiales / compra / instalación','Ganancia del pedido','Gastos fabricación referencia (no descontados)','Estado','Motivo / aclaración'],...report.orders.map(o=>[displayReportDate(o.day),o.code,o.sales,o.freightCharged,o.surchargesCharged,o.cost??'',o.margin??'',o.operationsReference??'',o.status,[...o.reasons,...o.lines.flatMap(l=>l.warnings)].join(' · ')])];rows.push(...report.exclusions.map(e=>['',e.code,'','','','','','','Excluido',e.reason+' · '+e.scope]));const csv='\ufeff'+rows.map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`margen-entregas-${from}-${to}.csv`;a.click();URL.revokeObjectURL(url);};
  const shown=report?.orders.filter(o=>!selected||o.day===selected)||[];
  const excluded=report?.exclusions.filter(e=>(e.code+' '+e.reason).toLowerCase().includes(exclusionSearch.toLowerCase()))||[];
  return <main className="mx-auto w-full min-w-0 max-w-7xl space-y-5 p-3 sm:p-6 text-slate-900"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Resultado diario de pedidos entregados</h1><p className="text-slate-600">Agrupado por fecha real de entrega. Cada pedido se cuenta una vez.</p></div><Link href="/admin/costos" className="text-blue-700 underline">Costos de productos</Link></div>
    <div className="flex flex-wrap items-end gap-3"><ReportDateRangePicker from={from} to={to} onChange={(start,end)=>{setFrom(start);setTo(end);setSelected('');}}/><label>Costo a comparar<br/><select value={mode} onChange={e=>setMode(e.target.value)} className={field}><option value="historical">Materiales actuales + referencia histórica</option><option value="replacement">Materiales / compra actuales</option></select></label><button disabled={busy} onClick={()=>void load()} className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50">{busy?'Calculando…':'Consultar'}</button>{report&&<button onClick={exportCsv} className={field}>Exportar pedidos</button>}</div>
    {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
    {report&&<><div className="rounded border border-blue-200 bg-blue-50 p-4"><p className="font-semibold">Cómo se calcula la ganancia del pedido</p><p>{report.notice}</p><p className="mt-2">Los descuentos comerciales reducen las ventas y tienen costo cero. Los servicios de instalación se descuentan con su costo registrado, además de los materiales.</p><details className="mt-2 text-sm"><summary className="cursor-pointer">Referencias y alcance del cálculo</summary><p>Los gastos de fabricación, reparto, comisiones, financiación e impuestos no se descuentan en esta vista. El IVA todavía requiere conciliación entre ventas y costos. Se compara el pedido entregado, aunque su cobro pueda estar pendiente; esta ganancia no representa el resultado neto de la empresa.</p></details></div><p className="text-sm text-slate-600">Costos actualizados: {new Date(report.updatedAt).toLocaleString('es-AR')}. {report.missingDate} pedidos sin fecha real quedan fuera porque no se pueden asignar a un día. El detalle de exclusiones identifica cada pedido y el motivo.</p>
      <div className="overflow-x-auto rounded border"><table className="w-full text-sm"><thead className="bg-slate-100 text-left"><tr>{['Día','Pedidos','Ventas productos','Flete cobrado (incluido)','Recargos (incluidos)','Ganancia calculable','Fabricación: referencia sin descontar','Sin cálculo / Estimados'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{report.days.map(d=><tr key={d.day} className="border-t"><td className="p-3"><button className="text-blue-700 underline" onClick={()=>setSelected(selected===d.day?'':d.day)}>{displayReportDate(d.day)}</button></td><td>{d.orders}</td><td>{money(d.sales)}</td><td>{money(d.freightCharged)}</td><td>{money(d.surchargesCharged)}</td><td>{money(d.margin)}{d.missing>0&&<span className="ml-2 text-amber-700">{d.missing} sin resultado conciliado; ver motivos por pedido</span>}</td><td>{money(d.operationsReference)}</td><td>{d.missing} / {d.partial}</td></tr>)}</tbody></table>{!report.days.length&&<p className="p-4">Sin entregas con fecha real en este período.</p>}</div>
      {selected&&<button className="text-blue-700 underline" onClick={()=>setSelected('')}>Ver todos los días</button>}
      <div className="space-y-2">{shown.map(o=><details key={o.id} className="min-w-0 rounded border p-3"><summary className="cursor-pointer">{displayReportDate(o.day)} · Pedido {o.code} · Ventas {money(o.sales)} · Flete incluido {money(o.freightCharged)} · {o.exchange?'Costo de reposición (referencia)':'Costo descontado'} {money(o.cost)} · Ganancia {money(o.margin)} (incluye recargos {money(o.surchargesCharged)}) · {o.status}{o.reasons.length>0&&<span className="block text-amber-700">Sin ganancia calculable: {o.reasons.join(' · ')}</span>}</summary>{o.exchange&&<p className="mt-2 text-sm text-amber-700">Cambio: los importes heredados ({money(o.recordedSales)} de productos y {money(o.recordedFreight)} de flete y {money(o.recordedSurcharges)} de recargos) quedan solo como referencia; no son ingresos nuevos confirmados.</p>}<p className="mt-2 text-sm">Total registrado del pedido {money(o.total)} · Flete cobrado {money(o.freightCharged)}, sumado íntegramente a la ganancia. Recargos registrados {money(o.surchargesCharged)}, incluidos en la ganancia; costos de financiación pendientes de incorporar.</p><p className="text-sm text-slate-600">Gastos de fabricación de referencia: {money(o.operationsReference)}; no descontados.{o.operationsPending&&' Referencia incompleta: hay gastos de operación pendientes de definir.'}</p><p className="mt-3 text-xs text-slate-500 sm:hidden">Deslizá la tabla para ver todos los costos →</p><div className="mt-2 max-w-full overflow-x-auto" role="region" aria-label="Detalle de costos del pedido" tabIndex={0}><table className="w-full min-w-[900px] text-left text-sm"><thead><tr>{['Producto','Cantidad','Costo unitario descontado','Costo total','Fabricación: referencia por unidad','Histórico guardado: referencia por unidad','Origen y motivo'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{o.lines.map((l,i)=><tr key={i} className="border-t"><td className="p-2">{l.name}</td><td>{l.quantity}</td><td>{money(l.unitCost)}</td><td>{money(l.cost)}</td><td>{money(l.operationsReference)}{l.operationsPending&&' (incompleto)'}</td><td>{money(l.historicalCostReference)}</td><td>{l.source}{l.warnings.length>0&&<p className="text-xs text-amber-700">{l.warnings.join(' · ')}</p>}</td></tr>)}</tbody></table></div></details>)}</div>
      <details className="rounded border p-3"><summary className="cursor-pointer font-semibold">Pedidos excluidos y motivos ({report.exclusions.length})</summary><p className="my-2 text-sm text-slate-600">Los pedidos sin fecha real corresponden a toda la base: no se puede determinar si pertenecen al período elegido. Los cancelados y las fechas contradictorias corresponden al período seleccionado. Los pedidos sin costo permanecen arriba, pero no suman ganancia calculable.</p><input className={field} aria-label="Buscar exclusiones" placeholder="Buscar pedido o motivo" value={exclusionSearch} onChange={e=>{setExclusionSearch(e.target.value);setExclusionLimit(100);}}/><table className="mt-3 w-full text-left text-sm"><thead><tr><th>Pedido</th><th>Motivo</th><th>Alcance</th></tr></thead><tbody>{excluded.slice(0,exclusionLimit).map(e=><tr className="border-t" key={e.id}><td className="p-2">{e.code}</td><td>{e.reason}</td><td>{e.scope}</td></tr>)}</tbody></table>{excluded.length>exclusionLimit&&<button className="mt-2 text-blue-700 underline" onClick={()=>setExclusionLimit(n=>n+100)}>Mostrar 100 más ({excluded.length-exclusionLimit} pendientes)</button>}{!excluded.length&&<p className="p-2">Sin exclusiones que coincidan.</p>}</details>
    </>}
  </main>;
}
