'use client';
import {useEffect,useState} from 'react';
import {createAuthenticatedRequester} from '@/lib/authenticatedRequest';
import {supabase} from '@/lib/supabase';
import type {StatementAccount} from '@/lib/bankStatements/model';
import type {StatementOrderContext} from '@/lib/bankStatements/orderServer';
const api=createAuthenticatedRequester(supabase),endpoint='/api/admin/bank-statements';
export default function InboxAccountSetup({accounts,context,onPrepared}:{accounts:StatementAccount[];context:StatementOrderContext;onPrepared:()=>Promise<void>}){
 const mapped=accounts.filter(a=>context.mappings.some(m=>m.financial_account_id===a.id));
 const [selected,setSelected]=useState<string[]>([]),[ready,setReady]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let live=true;api(endpoint+'?action=inbox-accounts').then(data=>{if(!live)return;const configured=((data.ready||[]) as string[]).filter(id=>mapped.some(a=>a.id===id));setReady(configured);setSelected(mapped.filter(a=>!configured.includes(a.id)).map(a=>a.id));}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[accounts,context]);
 async function prepare(){setBusy(true);setError('');setNotice('');try{const data=await api(endpoint,{method:'POST',body:JSON.stringify({action:'inbox-initialize',accounts:selected})});const successes=data.results.filter((r:{ready:boolean})=>r.ready).map((r:{account:string})=>r.account);setReady(previous=>[...new Set([...previous,...successes])]);setSelected(previous=>previous.filter(id=>!successes.includes(id)));const failed=data.results.filter((r:{ready:boolean})=>!r.ready);if(successes.length)setNotice(successes.length+' '+(successes.length===1?'cuenta preparada':'cuentas preparadas'));if(failed.length)setError(failed.map((r:{account:string;error:string})=>(accounts.find(a=>a.id===r.account)?.name||'Cuenta')+': '+r.error).join(' · '));await onPrepared();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="rounded-2xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">Preparar cuentas <span className="ml-2 font-normal text-slate-400">{ready.length}/{mapped.length} listas</span></summary><div className="mt-4 flex flex-wrap gap-3">{mapped.map(a=>{const mapping=context.mappings.find(m=>m.financial_account_id===a.id);const alias=context.accounts.find(m=>m.id===mapping?.mp_account_id);return <label key={a.id} className="flex min-w-52 flex-1 cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" aria-label={'Preparar '+a.name} checked={selected.includes(a.id)} disabled={busy} onChange={e=>setSelected(previous=>e.target.checked?[...previous,a.id]:previous.filter(id=>id!==a.id))}/><span className="flex-1 text-sm font-medium">{a.name}<small className="block font-normal text-slate-500">{alias?.alias||alias?.name}</small></span><span className={'text-xs '+(ready.includes(a.id)?'text-emerald-700':'text-amber-700')}>{ready.includes(a.id)?'Lista':'Sin preparar'}</span></label>;})}</div><div className="mt-3 flex flex-wrap items-center gap-3"><button type="button" disabled={busy||!selected.length} onClick={()=>void prepare()} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-40">{busy?'Preparando…':'Preparar selección ('+selected.length+')'}</button><span className="text-xs text-slate-500">Clasifica y vincula. No registra movimientos.</span></div>{notice&&<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>}{error&&<p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}{!mapped.length&&<p className="mt-3 text-sm text-slate-500">Asociá las cuentas en Configuración.</p>}</details>;
}
