'use client';
import StatementDateInput from './StatementDateInput';
import {useEffect,useState} from 'react';
import SearchableSelect from '@/components/ui/SearchableSelect';
import {createAuthenticatedRequester} from '@/lib/authenticatedRequest';
import {supabase} from '@/lib/supabase';
import type {StatementEntry} from '@/lib/bankStatements/model';
import type {StatementOrder} from '@/lib/bankStatements/orderLinks';
const api=createAuthenticatedRequester(supabase),endpoint='/api/admin/bank-statements';
const control='rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm disabled:opacity-50';
export default function StatementOrderLinkPanel({batch,entry,available,accountAlias,onSaved}:{batch:string;entry:StatementEntry;available:boolean;accountAlias?:string;onSaved:()=>Promise<void>}) {
 const [day,setDay]=useState(entry.effective_date),[orders,setOrders]=useState<StatementOrder[]>([]),[results,setResults]=useState<StatementOrder[]>([]),[query,setQuery]=useState(''),[chosen,setChosen]=useState<StatementOrder|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false);
 useEffect(()=>{if(!available)return;let live=true;setLoading(true);setOrders([]);setChosen(null);api(`${endpoint}?batch=${batch}&action=orders&entry=${entry.id}&day=${day}`).then(value=>{if(live)setOrders((value as {orders:StatementOrder[]}).orders);}).catch(cause=>{if(live){setOrders([]);setError(cause.message);}}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[available,batch,entry.id,entry.order_link_version,day]);
 const run=async(work:()=>Promise<void>)=>{setBusy(true);setError('');try{await work();}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo vincular');}finally{setBusy(false);}};
 const save=(order:StatementOrder|null)=>run(async()=>{await api(endpoint,{method:'POST',body:JSON.stringify({action:'order-link',batch,entry:entry.id,order:order?.id||null,payment:order?.payment_id||null,version:entry.order_link_version||0})});setChosen(null);await onSaved();});
 const search=()=>run(async()=>{const value=await api(`${endpoint}?batch=${batch}&action=orders&entry=${entry.id}&q=${encodeURIComponent(query.trim())}`) as {orders:StatementOrder[]};setResults(value.orders);setSearched(true);});
 return <section className="my-4 rounded-xl border bg-slate-50 p-3"><h3 className="font-semibold">Pedido de la cobranza</h3>{!available?<p className="mt-2 text-sm text-amber-800">Requiere habilitar la migración v171.</p>:<>
 {entry.order_link?<div className="my-2 text-sm"><strong>{entry.order_link.code}</strong> · {entry.order_link.kind==='automatic'?'Vinculado automáticamente':'Vinculado manualmente'}{entry.order_link.stale&&<p className="mt-1 text-amber-800">La relación en Chequeo de Pagos cambió. Revisá el vínculo.</p>}<button className={`${control} mt-2`} disabled={busy} onClick={()=>save(null)}>Quitar vínculo con pedido</button></div>:<p className="mt-2 text-sm text-amber-800">Pendiente de vinculación. No hubo una coincidencia inequívoca o requiere revisión manual.</p>}
 <label className="mt-3 block text-xs">Día para pedidos pendientes<StatementDateInput label="Día de pedidos pendientes" className={`${control} ml-2`} disabled={busy} value={day} onChange={value=>{if(value)setDay(value);}}/></label>
 <div className="mt-3"><SearchableSelect label="Pedidos pendientes del día" options={orders.map(order=>({value:order.id,label:order.code+' · '+(order.customer||'Sin cliente')+(order.payment_amount?' · Cobro '+order.payment_amount:'')}))} disabled={busy||loading} value={chosen&&orders.some(order=>order.id===chosen.id)?chosen.id:''} onChange={value=>setChosen(orders.find(order=>order.id===value)||null)} placeholder={loading?'Buscando pendientes…':'Escribí código, cliente o importe'} /></div>
 <p className="mt-1 text-xs text-slate-500">Sólo cobros pendientes del día seleccionado en {accountAlias||'la cuenta asociada de Chequeo de Pagos'}.</p>{!loading&&!orders.length&&<p className="mt-1 text-xs text-slate-500">No hay pedidos pendientes en ese día y cuenta. Podés buscar otro código.</p>}
 <div className="mt-3 flex gap-2"><input className={`${control} min-w-0 flex-1`} aria-label="Buscar otros códigos de pedido" placeholder="Código de pedido, sin límite de fecha" maxLength={80} value={query} onChange={event=>{setQuery(event.target.value);setSearched(false);setResults([]);}} onKeyDown={event=>{if(event.key==='Enter'&&query.trim().length>=2&&!busy)search();}}/><button className={control} disabled={busy||query.trim().length<2} onClick={search}>Buscar códigos</button></div>
 {results.length>0&&<label className="mt-2 block text-xs">Resultados fuera del filtro del día<select className={`${control} mt-1 w-full`} aria-label="Resultados de búsqueda de pedidos" disabled={busy} value={chosen&&results.some(order=>order.id===chosen.id)?chosen.id:''} onChange={event=>setChosen(results.find(order=>order.id===event.target.value)||null)}><option value="">Seleccionar código encontrado</option>{results.map(order=><option key={order.id} value={order.id}>{order.code} · {order.customer||'Sin cliente'} · {order.order_date?order.order_date.slice(8,10)+'/'+order.order_date.slice(5,7)+'/'+order.order_date.slice(0,4):'Sin fecha'}</option>)}</select></label>}{searched&&!results.length&&<p className="mt-2 text-xs">No se encontraron códigos.</p>}
 {chosen&&<p className="mt-2 text-sm">Vincular con <strong>{chosen.code}</strong></p>}<button className={`${control} mt-3 font-semibold`} disabled={busy||!chosen} onClick={()=>save(chosen)}>Vincular pedido seleccionado</button>
 <p className="mt-2 text-xs text-slate-500">Asocia el pedido con esta cobranza. No registra otro cobro ni modifica el saldo del pedido.</p>{error&&<p role="alert" className="mt-2 text-sm text-rose-700">{error}</p>}
 </>}</section>;
}
