'use client';
import { useState } from 'react';
import type { StatementAccount } from '@/lib/bankStatements/model';
import type { StatementFileAccount } from '@/lib/bankStatements/fileAccounts';
type Props = {accounts:StatementAccount[]; mappings:StatementFileAccount[]; busy:boolean; save:(identifier:string,account:string,version?:number,remove?:boolean)=>Promise<boolean>};
const control='rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm disabled:opacity-50';
function MappingRow({mapping,accounts,busy,save}:Omit<Props,'mappings'> & {mapping:StatementFileAccount}) {
 const [account,setAccount]=useState(mapping.financial_account_id);
 return <tr className="border-t"><td className="p-2 font-mono text-sm">{mapping.external_account_id}</td><td className="p-2"><select className={control} aria-label={`Cuenta del identificador ${mapping.external_account_id}`} value={account} disabled={busy} onChange={event=>setAccount(event.target.value)}><option value="">Seleccionar cuenta</option>{!accounts.some(item=>item.id===mapping.financial_account_id)&&<option value={mapping.financial_account_id}>Cuenta no disponible</option>}{accounts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></td><td className="flex gap-2 p-2"><button className={control} disabled={busy||!account||account===mapping.financial_account_id} onClick={()=>save(mapping.external_account_id,account,mapping.version)}>Guardar</button><button className={control} disabled={busy} onClick={()=>save(mapping.external_account_id,account,mapping.version,true)}>Quitar</button></td></tr>;
}
export default function StatementFileAccountSettings({accounts,mappings,busy,save}:Props) {
 const [identifier,setIdentifier]=useState(''),[account,setAccount]=useState('');
 return <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Configurar cuentas por identificador del archivo</summary><p className="my-3 text-sm text-slate-500">Asociá el identificador del archivo a su cuenta.</p><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th className="p-2 text-xs">Identificador del archivo</th><th className="p-2 text-xs">Cuenta ERP</th><th className="p-2 text-xs">Acciones</th></tr></thead><tbody>{mappings.map(mapping=><MappingRow key={`${mapping.external_account_id}:${mapping.version}`} mapping={mapping} accounts={accounts} busy={busy} save={save}/>)}</tbody></table></div><div className="mt-3 flex flex-wrap gap-2"><input className={control} aria-label="Nuevo identificador de cuenta" inputMode="numeric" maxLength={30} placeholder="Ej.: 3168927031" value={identifier} disabled={busy} onChange={event=>setIdentifier(event.target.value)}/><select className={control} aria-label="Cuenta para nueva asociación" value={account} disabled={busy} onChange={event=>setAccount(event.target.value)}><option value="">Seleccionar cuenta</option>{accounts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className={control} disabled={busy||!/^\d{1,30}$/.test(identifier)||!account||mappings.some(mapping=>mapping.external_account_id===identifier)} onClick={async()=>{if(await save(identifier,account)){setIdentifier('');setAccount('');}}}>Agregar asociación</button></div></details>;
}
