begin;

create table if not exists public.sales_quotes (
  id uuid primary key default gen_random_uuid(),
  sequence_no bigint generated by default as identity unique,
  quote_number text unique,
  seller_id uuid not null references public.sellers(id),
  client_id uuid references public.clients(id) on delete set null,
  channel text not null check (channel in ('minorista', 'mayorista')),
  status text not null default 'draft'
    check (status in ('draft', 'sent', 'follow_up', 'accepted', 'rejected', 'expired', 'converted')),
  customer_name text,
  customer_phone text,
  subtotal numeric not null default 0,
  discount_type text check (discount_type is null or discount_type in ('percentage', 'fixed')),
  discount_value numeric not null default 0,
  discount_amount numeric not null default 0,
  freight_amount numeric not null default 0,
  tax_amount numeric not null default 0,
  total_amount numeric not null default 0,
  payment_method_id uuid references public.payment_methods(id) on delete set null,
  commercial_conditions jsonb not null default '{}'::jsonb,
  notes text,
  valid_until date,
  sent_at timestamptz,
  accepted_at timestamptz,
  rejected_at timestamptz,
  converted_at timestamptz,
  converted_order_id uuid references public.orders(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales_quote_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.sales_quotes(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  sku text,
  variant text,
  quantity numeric not null check (quantity > 0),
  list_unit_price numeric not null default 0,
  unit_price numeric not null default 0,
  discount_percentage numeric not null default 0,
  subtotal numeric not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.sales_quote_followups (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.sales_quotes(id) on delete cascade,
  created_by uuid references public.sellers(id) on delete set null,
  note text not null,
  next_follow_up_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.orders
  add column if not exists quote_id uuid references public.sales_quotes(id) on delete set null;

create or replace function public.set_sales_quote_defaults() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  if new.quote_number is null or trim(new.quote_number) = '' then
    new.quote_number := case when new.channel = 'mayorista' then 'PM-' else 'PR-' end
      || lpad(new.sequence_no::text, 6, '0');
  end if;
  new.updated_at := now();
  if new.status = 'sent' and new.sent_at is null then new.sent_at := now(); end if;
  if new.status = 'accepted' and new.accepted_at is null then new.accepted_at := now(); end if;
  if new.status = 'rejected' and new.rejected_at is null then new.rejected_at := now(); end if;
  if new.status = 'converted' and new.converted_at is null then new.converted_at := now(); end if;
  return new;
end $$;

drop trigger if exists set_sales_quote_defaults_trigger on public.sales_quotes;
create trigger set_sales_quote_defaults_trigger
  before insert or update on public.sales_quotes
  for each row execute function public.set_sales_quote_defaults();

create index if not exists idx_sales_quotes_seller_created on public.sales_quotes(seller_id, created_at desc);
create index if not exists idx_sales_quotes_channel_status on public.sales_quotes(channel, status, created_at desc);
create index if not exists idx_sales_quotes_followup on public.sales_quotes(status, valid_until);
create index if not exists idx_sales_quote_items_quote on public.sales_quote_items(quote_id, sort_order);
create index if not exists idx_orders_quote_id on public.orders(quote_id) where quote_id is not null;

alter table public.sales_quotes enable row level security;
alter table public.sales_quote_items enable row level security;
alter table public.sales_quote_followups enable row level security;

drop policy if exists sales_quotes_read on public.sales_quotes;
create policy sales_quotes_read on public.sales_quotes for select to authenticated
  using (seller_id = auth.uid() or public.is_admin());
drop policy if exists sales_quotes_insert on public.sales_quotes;
create policy sales_quotes_insert on public.sales_quotes for insert to authenticated
  with check (seller_id = auth.uid() or public.is_admin());
drop policy if exists sales_quotes_update on public.sales_quotes;
create policy sales_quotes_update on public.sales_quotes for update to authenticated
  using (seller_id = auth.uid() or public.is_admin())
  with check (seller_id = auth.uid() or public.is_admin());
drop policy if exists sales_quotes_delete on public.sales_quotes;
create policy sales_quotes_delete on public.sales_quotes for delete to authenticated
  using (seller_id = auth.uid() or public.is_admin());

drop policy if exists sales_quote_items_access on public.sales_quote_items;
create policy sales_quote_items_access on public.sales_quote_items for all to authenticated
  using (exists (select 1 from public.sales_quotes q where q.id = quote_id and (q.seller_id = auth.uid() or public.is_admin())))
  with check (exists (select 1 from public.sales_quotes q where q.id = quote_id and (q.seller_id = auth.uid() or public.is_admin())));

drop policy if exists sales_quote_followups_access on public.sales_quote_followups;
create policy sales_quote_followups_access on public.sales_quote_followups for all to authenticated
  using (exists (select 1 from public.sales_quotes q where q.id = quote_id and (q.seller_id = auth.uid() or public.is_admin())))
  with check (exists (select 1 from public.sales_quotes q where q.id = quote_id and (q.seller_id = auth.uid() or public.is_admin())));

grant select, insert, update, delete on public.sales_quotes to authenticated;
grant select, insert, update, delete on public.sales_quote_items to authenticated;
grant select, insert, update, delete on public.sales_quote_followups to authenticated;
grant usage, select on sequence public.sales_quotes_sequence_no_seq to authenticated;

notify pgrst, 'reload schema';
commit;
