-- V73: clasificación mayorista, referencias históricas y descuentos como ajuste del pedido.

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS order_discount_type TEXT
    CHECK (order_discount_type IS NULL OR order_discount_type IN ('fixed', 'percentage')),
  ADD COLUMN IF NOT EXISTS order_discount_value NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS order_discount_amount NUMERIC NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.wholesale_list_references (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL UNIQUE,
  legacy_ordinal INTEGER NOT NULL UNIQUE,
  customer_segment TEXT NOT NULL CHECK (customer_segment IN ('Mayorista', 'Particular', 'Mixta')),
  list_number INTEGER,
  is_before_list_12 BOOLEAN NOT NULL DEFAULT false,
  source TEXT NOT NULL DEFAULT 'Mayorista - Pedidos / RefListas',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

INSERT INTO public.wholesale_list_references
  (label, legacy_ordinal, customer_segment, list_number, is_before_list_12)
VALUES
  ('37', 2, 'Mixta', NULL, true),
  ('38', 3, 'Mixta', NULL, true),
  ('39', 4, 'Mixta', NULL, true),
  ('40', 5, 'Mixta', NULL, true),
  ('PART 01.22', 6, 'Particular', NULL, true),
  ('MAYOR 01.22', 7, 'Mayorista', NULL, true),
  ('PART 02.22', 8, 'Particular', NULL, true),
  ('MAYOR 02.22', 9, 'Mayorista', NULL, true),
  ('PART 03.22', 10, 'Particular', NULL, true),
  ('MAYOR 03.22', 11, 'Mayorista', NULL, true),
  ('PART 04.22', 12, 'Particular', NULL, true),
  ('MAYOR 04.22', 13, 'Mayorista', NULL, true),
  ('L5 PARTICULAR', 14, 'Particular', 5, true),
  ('L5 MAYORISTA', 15, 'Mayorista', 5, true),
  ('L6 PARTICULAR', 16, 'Particular', 6, true),
  ('L6 MAYORISTA', 17, 'Mayorista', 6, true),
  ('L7 PARTICULAR', 18, 'Particular', 7, true),
  ('L7 MAYORISTA', 19, 'Mayorista', 7, true),
  ('L8 PARTICULAR', 20, 'Particular', 8, true),
  ('L8 MAYORISTA', 21, 'Mayorista', 8, true),
  ('L9 PARTICULAR', 22, 'Particular', 9, true),
  ('L9 MAYORISTA', 23, 'Mayorista', 9, true),
  ('L10 PARTICULAR', 24, 'Particular', 10, true),
  ('L10 MAYORISTA', 25, 'Mayorista', 10, true),
  ('L11 PARTICULAR', 26, 'Particular', 11, true),
  ('L11 MAYORISTA', 27, 'Mayorista', 11, true),
  ('L12 PARTICULAR', 28, 'Particular', 12, false),
  ('L12 MAYORISTA', 29, 'Mayorista', 12, false)
ON CONFLICT (label) DO UPDATE SET
  legacy_ordinal = EXCLUDED.legacy_ordinal,
  customer_segment = EXCLUDED.customer_segment,
  list_number = EXCLUDED.list_number,
  is_before_list_12 = EXCLUDED.is_before_list_12;

ALTER TABLE public.wholesale_list_references ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS wholesale_list_references_read ON public.wholesale_list_references;
CREATE POLICY wholesale_list_references_read ON public.wholesale_list_references
  FOR SELECT TO authenticated USING (true);

-- Copia recuperable de los renglones que antes representaban descuentos.
CREATE TABLE IF NOT EXISTS public.wholesale_discount_item_migration_backup (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL,
  product_id UUID,
  product_name TEXT,
  quantity NUMERIC,
  unit_price NUMERIC,
  subtotal NUMERIC,
  discount_percentage NUMERIC,
  historical_unit_cost NUMERIC,
  migrated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

INSERT INTO public.wholesale_discount_item_migration_backup
  (id, order_id, product_id, product_name, quantity, unit_price, subtotal, discount_percentage, historical_unit_cost)
SELECT id, order_id, product_id, product_name, quantity, unit_price, subtotal, discount_percentage, historical_unit_cost
FROM public.order_items
WHERE lower(COALESCE(product_name, '')) LIKE '%descuento%'
   OR lower(COALESCE(product_name, '')) LIKE '%bonificaci%'
ON CONFLICT (id) DO NOTHING;

WITH discounts AS (
  SELECT order_id,
         round(sum(abs(COALESCE(subtotal, quantity * unit_price, unit_price, 0))), 2) AS amount
  FROM public.wholesale_discount_item_migration_backup
  GROUP BY order_id
)
UPDATE public.orders o
SET order_discount_type = 'fixed',
    order_discount_value = d.amount,
    order_discount_amount = d.amount,
    totals = COALESCE(o.totals, '{}'::jsonb) || jsonb_build_object(
      'order_discount_type', 'fixed',
      'order_discount_value', d.amount,
      'order_discount_amount', d.amount
    )
FROM discounts d
WHERE o.id = d.order_id;

DELETE FROM public.order_items oi
USING public.wholesale_discount_item_migration_backup b
WHERE oi.id = b.id;

-- Facundo usa AQ-FP para ambos canales: Procedencia manda sobre el prefijo.
UPDATE public.orders o
SET channel = CASE
  WHEN lower(src.name) = 'mayorista' THEN 'mayorista'
  WHEN lower(src.name) LIKE '%orgánico%'
    OR lower(src.name) LIKE '%organico%'
    OR lower(src.name) LIKE '%cliente habitual%'
    OR lower(src.name) LIKE '%recomendado%' THEN 'web_organica'
  ELSE o.channel
END
FROM public.sellers s, public.advertising_sources src
WHERE o.seller_id = s.id
  AND o.advertising_source_id = src.id
  AND lower(s.full_name) = 'facundo paz'
  AND upper(COALESCE(o.legacy_code, '')) LIKE 'AQ-%';

-- Para el resto de los vendedores, los prefijos históricos sí identifican B2B.
UPDATE public.orders o
SET channel = 'mayorista'
WHERE (upper(COALESCE(o.legacy_code, '')) LIKE 'AQ-%'
    OR upper(COALESCE(o.legacy_code, '')) LIKE 'AQU%'
    OR upper(COALESCE(o.legacy_code, '')) LIKE 'POW%')
  AND NOT EXISTS (
    SELECT 1 FROM public.sellers s
    WHERE s.id = o.seller_id AND lower(s.full_name) = 'facundo paz'
  );

-- Vincular pedidos antiguos sin cuenta sólo cuando el nombre identifica una única cuenta.
WITH unique_clients AS (
  SELECT lower(trim(business_name)) AS normalized_name, min(id::text)::uuid AS client_id
  FROM public.clients
  WHERE business_name IS NOT NULL AND trim(business_name) <> ''
  GROUP BY lower(trim(business_name))
  HAVING count(*) = 1
)
UPDATE public.orders o
SET client_id = u.client_id
FROM unique_clients u
WHERE o.client_id IS NULL
  AND o.channel = 'mayorista'
  AND lower(trim(o.customer_name)) = u.normalized_name;

UPDATE public.clients c
SET is_wholesale = true,
    client_type = 'Mayorista'
WHERE EXISTS (
  SELECT 1 FROM public.orders o
  WHERE o.client_id = c.id AND o.channel = 'mayorista'
);

CREATE INDEX IF NOT EXISTS idx_orders_wholesale_channel_date
  ON public.orders(channel, order_date DESC);
CREATE INDEX IF NOT EXISTS idx_orders_discount_amount
  ON public.orders(order_discount_amount)
  WHERE order_discount_amount > 0;

-- La misma tabla base sirve a Logística; las pantallas trabajan con vistas por canal.
CREATE OR REPLACE VIEW public.v_wholesale_orders
WITH (security_invoker = true) AS
SELECT o.*
FROM public.orders o
WHERE o.channel = 'mayorista';

DROP VIEW IF EXISTS public.v_client_balances_and_stats CASCADE;
CREATE VIEW public.v_client_balances_and_stats
WITH (security_invoker = true) AS
WITH client_orders AS (
  SELECT client_id, COALESCE(sum(total_amount), 0) AS total_charged, count(*) AS orders_count
  FROM public.orders
  WHERE status NOT IN ('Anulado', 'Cancelado')
  GROUP BY client_id
), client_payments_sum AS (
  SELECT client_id, COALESCE(sum(amount * COALESCE(exchange_rate, 1)), 0) AS total_paid
  FROM public.client_payments
  WHERE status = 'Aprobado'
  GROUP BY client_id
)
SELECT c.*,
       COALESCE(o.total_charged, 0) AS total_charged,
       COALESCE(p.total_paid, 0) AS total_paid,
       CASE WHEN c.is_wholesale THEN COALESCE(o.total_charged, 0) - COALESCE(p.total_paid, 0) ELSE 0 END AS balance,
       COALESCE(o.orders_count, 0)::integer AS orders_count
FROM public.clients c
LEFT JOIN client_orders o ON o.client_id = c.id
LEFT JOIN client_payments_sum p ON p.client_id = c.id;

GRANT SELECT ON public.v_wholesale_orders TO authenticated;
GRANT SELECT ON public.v_client_balances_and_stats TO authenticated;
GRANT SELECT ON public.wholesale_list_references TO authenticated;
