"use client";
import {useState} from 'react';
import SelectionModal from './SelectionModal';
import OperationAttachments,{appendOperationFiles} from './OperationAttachments';
export default function MissingVoucherModal({files,onFilesChange,onClose,onSave,busy,error}:{files:File[];onFilesChange:(files:File[])=>void;onClose:()=>void;onSave:(withoutVoucher:boolean)=>void;busy:boolean;error:string}){
 const [pasteError,setPasteError]=useState('');
 const add=(incoming:File[])=>{try{onFilesChange(appendOperationFiles(files,incoming,0));setPasteError('');}catch(e){setPasteError(e instanceof Error?e.message:'No se pudo pegar el comprobante.');}};
 async function paste(){try{if(!navigator.clipboard?.read)throw new Error('Pegá el comprobante con Ctrl+V dentro de esta ventana.');const items=await navigator.clipboard.read();const incoming:File[]=[];for(const item of items){const type=item.types.find(type=>['image/png','image/jpeg','image/webp','application/pdf'].includes(type));if(type){const blob=await item.getType(type);incoming.push(new File([blob],`comprobante-pegado-${incoming.length+1}.${type==='application/pdf'?'pdf':type.split('/')[1]}`,{type}));}}if(!incoming.length)throw new Error('No hay una imagen o PDF en el portapapeles. Copiá el comprobante y pegalo con Ctrl+V.');add(incoming);}catch(e){setPasteError(e instanceof Error?e.message:'No se pudo leer el portapapeles. Podés pegar con Ctrl+V o adjuntar un archivo.');}}
 return <SelectionModal title="Pago sin comprobante" onClose={onClose} disabled={busy} onPaste={e=>{if(!busy&&e.clipboardData.files.length){e.preventDefault();add(Array.from(e.clipboardData.files));}}}><div><p className="mb-4 text-sm text-slate-700">Este pago no tiene un comprobante adjunto. ¿Querés guardarlo igual? Quedará marcado como <strong>Pendiente de comprobante</strong> en Movimientos hasta que lo cargues.</p><OperationAttachments files={files} onFilesChange={onFilesChange} ids={[]} onRemove={()=>{}} disabled={busy}/><button type="button" disabled={busy} onClick={paste} className="mt-3 rounded-lg border px-3 py-2 text-sm">Pegar comprobante</button><p className="mt-2 text-xs text-slate-500">También podés pegar una captura con Ctrl+V dentro de esta ventana.</p>{(error||pasteError)&&<p role="alert" className="mt-3 text-sm text-red-700">{error||pasteError}</p>}<div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" disabled={busy} className="rounded-lg border px-4 py-2 text-sm" onClick={onClose}>Volver al formulario</button>{files.length?<button type="button" disabled={busy} className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white" onClick={()=>onSave(false)}>{busy?'Guardando…':'Guardar con comprobante'}</button>:<button type="button" disabled={busy} className="rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white" onClick={()=>onSave(true)}>{busy?'Guardando…':'Guardar igual sin comprobante'}</button>}</div></div></SelectionModal>;
}
