"use client";
import {useEffect,useRef,useState} from 'react';
import {operationLabels,type OperationType} from '@/lib/financialOperations/types';
const descriptions:Record<OperationType,string>={supplier_payment:'Facturas, anticipos y compras a proveedor eventual.',customer_collection:'Cobros de pedidos y comprobantes existentes.',payroll_payment:'Sueldo, adelanto, eventual o acuerdo.',operating_expense:'Servicios y gastos de funcionamiento.',tax_payment:'Organismo, período y cuota.',internal_transfer:'Dinero entre cuentas de la misma moneda.',custody_fund:'Entrega, gastos rendidos, devolución y reintegro.',currency_exchange:'Dos monedas, cotización y comisión.',financing:'Capital recibido o prestado, devolución y costos.',partner_equity:'Aportes y retiros identificados por socio.',asset_trade:'Bien, contraparte y documento.',cash_count:'Conteo al corte y ajuste confirmado.',general:'Excepciones que no pertenecen a otra familia.'};
export default function OperationChooser({onChoose,onClose}:{onChoose:(kind:OperationType)=>void;onClose:()=>void}){
 const [search,setSearch]=useState('');const panel=useRef<HTMLDivElement>(null);
 useEffect(()=>{const prior=document.activeElement as HTMLElement|null;panel.current?.querySelector('input')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=Array.from(panel.current?.querySelectorAll<HTMLElement>('button,input')||[]),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prior?.focus();};},[onClose]);
 const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const rows=Object.entries(operationLabels).filter(([id,label])=>normalize(label+' '+descriptions[id as OperationType]).includes(normalize(search))).sort(([a],[b])=>a==='general'?1:b==='general'?-1:0);
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-label="Elegir familia de operación"><div ref={panel} className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white p-5 shadow-xl"><div className="mb-3 flex justify-between"><h2 className="text-xl font-semibold">¿Qué operación vas a registrar?</h2><button onClick={onClose} className="rounded border px-3 py-1">Cerrar</button></div><p className="mb-3 text-sm text-slate-600">Elegí la familia. Las variantes se completan dentro de su formulario.</p><input aria-label="Buscar tipo de operación" placeholder="Buscar por tipo o ejemplo…" value={search} onChange={e=>setSearch(e.target.value)} className="mb-4 w-full rounded-lg border p-3"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(([id,label])=><button key={id} onClick={()=>onChoose(id as OperationType)} className="rounded-xl border p-4 text-left hover:border-brand-500 hover:bg-brand-50"><span className="block font-semibold">{label}</span><span className="mt-1 block text-sm text-slate-600">{descriptions[id as OperationType]}</span></button>)}</div>{!rows.length&&<p>Sin coincidencias.</p>}</div></div>;
}
