"use client";
import {useEffect,useRef,useState} from 'react';
import AdaptiveSelect from '@/components/ui/AdaptiveSelect';
import {supabase} from '@/lib/supabase';
import {createAuthenticatedRequester} from '@/lib/authenticatedRequest';
import {treasuryToday} from '@/lib/treasuryTransactionTime';
import {operationLabels} from '@/lib/financialOperations/types';
import {buildSpecialPlan,type SpecialInput,type SpecialType,type Resources,type SpecialPlan} from '@/lib/financialOperations/specialized';
import {fieldClass} from './OperationFields';
const request=createAuthenticatedRequester(supabase);
const actions:Record<SpecialType,Array<[string,string]>>={custody_fund:[['deliver','Entregar fondo'],['expense','Rendir gasto'],['return','Devolver dinero'],['reimburse','Pagar reintegro'],['close','Cerrar fondo']],currency_exchange:[['exchange','Cambiar moneda']],financing:[['receive','Recibir préstamo'],['lend','Prestar dinero'],['repay','Devolver capital'],['collect','Cobrar capital']],partner_equity:[['contribution','Aporte de socio'],['withdrawal','Retiro de socio']],asset_trade:[['purchase','Compra de bien'],['sale','Venta de bien']],cash_count:[['record','Registrar conteo'],['adjust','Confirmar diferencia'],['opening','Apertura de cuenta sin movimientos']]};
type Props={kind:SpecialType;transactionId?:string;onClose:()=>void;onSaved:()=>void;requestOverride?:typeof request;preview?:boolean};
type History={id:string;operation_type:SpecialType;status:string;version:number;detail:{input:SpecialInput}};
export default function SpecialOperationEditor({kind,transactionId,onClose,onSaved,requestOverride,preview=false}:Props){
 const api=requestOverride||request,panel=useRef<HTMLDivElement>(null),pending=useRef<{signature:string;key:string}|null>(null);
 const [p,setP]=useState<SpecialInput>({operation_type:kind,action:actions[kind][0][0],effective_date:treasuryToday(),account_id:'',payment_method_id:'',amount:'',concept:'',fee:'0',counted:'0',cutoff:new Date().toISOString(),voucher_ids:[]});
 const [r,setR]=useState<Resources>({accounts:[],funds:[],loans:[],counts:[]}),[methods,setMethods]=useState<Array<{id:string;name:string}>>([]),[vouchers,setVouchers]=useState<Array<{id:string;reference:string|null}>>([]);
 const [available,setAvailable]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<SpecialPlan|null>(null),[cut,setCut]=useState<{balance:string;fingerprint:string;has_history:boolean}|undefined>();
 const [canWrite,setCanWrite]=useState(true);
 const [refreshingVouchers,setRefreshingVouchers]=useState(false);
 async function refreshVouchers(){setRefreshingVouchers(true);try{const latest=await api('/api/admin/financial-operations');setVouchers(latest.vouchers);}catch(e){setError(e instanceof Error?e.message:'No se pudieron actualizar los comprobantes.');}finally{setRefreshingVouchers(false);}}
 const [history,setHistory]=useState<History[]>([]),[selected,setSelected]=useState<History|null>(null),[reason,setReason]=useState('');
 const patch=(v:Partial<SpecialInput>)=>{setP(old=>({...old,...v}));setReview(null);setError('');};
 useEffect(()=>{const prior=document.activeElement as HTMLElement|null;panel.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const els=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),a[href]')||[]),first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===panel.current)){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prior?.focus();};},[onClose,busy]);
 useEffect(()=>{let active=true;(async()=>{try{const [h,o,s]=await Promise.all([api('/api/admin/finanzas-data?action=init'),api('/api/admin/financial-operations'),api('/api/admin/special-financial-operations')]);if(!active)return;setR({accounts:h.financialAccounts,funds:s.funds,loans:s.loans,counts:s.counts});setMethods(o.paymentMethods);setVouchers(o.vouchers);setAvailable(s.available);setCanWrite(s.can_write!==false);setHistory(s.operations||[]);setP(old=>({...old,account_id:h.financialAccounts.find((a:{is_active:boolean})=>a.is_active)?.id||''}));if(transactionId){const detail=await api(`/api/admin/special-financial-operations?transaction_id=${transactionId}`);if(active){setSelected(detail.operation);setP(detail.operation.detail.input);}}}catch(e){if(active)setError(e instanceof Error?e.message:'No se pudieron cargar los datos.');}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[api,transactionId]);
 useEffect(()=>{if(kind!=='cash_count'||!p.account_id)return;const count=r.counts.find(c=>c.id===p.resource_id);const cutoff=p.action==='adjust'?count?.cutoff:p.cutoff;if(!cutoff)return;let active=true;setCut(undefined);api(`/api/admin/special-financial-operations?account_id=${p.account_id}&cutoff=${encodeURIComponent(cutoff)}`).then(v=>{if(active){setCut(v);setP(old=>({...old,effective_date:treasuryToday(new Date(cutoff))}));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[api,kind,p.account_id,p.action,p.cutoff,p.resource_id,r.counts]);
 const account=r.accounts.find(a=>a.id===p.account_id),destination=r.accounts.find(a=>a.id===p.destination_account_id);
 const fund=r.funds.find(f=>f.id===p.resource_id),loan=r.loans.find(l=>l.id===p.resource_id);
 const field=(label:string,name:keyof SpecialInput,type='text',required=true)=><label className="text-xs font-semibold">{label}<input aria-label={label} className={fieldClass} type={type} required={required} disabled={kind==='cash_count'&&name==='effective_date'} step={type==='number'?'0.01':undefined} min={type==='number'?'0':undefined} maxLength={type==='text'?240:undefined} value={String(p[name]??'')} onChange={e=>patch({[name]:e.target.value})}/></label>;
 const chooseAccount=(label:string,name:'account_id'|'destination_account_id'|'fee_account_id',filter:(a:Resources['accounts'][number])=>boolean=()=>true)=><label className="text-xs font-semibold">{label}<AdaptiveSelect aria-label={label} className={fieldClass} required value={p[name]||''} onChange={e=>patch({[name]:e.target.value})}><option value="">Seleccionar cuenta</option>{r.accounts.filter(a=>a.is_active&&filter(a)).map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}{r.funds.some(f=>f.account_id===a.id&&f.status==='open')?' · bajo custodia':''}</option>)}</AdaptiveSelect></label>;
 async function submit(e:React.FormEvent){e.preventDefault();setError('');try{const plan=buildSpecialPlan(p,r,cut);setReview(plan);if((!available||!canWrite)&&!preview)return;const body={action:'save',payload:p};const signature=JSON.stringify(body);if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};setBusy(true);await api('/api/admin/special-financial-operations',{method:'POST',body:JSON.stringify({...body,key:pending.current.key})});onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 async function cancel(){if(!selected)return;try{const body={action:'cancel',operation_id:selected.id,version:selected.version,reason};const signature=JSON.stringify(body);if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};setBusy(true);await api('/api/admin/special-financial-operations',{method:'POST',body:JSON.stringify({...body,key:pending.current.key})});onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:'No se pudo anular.');}finally{setBusy(false);}}
 return <div ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label={operationLabels[kind]} className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-3"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white p-5"><div className="mb-4 flex justify-between"><h2 className="text-lg font-semibold">{operationLabels[kind]}</h2><button disabled={busy} onClick={onClose} className="rounded border px-3 py-1">Cerrar</button></div>
 {(!available||!canWrite||preview)&&<p className="mb-3 rounded-lg bg-blue-50 p-3 text-sm">{preview?'Prueba simulada con datos reales: no modifica la base.':!canWrite?'Tu usuario permite consultar y revisar los efectos; el guardado requiere permiso de administración.':'Podés completar el formulario y revisar sus efectos. El guardado de esta familia requiere activar su migración; no se registrará dinero real.'}</p>}
 {error&&<p role="alert" className="mb-3 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 {loading?<p>Cargando datos reales…</p>:selected?<div className="space-y-3"><p className="text-sm">{selected.detail.input.concept} · {selected.status}. Las operaciones compuestas se corrigen anulando y registrando nuevamente; se conservan las líneas originales.</p>{selected.status==='posted'&&<><label className="block text-xs font-semibold">Motivo de anulación<input className={fieldClass} minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!available||!canWrite||busy||reason.trim().length<3} onClick={cancel} className="rounded border border-red-300 px-4 py-2 text-red-700">Anular operación completa</button></>}<button onClick={()=>setSelected(null)} className="rounded border px-4 py-2">Nueva operación</button></div>:<form onSubmit={submit} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2">
 <label className="text-xs font-semibold">Acción<AdaptiveSelect aria-label="Acción" className={fieldClass} value={p.action} onChange={e=>{patch({action:e.target.value,resource_id:undefined,confirm:false});setCut(undefined);}}>{actions[kind].map(([id,label])=><option key={id} value={id}>{label}</option>)}</AdaptiveSelect></label>{field('Fecha','effective_date','date')}
 {chooseAccount(kind==='custody_fund'&&p.action==='return'?'Cuenta que recibe la devolución':'Cuenta','account_id')}
 <label className="text-xs font-semibold">Medio de pago<AdaptiveSelect aria-label="Medio de pago" className={fieldClass} required value={p.payment_method_id} onChange={e=>patch({payment_method_id:e.target.value})}><option value="">Seleccionar medio</option>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</AdaptiveSelect></label>
 {kind!=='cash_count'&&p.action!=='close'&&field(kind==='financing'?'Capital':`Importe ${account?.currency||''}`,'amount','number')}
 {kind==='currency_exchange'&&<>{chooseAccount('Cuenta de la otra moneda','destination_account_id',a=>a.id!==p.account_id&&a.currency!==account?.currency)}{field(`Importe recibido ${destination?.currency||''}`,'destination_amount','number')}{field('Comisión','fee','number',false)}{Number(p.fee)>0&&chooseAccount('Cuenta que paga la comisión','fee_account_id')}{Number(p.destination_amount)>0&&<p className="text-sm">Cotización: 1 {destination?.currency} = {(Number(p.amount)/Number(p.destination_amount)).toLocaleString('es-AR',{maximumFractionDigits:6})} {account?.currency}. La comisión se registra por separado.</p>}</>}
 {kind==='custody_fund'&&p.action==='deliver'&&<>{chooseAccount('Cuenta exclusiva de custodia','destination_account_id',a=>a.id!==p.account_id&&a.currency===account?.currency)}{field('Custodio','counterparty')}{field('Referencia del fondo','reference')}{field('Finalidad','purpose')}<p className="text-xs text-slate-600">La cuenta de custodia debe comenzar con saldo cero y estar dedicada al fondo. Su dinero no queda disponible en la caja de origen. <a className="underline" href="/admin/finanzas?tab=accounts">Administrar cuentas</a></p></>}
 {kind==='custody_fund'&&p.action!=='deliver'&&<><label className="text-xs font-semibold">Fondo<AdaptiveSelect aria-label="Fondo" className={fieldClass} required value={p.resource_id||''} onChange={e=>{const f=r.funds.find(f=>f.id===e.target.value);patch({resource_id:e.target.value,...(['expense','close'].includes(p.action)&&f?{account_id:f.account_id}:{})});}}><option value="">Seleccionar fondo abierto</option>{r.funds.filter(f=>f.status==='open').map(f=><option key={f.id} value={f.id}>{f.custodian} · {f.purpose} · {f.currency}</option>)}</AdaptiveSelect></label>{fund&&<p className="text-sm">En custodia: {fund.balance} {fund.currency} · Reintegros pendientes: {fund.pending} {fund.currency}.</p>}{p.action==='expense'&&<>{field('Referencia del gasto','reference')}<label className="flex gap-2 text-xs"><input type="checkbox" checked={p.personal_paid||false} onChange={e=>patch({personal_paid:e.target.checked})}/>El exceso sobre el fondo fue pagado por el custodio y debe reintegrarse.</label></>}</>}
 {kind==='financing'&&<>{['receive','lend'].includes(p.action)?<>{field('Contraparte','counterparty')}{field('Contrato o referencia','reference')}</>:<label className="text-xs font-semibold">Financiación<AdaptiveSelect aria-label="Financiación" className={fieldClass} required value={p.resource_id||''} onChange={e=>patch({resource_id:e.target.value})}><option value="">Seleccionar financiación</option>{r.loans.filter(l=>l.currency===account?.currency&&l.side===(p.action==='repay'?'borrower':'lender')&&Number(l.capital)>0).map(l=><option key={l.id} value={l.id}>{l.counterparty} · {l.reference} · pendiente {l.capital}</option>)}</AdaptiveSelect></label>}{field(['repay','collect'].includes(p.action)?'Intereses de esta cuota':'Costos del desembolso','fee','number',false)}{loan&&<p className="text-sm">Capital pendiente: {loan.capital} {loan.currency}. Capital e intereses generan líneas separadas.</p>}</>}
 {['partner_equity','asset_trade'].includes(kind)&&<>{field(kind==='partner_equity'?'Socio':'Contraparte','counterparty')}{field(kind==='partner_equity'?'Referencia':'Número de documento','reference')}{kind==='asset_trade'&&field('Bien identificado','asset_name')}{kind==='asset_trade'&&p.action==='purchase'&&<label className="flex gap-2 text-xs"><input type="checkbox" required checked={p.document_not_registered||false} onChange={e=>patch({document_not_registered:e.target.checked})}/>Este documento no está registrado en Compras. Si ya existe, cancelalo mediante Pago a proveedor.</label>}</>}
 {kind==='cash_count'&&<>{p.action==='adjust'?<label className="text-xs font-semibold">Arqueo pendiente<AdaptiveSelect aria-label="Arqueo pendiente" className={fieldClass} required value={p.resource_id||''} onChange={e=>patch({resource_id:e.target.value})}><option value="">Seleccionar arqueo</option>{r.counts.filter(c=>c.account_id===p.account_id&&c.status==='recorded').map(c=><option key={c.id} value={c.id}>{new Date(c.cutoff).toLocaleString('es-AR')} · esperado {c.expected} · contado {c.counted}</option>)}</AdaptiveSelect></label>:<><label className="text-xs font-semibold">Fecha y hora de corte<input className={fieldClass} type="datetime-local" required value={p.cutoff?new Date(new Date(p.cutoff).getTime()-new Date(p.cutoff).getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>{if(e.target.value)patch({cutoff:new Date(e.target.value).toISOString()});}}/></label>{field('Importe contado','counted','number')}</>}{cut&&<p className="text-sm">Saldo esperado al corte: {cut.balance} {account?.currency}. Registrar el conteo no mueve dinero.</p>}{p.action!=='record'&&<label className="flex gap-2 text-xs"><input type="checkbox" required checked={p.confirm||false} onChange={e=>patch({confirm:e.target.checked})}/>Confirmo {p.action==='opening'?'la apertura de una cuenta sin movimientos':'el ajuste por diferencia y su motivo'}.</label>}</>}
 </div>{field('Detalle','concept')}<label className="block text-xs font-semibold">Observaciones / motivo<textarea className={`${fieldClass} h-20 py-2`} required={kind==='cash_count'&&p.action==='adjust'} maxLength={4000} value={p.notes||''} onChange={e=>patch({notes:e.target.value})}/></label>
 <details className="rounded border p-3"><summary>Comprobantes ({p.voucher_ids?.length||0})</summary>{vouchers.map(v=><label key={v.id} className="mt-2 flex gap-2 text-xs"><input type="checkbox" checked={p.voucher_ids?.includes(v.id)||false} onChange={e=>patch({voucher_ids:e.target.checked?[...(p.voucher_ids||[]),v.id]:(p.voucher_ids||[]).filter(id=>id!==v.id)})}/>{v.reference||v.id.slice(0,8)}</label>)}<a href="/admin/comprobantes-tesoreria" target="_blank" rel="noopener noreferrer" className="mt-2 block text-xs underline">Administrar comprobantes (otra pestaña)</a><button type="button" disabled={refreshingVouchers} onClick={refreshVouchers} className="mt-2 text-xs text-brand-700 underline disabled:opacity-50">{refreshingVouchers?"Actualizando…":"Actualizar comprobantes"}</button><p className="mt-1 text-xs text-slate-500">El formulario queda abierto. Después de crear un comprobante en la otra pestaña, actualizá la lista para seleccionarlo.</p></details>
 {review&&<div className="rounded-lg bg-slate-50 p-3 text-sm"><h3 className="font-semibold">Efectos previstos · todavía sin guardar</h3>{review.lines.map(l=><p key={l.line}>{l.direction} · {r.accounts.find(a=>a.id===l.account_id)?.name} · {l.amount} {r.accounts.find(a=>a.id===l.account_id)?.currency} · {l.category}</p>)}{!review.lines.length&&<p>Sin movimiento de dinero.</p>}{review.fund&&<p>Cambio en custodia: {review.fund.balance_delta} · obligación de reintegro: {review.fund.pending_delta}.</p>}{review.loan&&<p>Cambio del capital pendiente: {review.loan.capital_delta}.</p>}</div>}
 <div className="flex justify-end gap-2"><button type="button" onClick={onClose} disabled={busy} className="rounded border px-4 py-2">Cerrar</button><button disabled={busy} className="rounded bg-brand-600 px-4 py-2 text-white">{busy?'Procesando…':preview?'Simular operación':available&&canWrite?'Guardar operación':'Revisar efectos sin guardar'}</button></div></form>}
 {!loading&&!selected&&history.filter(o=>o.operation_type===kind).length>0&&<details className="mt-4 rounded border p-3"><summary>Operaciones de esta familia · últimas 100 del circuito</summary>{history.filter(o=>o.operation_type===kind).map(o=><button key={o.id} onClick={()=>setSelected(o)} className="mt-2 block w-full rounded border p-2 text-left text-xs">{o.detail.input.effective_date} · {o.detail.input.concept} · {o.status}</button>)}</details>}
 </div></div>;
}
