"use client";
import {useState} from 'react';
import SelectionModal from './SelectionModal';
import {fieldClass,purchaseLabel,purchaseOrderCodes,type PurchaseOption} from './OperationFields';
import type {OperationInput} from '@/lib/financialOperations/types';
import {oldestSupplierAllocations,supplierDocumentPending,payableSupplierDocuments} from '@/lib/financialOperations/supplierAllocation';
import {moneyValue} from '@/lib/financialOperations/validation';

type Allocation=NonNullable<OperationInput['allocations']>[number];
const money=(amount:number,currency:string)=>`${currency} ${amount.toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const pending=supplierDocumentPending;
function DocumentIdentity({purchase:p}:{purchase:PurchaseOption}) {
 const receipt=p.purchase_receptions;
 const order=purchaseOrderCodes(p);
 const number=receipt?.delivery_slip_number;
 return <div className="min-w-0"><p className="font-semibold text-slate-800">{receipt?'Documento de recepción':p.document_type||'Documento de compra'}{number?` · Remito ${number}`:!receipt&&p.invoice_number?` · ${p.invoice_number}`:''}</p><dl className="mt-1 flex flex-wrap gap-x-5 gap-y-1 text-xs text-slate-500">{receipt&&<div><dt className="inline">Comprobante: </dt><dd className="inline font-medium text-slate-700">{p.invoice_number||'Sin número cargado'}</dd></div>}{order&&<div><dt className="inline">Orden de compra: </dt><dd className="inline font-medium text-slate-700">{order}</dd></div>}{(receipt?.reception_date||p.purchase_date)&&<div><dt className="inline">Fecha: </dt><dd className="inline">{(receipt?.reception_date||p.purchase_date||'').slice(0,10).split('-').reverse().join('/')}</dd></div>}</dl>{receipt&&!number&&<p className="mt-1 text-xs text-slate-500">Recepción sin número de remito cargado.</p>}</div>;
}
export default function SupplierDocuments({value,onChange,purchases,supplierName,currency}:{value:OperationInput;onChange:(value:OperationInput)=>void;purchases:PurchaseOption[];supplierName:string;currency?:string}) {
 const [open,setOpen]=useState(false),[draft,setDraft]=useState<Allocation[]>([]),[query,setQuery]=useState(''),[error,setError]=useState('');
 const automatic=value.detail.supplier_allocation_mode==='oldest_first';
 const selectedCurrency=currency||purchases[0]?.currency||'ARS';
 purchases=payableSupplierDocuments(purchases,value.supplier_id||'',selectedCurrency);
 const allocations=automatic?oldestSupplierAllocations(purchases,value.supplier_id||'',selectedCurrency,value.amount,value.effective_date):value.allocations||[];
 const assigned=allocations.reduce((sum,a)=>sum+Number(a.amount),0);
 const draftTotal=draft.reduce((sum,a)=>sum+(Number(a.amount)||0),0);
 const remainder=Number(value.amount||0)-assigned;
 const filtered=purchases.filter(p=>[purchaseLabel(p),p.document_type].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const update=(id:string,amount:string)=>{setError('');setDraft(rows=>rows.map(a=>a.purchase_id===id?{...a,amount}:a));};
 const toggle=(p:PurchaseOption)=>{setError('');setDraft(rows=>{if(rows.some(a=>a.purchase_id===p.id))return rows.filter(a=>a.purchase_id!==p.id);const remaining=Number(value.amount||0)-rows.reduce((sum,a)=>sum+(Number(a.amount)||0),0);return [...rows,{purchase_id:p.id,amount:(remaining>0?Math.min(pending(p),remaining):pending(p)).toFixed(2)}];});};
 const apply=()=>{try{let total=0;for(const a of draft){const p=purchases.find(p=>p.id===a.purchase_id);if(!p)throw new Error('Uno de los documentos ya no está disponible.');const cents=moneyValue(a.amount);if(cents>Math.round(pending(p)*100))throw new Error('El importe a pagar supera el saldo pendiente de un documento.');total+=cents;}if(value.amount&&total>moneyValue(value.amount))throw new Error('El total asignado supera el importe del pago. Ajustá los importes o quitá un documento.');onChange({...value,detail:{...value.detail,supplier_allocation_mode:'documents'},allocations:draft.map(a=>({...a})),...(!value.amount&&total>0?{amount:(total/100).toFixed(2)}:{})});setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Revisá los importes.');}};
 return <section className="rounded-xl border border-slate-200 bg-slate-50/60 p-3"><div className="mb-3 grid grid-cols-2 gap-2" role="group" aria-label="Aplicación del pago">{([['oldest_first','Cuenta corriente'],['documents','Documentos específicos']] as const).map(([mode,label])=><button key={mode} type="button" aria-pressed={automatic===(mode==='oldest_first')} onClick={()=>onChange({...value,allocations:mode==='documents'?allocations:[],detail:{...value.detail,supplier_allocation_mode:mode}})} className={`rounded-lg border px-3 py-2 text-sm font-medium ${automatic===(mode==='oldest_first')?'border-blue-300 bg-blue-50 text-blue-800':'border-slate-200 bg-white text-slate-600'}`}>{label}</button>)}</div><p className="mb-3 text-xs text-slate-600">{automatic?'El pago se aplica primero a los documentos más antiguos pendientes a la fecha del pago.':'Elegí qué documentos pagar y el importe para cada uno.'}</p><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold">{automatic?'Distribución del pago':'Documentos a pagar'}</h3><p className="mt-1 text-xs text-slate-500">{allocations.length?`${allocations.length} documento${allocations.length===1?'':'s'} ${automatic?'a cubrir':`seleccionado${allocations.length===1?'':'s'}`} · ${money(assigned,currency||purchases[0]?.currency||'ARS')}`:automatic?(value.amount?'No hay documentos pendientes a la fecha de este pago.':'Ingresá el importe para ver cómo se distribuye el pago.'):'Seleccioná documentos o dejá el pago a cuenta del proveedor.'}</p></div><button type="button" disabled={!purchases.length} onClick={()=>{setDraft(allocations.map(a=>({...a})));setQuery('');setError('');setOpen(true);}} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium disabled:opacity-50">{automatic?'Revisar distribución':allocations.length?'Revisar documentos':'Seleccionar documentos'}</button></div>
 {!automatic&&allocations.length>0&&<div className="mt-3 space-y-2">{allocations.map(a=>{const p=purchases.find(p=>p.id===a.purchase_id);return <div key={a.purchase_id} className="flex flex-wrap items-start justify-between gap-2 rounded-lg bg-white p-3 text-sm">{p?<DocumentIdentity purchase={p}/>:<span>Documento seleccionado</span>}<div className="flex items-center gap-3"><span className="font-semibold">{money(Number(a.amount),p?.currency||'ARS')}</span><button type="button" className="text-xs text-slate-500 underline" aria-label={`Quitar documento ${p?.invoice_number||''}`} onClick={()=>onChange({...value,allocations:allocations.filter(row=>row.purchase_id!==a.purchase_id)})}>Quitar</button></div></div>;})}</div>}
 {!purchases.length&&<p className="mt-2 text-xs text-slate-500">No hay documentos pendientes en la moneda de esta cuenta. El pago quedará a cuenta del proveedor.</p>}{value.amount&&remainder!==0&&<p className={`mt-3 text-xs ${remainder<0?'text-red-700':'text-slate-600'}`}>{remainder<0?`El total asignado supera el pago en ${money(-remainder,currency||purchases[0]?.currency||'ARS')}.`:automatic&&purchases.length?`Anticipo por encima de la deuda de los documentos: ${money(remainder,selectedCurrency)}`:`Pago a cuenta sin documento asociado: ${money(remainder,selectedCurrency)}`}</p>}
 {open&&<SelectionModal title={`Documentos a pagar · ${supplierName}`} onClose={()=>setOpen(false)} wide>{automatic&&<p className="mb-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-800">Esta es la distribución propuesta, del documento más antiguo al más nuevo. Confirmar permite personalizarla y cambia el pago a Documentos específicos; cancelar conserva la aplicación automática.</p>}<p className="mb-3 text-sm text-slate-600">Marcá las recepciones o comprobantes que vas a pagar. Podés pagar todo el saldo o solo una parte. La orden de compra indica el origen de la recepción.</p><input autoFocus aria-label="Buscar documento de proveedor" className={fieldClass} placeholder="Buscar remito, comprobante u orden de compra" value={query} onChange={e=>setQuery(e.target.value)}/><div className="mt-4 space-y-3">{filtered.map(p=>{const selected=draft.find(a=>a.purchase_id===p.id);return <article key={p.id} className={`rounded-xl border p-4 ${selected?'border-blue-300 bg-blue-50/40':'border-slate-200 bg-white'}`}><div className="flex items-start gap-3"><input type="checkbox" className="mt-1 h-4 w-4" aria-label={`Seleccionar documento ${p.invoice_number||'sin número'}`} checked={Boolean(selected)} onChange={()=>toggle(p)}/><div className="flex-1"><DocumentIdentity purchase={p}/><div className="mt-3 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Total del documento</p><p className="text-sm">{money(Number(p.total_amount),p.currency)}</p></div><div><p className="text-xs text-slate-500">Saldo pendiente</p><p className="text-sm font-semibold">{money(pending(p),p.currency)}</p></div>{selected&&<label className="text-xs font-semibold">Importe a pagar<input aria-label={`Importe a pagar ${p.invoice_number}`} className={`${fieldClass} mt-1`} type="number" min="0.01" max={pending(p)} step="0.01" value={selected.amount} onChange={e=>update(p.id,e.target.value)}/></label>}</div></div></div></article>;})}</div>{!filtered.length&&<p className="my-4 text-sm text-slate-500">Sin documentos para esta búsqueda.</p>}<div className="sticky bottom-0 mt-4 border-t border-slate-200 bg-white pt-3"><div className="flex flex-wrap justify-between gap-2 text-sm"><span>{draft.length} documento{draft.length===1?'':'s'} seleccionado{draft.length===1?'':'s'}</span><strong>Total a pagar: {money(draftTotal,currency||purchases[0]?.currency||'ARS')}</strong></div>{!value.amount&&<p className="mt-1 text-xs text-slate-500">Al confirmar, este total completará el importe del pago.</p>}{error&&<p role="alert" className="mt-2 text-sm text-red-700">{error}</p>}<div className="mt-3 flex justify-end gap-2"><button type="button" className="rounded-lg border px-4 py-2 text-sm" onClick={()=>setOpen(false)}>Cancelar</button><button type="button" className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white" onClick={apply}>Confirmar documentos</button></div></div></SelectionModal>}
 </section>;
}
